<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LeaveTypesSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            [
                'code'                       => 'VL',
                'name'                       => 'Vacation Leave',
                'description'                => 'Leave for personal needs, rest and recreation.',
                'days_per_year'              => null,
                'is_creditable'              => true,
                'is_deductible'              => true,
                'requires_approval'          => true,
                'min_days_notice'            => 5,
                'max_days_per_application'   => null,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 1,
            ],
            [
                'code'                       => 'SL',
                'name'                       => 'Sick Leave',
                'description'                => 'Leave for illness, injury, or medical/dental appointments.',
                'days_per_year'              => null,
                'is_creditable'              => true,
                'is_deductible'              => true,
                'requires_approval'          => true,
                'min_days_notice'            => 0,
                'max_days_per_application'   => null,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 2,
            ],
            [
                'code'                       => 'ML',
                'name'                       => 'Maternity Leave',
                'description'                => '105 days paid maternity leave (RA 11210).',
                'days_per_year'              => 105,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => true,
                'min_days_notice'            => 30,
                'max_days_per_application'   => 105,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 3,
            ],
            [
                'code'                       => 'PL',
                'name'                       => 'Paternity Leave',
                'description'                => '7 working days paternity leave (RA 8187).',
                'days_per_year'              => 7,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => true,
                'min_days_notice'            => 0,
                'max_days_per_application'   => 7,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 4,
            ],
            [
                'code'                       => 'SPL',
                'name'                       => 'Special Privilege Leave',
                'description'                => '3 days per year for personal milestones (CSC MC 41 s. 1998).',
                'days_per_year'              => 3,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => true,
                'min_days_notice'            => 0,
                'max_days_per_application'   => 3,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 5,
            ],
            [
                'code'                       => 'SL-VAWC',
                'name'                       => 'VAWC Leave',
                'description'                => '10 days for female employees who are victims of violence against women and children (RA 9262).',
                'days_per_year'              => 10,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => true,
                'min_days_notice'            => 0,
                'max_days_per_application'   => 10,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 6,
            ],
            [
                'code'                       => 'FL',
                'name'                       => 'Force Leave',
                'description'                => 'Mandatory 5-day utilization of VL each year.',
                'days_per_year'              => 5,
                'is_creditable'              => true,
                'is_deductible'              => true,
                'requires_approval'          => false,
                'min_days_notice'            => 0,
                'max_days_per_application'   => 5,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent"]',
                'is_active'                  => true,
                'sort_order'                 => 7,
            ],
            [
                'code'                       => 'CTO',
                'name'                       => 'Compensatory Time Off',
                'description'                => 'Offsetting of overtime rendered (CSC MC 53 s. 1993).',
                'days_per_year'              => null,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => true,
                'min_days_notice'            => 0,
                'max_days_per_application'   => null,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 8,
            ],
            [
                'code'                       => 'SL-SOLO',
                'name'                       => 'Solo Parent Leave',
                'description'                => '7 working days parental leave for solo parents (RA 8972).',
                'days_per_year'              => 7,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => true,
                'min_days_notice'            => 0,
                'max_days_per_application'   => 7,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 9,
            ],
            [
                'code'                       => 'STUDY',
                'name'                       => 'Study Leave',
                'description'                => 'Leave granted to pursue master\'s degree or BAR/Board exam review (CSC MC 6 s. 1996).',
                'days_per_year'              => null,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => true,
                'min_days_notice'            => 30,
                'max_days_per_application'   => null,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent"]',
                'is_active'                  => true,
                'sort_order'                 => 10,
            ],
            [
                'code'                       => 'RP',
                'name'                       => 'Rehabilitation Privilege',
                'description'                => 'Leave for rehabilitation due to work-related injuries.',
                'days_per_year'              => null,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => true,
                'min_days_notice'            => 0,
                'max_days_per_application'   => null,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 11,
            ],
            [
                'code'                       => 'SLBW',
                'name'                       => 'Special Leave Benefits for Women',
                'description'                => 'Leave for female employees who undergo surgery for gynecological disorders (RA 9710).',
                'days_per_year'              => null,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => true,
                'min_days_notice'            => 5,
                'max_days_per_application'   => 60,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 12,
            ],
            [
                'code'                       => 'SECL',
                'name'                       => 'Special Emergency (Calamity) Leave',
                'description'                => 'Leave for employees in areas declared under state of calamity.',
                'days_per_year'              => null,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => true,
                'min_days_notice'            => 0,
                'max_days_per_application'   => 5,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 13,
            ],
            [
                'code'                       => 'AL',
                'name'                       => 'Adoption Leave',
                'description'                => 'Leave for adoptive parents (RA 8552).',
                'days_per_year'              => null,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => true,
                'min_days_notice'            => 0,
                'max_days_per_application'   => null,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 14,
            ],
            [
                'code'                       => 'MONO',
                'name'                       => 'Monetization of Leave Credits',
                'description'                => 'Conversion of accumulated leave credits to cash (CSC-DBM JC No. 2 s. 2012).',
                'days_per_year'              => null,
                'is_creditable'              => false,
                'is_deductible'              => true,
                'requires_approval'          => true,
                'min_days_notice'            => 0,
                'max_days_per_application'   => null,
                'with_pay'                   => false,
                'applicable_employment_types' => '["permanent"]',
                'is_active'                  => true,
                'sort_order'                 => 15,
            ],
            [
                'code'                       => 'TL',
                'name'                       => 'Terminal Leave',
                'description'                => 'Commutation of all accumulated leave credits upon retirement or separation.',
                'days_per_year'              => null,
                'is_creditable'              => false,
                'is_deductible'              => true,
                'requires_approval'          => true,
                'min_days_notice'            => 0,
                'max_days_per_application'   => null,
                'with_pay'                   => false,
                'applicable_employment_types' => '["permanent"]',
                'is_active'                  => true,
                'sort_order'                 => 16,
            ],
            [
                'code'                       => 'WL',
                'name'                       => 'Wellness Leave',
                'description'                => 'Leave for employee wellness and mental health.',
                'days_per_year'              => null,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => true,
                'min_days_notice'            => 0,
                'max_days_per_application'   => null,
                'with_pay'                   => true,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 18,
            ],
            [
                'code'                       => 'AWOL',
                'name'                       => 'Absent Without Leave',
                'description'                => 'Unauthorized absence; results in salary deduction and disciplinary action.',
                'days_per_year'              => null,
                'is_creditable'              => false,
                'is_deductible'              => false,
                'requires_approval'          => false,
                'min_days_notice'            => 0,
                'max_days_per_application'   => null,
                'with_pay'                   => false,
                'applicable_employment_types' => '["permanent","casual","contractual","coterminous","substitute"]',
                'is_active'                  => true,
                'sort_order'                 => 17,
            ],
        ];

        foreach ($types as $type) {
            DB::table('leave_types')->updateOrInsert(
                ['code' => $type['code']],
                array_merge($type, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
