<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Controllers\ITJobRequestController;
use App\Models\ICTEquipment;
use App\Models\AtlasSentinelRelease;
use App\Models\BiometricDevice;
use App\Models\IctEquipmentAlert;
use App\Models\IctEquipmentDevice;
use App\Models\IctEquipmentEnrollmentToken;
use App\Models\IctEquipmentHardwareInventory;
use App\Models\IctEquipmentHardwareInventoryChange;
use App\Models\IctEquipmentHealthHistory;
use App\Models\IctEquipmentHealthSnapshot;
use App\Models\IctEquipmentSecurityStatus;
use App\Models\IctEquipmentSoftwareInventory;
use App\Models\IctBackupRun;
use App\Models\IctEquipmentRemediationLog;
use App\Models\ITJobCategory;
use App\Models\User;
use App\Services\AtlasSentinelBackupService;
use App\Services\AtlasSentinelDiagnosticsService;
use App\Services\AtlasSentinelHealthEvaluator;
use App\Services\AtlasSentinelNetworkLocationResolver;
use App\Services\AtlasSentinelFleetStateService;
use App\Services\AtlasSentinelRemediationDispatcher;
use App\Services\AtlasSentinelRemoteHelpService;
use App\Services\AtlasSentinelScoringService;
use App\Services\AtlasSentinelSecurityEvaluator;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;

class AtlasSentinelController extends Controller
{
    // Generic/assembled motherboards routinely report one of these instead
    // of a real BIOS serial — identical across every machine that hits it,
    // not just blank on one. The agent's own fallback for a blank read is
    // literally "UNKNOWN-SERIAL", which is just as collision-prone.
    private const UNRELIABLE_SERIALS = [
        '', 'unknown-serial', 'to be filled by o.e.m.', 'system serial number',
        'default string', 'none', 'not specified', '0123456789', '1234567890',
        'serial number', 'n/a', 'na', 'o.e.m.', 'oem', 'not available',
        'not applicable', 'invalid', 'unknown', 'chassis serial number',
        'base board serial number', 'mainboard serial number',
    ];

    public function __construct(
        private AtlasSentinelHealthEvaluator $healthEvaluator,
        private ITJobRequestController $jobRequests,
        private AtlasSentinelNetworkLocationResolver $networkLocationResolver,
        private AtlasSentinelScoringService $scoringService,
        private AtlasSentinelDiagnosticsService $diagnosticsService,
        private AtlasSentinelSecurityEvaluator $securityEvaluator,
        private AtlasSentinelRemediationDispatcher $remediationDispatcher,
        private AtlasSentinelBackupService $backupService,
        private AtlasSentinelFleetStateService $fleetStateService,
        private AtlasSentinelRemoteHelpService $remoteHelpService,
    ) {
    }

    /**
     * POST /api/ict-agent/enroll
     *
     * Exchanges a one-time enrollment token (generated by MIS in the ICT
     * Equipments page) for a long-lived device token. Matches the reported
     * serial number against an existing ict_equipments row; if none exists,
     * creates a draft row for MIS to complete later instead of blocking
     * enrollment.
     */
    public function enroll(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'enrollment_token' => ['required', 'string'],
            'serial_no'        => ['required', 'string', 'max:255'],
            'hostname'         => ['nullable', 'string', 'max:255'],
            'mac_address'      => ['nullable', 'string', 'max:20'],
            'os_version'       => ['nullable', 'string', 'max:255'],
            'agent_version'    => ['nullable', 'string', 'max:20'],
            'model'            => ['nullable', 'string', 'max:255'],
        ]);

        $enrollmentToken = IctEquipmentEnrollmentToken::where('token', $validated['enrollment_token'])
            ->whereNull('revoked_at')
            ->where('expires_at', '>', now())
            ->where(function ($query) {
                $query->whereNull('max_uses')->orWhereColumn('uses_count', '<', 'max_uses');
            })
            ->first();

        if (! $enrollmentToken) {
            return response()->json([
                'message' => 'This enrollment token is invalid, expired, already used up, or revoked.',
            ], 422);
        }

        $serial = trim($validated['serial_no']);
        $hostname = $validated['hostname'] ?? null;
        $mac = $this->normalizeMac($validated['mac_address'] ?? null);
        $matchSource = null;
        $cloneCollision = false;

        $equipment = $this->isUnreliableSerial($serial) ? null : ICTEquipment::where('serial_no', $serial)->first();

        if ($equipment) {
            $matchSource = 'serial';
            $existingDevice = IctEquipmentDevice::where('equipment_id', $equipment->id)->latest('id')->first();

            if ($this->isIdentityConflict($existingDevice, $mac)) {
                $cloneCollision = true;
                logger()->warning('Atlas Sentinel: serial match looked like a cloned/generic desktop; creating Pending Setup equipment instead of reclaiming existing row.', [
                    'matched_equipment_id' => $equipment->id,
                    'matched_device_id' => $existingDevice?->id,
                    'previous_hostname' => $existingDevice?->hostname,
                    'new_hostname' => $hostname,
                    'serial_no' => $serial,
                    'mac_address' => $mac,
                ]);
                $equipment = null;
                $matchSource = null;
            }
        }

        // A MAC-address match is, by construction, always the same MAC — the
        // agent's hostname is expected to change across a reformat/reimage,
        // so it's not treated as a collision signal here.
        if (! $equipment && $mac && ! $cloneCollision) {
            $deviceByMac = IctEquipmentDevice::where('mac_address', $mac)->latest('id')->first();
            if ($deviceByMac) {
                $equipment = ICTEquipment::find($deviceByMac->equipment_id);
                $matchSource = 'mac';
            }
        }

        $linked = (bool) $equipment;

        if (! $equipment) {
            $equipment = $this->createPendingEquipment($validated, $serial, $mac, $cloneCollision);
            $matchSource = $cloneCollision ? 'clone_collision_pending_setup' : 'pending_setup';
        }

        // Re-running install.ps1 on a machine already matched to this
        // equipment (re-enrollment, reinstall) reuses its device row instead
        // of leaving the old one stale forever with a dead token.
        $device = IctEquipmentDevice::where('equipment_id', $equipment->id)->latest('id')->first();

        if ($device && $device->hostname && $hostname && $device->hostname !== $hostname) {
            logger()->warning('Atlas Sentinel: device row reclaimed under a different hostname — possible serial/MAC collision or legitimate reinstall.', [
                'equipment_id' => $equipment->id,
                'previous_hostname' => $device->hostname,
                'new_hostname' => $hostname,
                'serial_no' => $serial,
                'mac_address' => $mac,
            ]);
        }

        $deviceAttributes = [
            'equipment_id'     => $equipment->id,
            'hostname'         => $hostname,
            'mac_address'      => $mac,
            'os_version'       => $validated['os_version'] ?? null,
            'agent_version'    => $validated['agent_version'] ?? null,
            'last_checkin_at'  => now(),
        ];

        if ($device) {
            $device->tokens()->delete();
            $device->update($deviceAttributes);
        } else {
            $device = IctEquipmentDevice::create($deviceAttributes);
        }

        $deviceToken = $device->createToken('ict-agent', ['ict-agent'])->plainTextToken;

        $enrollmentToken->increment('uses_count');
        if (! $enrollmentToken->used_at) {
            $enrollmentToken->update(['used_at' => now()]);
        }

        return response()->json([
            'device_token' => $deviceToken,
            'equipment_id' => $equipment->id,
            'linked'       => $linked,
            'match_source' => $matchSource,
        ], 201);
    }

    private function createPendingEquipment(array $validated, string $serial, ?string $mac, bool $cloneCollision): ICTEquipment
    {
        $hostname = $validated['hostname'] ?? 'unknown host';
        $description = $validated['model'] ?? "Auto-detected device — {$hostname}";

        if ($mac) {
            $description .= " (MAC {$mac})";
        }

        return ICTEquipment::create([
            'category'    => 'Other',
            'serial_no'   => $serial,
            'description' => $description,
            'status'      => 'Pending Setup',
            'remarks'     => $cloneCollision
                ? 'Atlas Sentinel detected a cloned or duplicate hardware identity during enrollment. Review before merging with an existing equipment record.'
                : null,
        ]);
    }

    private function isIdentityConflict(?IctEquipmentDevice $existingDevice, ?string $newMac): bool
    {
        if (! $existingDevice) {
            return false;
        }

        // Hostname is deliberately not part of this check — a reformat/reimage
        // routinely assigns a new hostname to the same physical machine, so
        // treating that alone as a collision forked a duplicate equipment
        // record on every legitimate reformat + re-enroll. MAC address is a
        // hardware property of the NIC and doesn't legitimately change here,
        // so it remains the sole signal for a genuine identity conflict
        // (e.g. a shared/generic serial number reused across two different
        // physical units).
        $existingMac = $this->normalizeMac($existingDevice->mac_address);

        return (bool) ($newMac && $existingMac && $existingMac !== $newMac);
    }

    private function normalizeMac(?string $mac): ?string
    {
        $mac = strtolower(trim((string) $mac));

        return $mac !== '' ? $mac : null;
    }

    private function isUnreliableSerial(?string $serial): bool
    {
        return in_array(strtolower(trim($serial ?? '')), self::UNRELIABLE_SERIALS, true);
    }

    /**
     * GET /api/ict-agent/me
     *
     * Sanity-check endpoint for the agent to confirm its device token still
     * resolves correctly and to see which equipment record it's linked to.
     */
    public function me(Request $request): JsonResponse
    {
        $device = $request->user();

        return response()->json([
            'device_id'    => $device->id,
            'equipment_id' => $device->equipment_id,
            'hostname'     => $device->hostname,
            'last_checkin_at' => $device->last_checkin_at,
        ]);
    }

    /**
     * POST /api/ict-agent/checkin
     *
     * Periodic hardware/peripheral snapshot from an enrolled device. Stores
     * the latest snapshot (overwritten each check-in) and runs it through
     * AtlasSentinelHealthEvaluator, which logs routine findings into the
     * equipment's existing PMS history and tracks actionable findings as
     * open alerts.
     */
    public function checkin(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'cpu'           => ['nullable', 'string', 'max:255'],
            'cpu_usage_pct' => ['nullable', 'numeric'],
            'cpu_temp_c'    => ['nullable', 'numeric'],
            'ram_total_mb'  => ['nullable', 'integer'],
            'ram_free_mb'   => ['nullable', 'integer'],
            'uptime_seconds' => ['nullable', 'integer'],
            'disks'         => ['nullable', 'array'],
            'disks.*.drive'    => ['nullable', 'string', 'max:10'],
            'disks.*.total_gb' => ['nullable', 'numeric'],
            'disks.*.free_gb'  => ['nullable', 'numeric'],
            'printers'      => ['nullable', 'array'],
            'printers.*.name'                  => ['nullable', 'string', 'max:255'],
            'printers.*.detected_error_state'  => ['nullable', 'string', 'max:50'],
            'printers.*.pending_jobs'          => ['nullable', 'integer'],
            'printers.*.is_default'            => ['nullable', 'boolean'],
            'pnp_issues'    => ['nullable', 'array'],
            'pnp_issues.*.device_name' => ['nullable', 'string', 'max:255'],
            'pnp_issues.*.error_code'  => ['nullable', 'string', 'max:50'],
            'network'                      => ['nullable', 'array'],
            'network.gateway_latency_ms'   => ['nullable', 'numeric'],
            'network.packet_loss_pct'      => ['nullable', 'numeric'],
            'network.link_speed_mbps'      => ['nullable', 'integer'],
            'network.link_up'              => ['nullable', 'boolean'],
            'network.local_ip'             => ['nullable', 'string', 'max:45'],
            'services'      => ['nullable', 'array'],
            'services.*.name'   => ['nullable', 'string', 'max:255'],
            'services.*.status' => ['nullable', 'string', 'max:50'],
            'os_version'    => ['nullable', 'string', 'max:255'],
            'agent_version' => ['nullable', 'string', 'max:20'],
            'wifi_ssid'     => ['nullable', 'string', 'max:255'],
            'wifi_bssid'    => ['nullable', 'string', 'max:50'],
            'update_result' => ['nullable', 'array'],
            'update_result.version' => ['nullable', 'string', 'max:20'],
            'update_result.result'  => ['nullable', 'string', 'in:success,failed,failed_service_down,vanished'],
            'update_result.details' => ['nullable', 'string', 'max:2000'],
            'remediation_results'   => ['nullable', 'array'],
            'remediation_results.*.action'       => ['nullable', 'string', 'max:50'],
            'remediation_results.*.target'       => ['nullable', 'string', 'max:255'],
            'remediation_results.*.trigger_code' => ['nullable', 'string', 'max:50'],
            'remediation_results.*.result'       => ['nullable', 'string', 'in:success,failed'],
            'remediation_results.*.details'      => ['nullable', 'string'],
        ]);

        $device = $request->user();

        IctEquipmentHealthSnapshot::updateOrCreate(
            ['device_id' => $device->id],
            ['payload' => $validated, 'recorded_at' => now()]
        );

        $historyRow = IctEquipmentHealthHistory::create([
            'device_id'   => $device->id,
            'payload'     => $validated,
            'recorded_at' => now(),
        ]);

        $networkLocation = $this->networkLocationResolver->resolve($validated['wifi_ssid'] ?? null, $request->ip());

        $deviceUpdate = [
            'last_checkin_at'   => now(),
            'stale_notified_at' => null,
            'os_version'        => $validated['os_version'] ?? $device->os_version,
            'agent_version'     => $validated['agent_version'] ?? $device->agent_version,
        ];

        if ($networkLocation !== $device->network_location) {
            $deviceUpdate['network_location'] = $networkLocation;
            $deviceUpdate['network_location_changed_at'] = now();
        }

        if (isset($validated['update_result']['result'])) {
            $deviceUpdate['last_update_attempted_at'] = now();
            $deviceUpdate['last_update_result'] = $validated['update_result']['result'];
            $deviceUpdate['last_update_details'] = $validated['update_result']['details'] ?? null;
        }

        $device->update($deviceUpdate);

        $this->healthEvaluator->evaluate($device, $validated);
        $this->diagnosticsService->diagnoseFastLoop($device, $validated);
        $this->scoringService->scoreAndStore($device, $validated, $historyRow);

        if (! empty($validated['remediation_results'])) {
            $this->remediationDispatcher->recordResults($device, $validated['remediation_results']);
        }

        $response = ['status' => 'ok'];

        $pendingRemediations = $this->remediationDispatcher->pendingActions($device, $validated);
        if ($pendingRemediations) {
            $response['remediations'] = $pendingRemediations;
        }

        // A backup hiccup must never take health monitoring down with it.
        try {
            $backup = $this->backupService->pendingBackup($device);
            if ($backup) {
                $response['backup'] = $backup;
            }
        } catch (\Throwable $e) {
            logger()->error('Atlas Sentinel: backup dispatch failed during checkin', [
                'device_id' => $device->id,
                'error' => $e->getMessage(),
            ]);
        }

        // A biometric bridge lookup hiccup must never take health monitoring down with it.
        try {
            $biometricBridge = BiometricDevice::where('ict_equipment_device_id', $device->id)
                ->where('is_active', true)
                ->first();
            if ($biometricBridge) {
                $response['biometric_bridge'] = [
                    'device_key'    => $biometricBridge->device_key,
                    'label'         => $biometricBridge->label,
                    'receiver_port' => $biometricBridge->receiver_port,
                ];
            }
        } catch (\Throwable $e) {
            logger()->error('Atlas Sentinel: biometric bridge lookup failed during checkin', [
                'device_id' => $device->id,
                'error' => $e->getMessage(),
            ]);
        }

        $latestRelease = AtlasSentinelRelease::latestRelease();
        $reportedVersion = $validated['agent_version'] ?? $device->agent_version ?? null;
        if ($latestRelease
            && $this->fleetStateService->shouldOfferUpdate($latestRelease->version, $reportedVersion)
            && $this->fleetStateService->tryReserveUpdateOfferSlot($latestRelease->version)) {
            $response['update'] = [
                'version'      => $latestRelease->version,
                'download_url' => route('ict-agent.releases.show', ['encodedKey' => $this->encodeS3Key($latestRelease->s3_key)]),
                'sha256'       => $latestRelease->sha256,
            ];
        }

        return response()->json($response);
    }

    /**
     * POST /api/ict-agent/inventory-checkin
     *
     * Daily (slow-loop) hardware/software/security inventory — separate
     * from the 20-min checkin() so data that barely changes doesn't churn
     * the DB 72x/day. Hardware changes are diffed against the previous
     * snapshot before being overwritten, so swaps (new RAM, new disk) are
     * traceable; everything else is latest-only, same pattern as
     * IctEquipmentHealthSnapshot.
     */
    public function inventoryCheckin(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'hardware'                       => ['nullable', 'array'],
            'hardware.cpu_model'              => ['nullable', 'string', 'max:255'],
            'hardware.cpu_cores'              => ['nullable', 'integer'],
            'hardware.ram_modules'            => ['nullable', 'array'],
            'hardware.ram_modules.*.slot'      => ['nullable', 'string', 'max:50'],
            'hardware.ram_modules.*.size_mb'   => ['nullable', 'integer'],
            'hardware.ram_modules.*.speed_mhz' => ['nullable', 'integer'],
            'hardware.disks'                  => ['nullable', 'array'],
            'hardware.disks.*.drive'          => ['nullable', 'string', 'max:50'],
            'hardware.disks.*.model'          => ['nullable', 'string', 'max:255'],
            'hardware.disks.*.serial'         => ['nullable', 'string', 'max:255'],
            'hardware.disks.*.smart_status'   => ['nullable', 'string', 'max:20'],
            'hardware.disks.*.wear_level_pct' => ['nullable', 'numeric'],
            'hardware.gpu'                    => ['nullable', 'array'],
            'hardware.gpu.name'               => ['nullable', 'string', 'max:255'],
            'hardware.gpu.vram_mb'            => ['nullable', 'integer'],
            'hardware.peripherals'            => ['nullable', 'array'],
            'hardware.peripherals.*.type'     => ['nullable', 'string', 'max:50'],
            'hardware.peripherals.*.name'     => ['nullable', 'string', 'max:255'],
            'hardware.battery'                => ['nullable', 'array'],
            'hardware.battery.design_capacity_mwh'      => ['nullable', 'integer'],
            'hardware.battery.full_charge_capacity_mwh' => ['nullable', 'integer'],
            'hardware.battery.cycle_count'              => ['nullable', 'integer'],
            'software'                        => ['nullable', 'array'],
            'software.installed'              => ['nullable', 'array'],
            'software.installed.*.name'         => ['nullable', 'string', 'max:255'],
            'software.installed.*.version'      => ['nullable', 'string', 'max:100'],
            'software.installed.*.publisher'    => ['nullable', 'string', 'max:255'],
            'software.installed.*.install_date' => ['nullable', 'string', 'max:50'],
            'software.installed.*.uninstall_key'           => ['nullable', 'string', 'max:255'],
            'software.installed.*.quiet_uninstall_string'  => ['nullable', 'string', 'max:1000'],
            'software.installed.*.is_msi'                  => ['nullable', 'boolean'],
            'security'                         => ['nullable', 'array'],
            'security.antivirus_enabled'       => ['nullable', 'boolean'],
            'security.antivirus_up_to_date'    => ['nullable', 'boolean'],
            'security.firewall_enabled'        => ['nullable', 'boolean'],
            'security.pending_updates_count'   => ['nullable', 'integer'],
            'security.last_update_installed_at' => ['nullable', 'string', 'max:20'],
            'security.reboot_required'         => ['nullable', 'boolean'],
            'event_log_entries'                       => ['nullable', 'array'],
            'event_log_entries.*.channel'              => ['nullable', 'string', 'max:50'],
            'event_log_entries.*.event_id'             => ['nullable', 'string', 'max:20'],
            'event_log_entries.*.level'                => ['nullable', 'string', 'max:20'],
            'event_log_entries.*.source'               => ['nullable', 'string', 'max:255'],
            'event_log_entries.*.message'              => ['nullable', 'string'],
            'event_log_entries.*.logged_at'             => ['nullable', 'string', 'max:40'],
        ]);

        $device = $request->user();
        $hardware = $validated['hardware'] ?? [];

        $this->recordHardwareInventory($device, $hardware);

        IctEquipmentSoftwareInventory::updateOrCreate(
            ['device_id' => $device->id],
            ['installed_software' => $validated['software']['installed'] ?? [], 'recorded_at' => now()]
        );

        if (isset($validated['security'])) {
            IctEquipmentSecurityStatus::updateOrCreate(
                ['device_id' => $device->id],
                [
                    'antivirus_enabled'         => $validated['security']['antivirus_enabled'] ?? null,
                    'antivirus_up_to_date'      => $validated['security']['antivirus_up_to_date'] ?? null,
                    'firewall_enabled'          => $validated['security']['firewall_enabled'] ?? null,
                    'pending_updates_count'     => $validated['security']['pending_updates_count'] ?? null,
                    'last_update_installed_at'  => $validated['security']['last_update_installed_at'] ?? null,
                    'reboot_required'           => $validated['security']['reboot_required'] ?? false,
                    'recorded_at'               => now(),
                ]
            );

            $this->securityEvaluator->evaluate($device, $validated['software']['installed'] ?? [], $validated['security']);
        }

        $this->diagnosticsService->diagnoseInventoryLoop(
            $device,
            $hardware,
            $validated['security'] ?? [],
            $validated['event_log_entries'] ?? []
        );

        $device->update(['last_full_inventory_at' => now(), 'last_diagnostics_at' => now()]);

        return response()->json(['status' => 'ok']);
    }

    /**
     * Diffs the incoming hardware snapshot against whatever was recorded
     * last time, logging only the fields that actually changed (a swapped
     * stick of RAM, a replaced disk) before overwriting the latest-only row.
     */
    private function recordHardwareInventory(IctEquipmentDevice $device, array $hardware): void
    {
        $previous = IctEquipmentHardwareInventory::where('device_id', $device->id)->first();

        $fields = ['cpu_model', 'cpu_cores', 'ram_modules', 'disks', 'gpu', 'peripherals', 'battery'];
        if ($previous) {
            foreach ($fields as $field) {
                $oldValue = $previous->{$field};
                $newValue = $hardware[$field] ?? null;

                if (json_encode($oldValue) !== json_encode($newValue)) {
                    IctEquipmentHardwareInventoryChange::create([
                        'device_id'   => $device->id,
                        'field'       => $field,
                        'old_value'   => $oldValue !== null ? json_encode($oldValue) : null,
                        'new_value'   => $newValue !== null ? json_encode($newValue) : null,
                        'detected_at' => now(),
                    ]);
                }
            }
        }

        IctEquipmentHardwareInventory::updateOrCreate(
            ['device_id' => $device->id],
            [
                'cpu_model'   => $hardware['cpu_model'] ?? null,
                'cpu_cores'   => $hardware['cpu_cores'] ?? null,
                'ram_modules' => $hardware['ram_modules'] ?? [],
                'disks'       => $hardware['disks'] ?? [],
                'gpu'         => $hardware['gpu'] ?? null,
                'peripherals' => $hardware['peripherals'] ?? [],
                'battery'     => $hardware['battery'] ?? null,
                'recorded_at' => now(),
            ]
        );
    }

    /**
     * GET /api/ict-agent/releases/{encodedKey}
     *
     * Streams the private S3-stored agent release zip to an enrolled device.
     * Same s3.<base64url> key-encoding pattern as the WFH photo proxy —
     * never expose a raw/public S3 URL for these binaries.
     */
    public function releaseDownload(Request $request, string $encodedKey)
    {
        if (! preg_match('/^[a-zA-Z0-9_.=-]+$/', $encodedKey)) {
            abort(400);
        }

        $s3Key = $this->decodeS3Key($encodedKey);
        // Device tokens may only fetch release artifacts — the encoded key is
        // client-supplied, so without the prefix check it could name any
        // object in the bucket (WFH photos, backups, ...).
        if (! $s3Key || ! str_starts_with($s3Key, 'atlas-sentinel-releases/') || ! Storage::disk('s3')->exists($s3Key)) {
            abort(404);
        }

        // Redirect to a presigned S3 URL so the ~140MB transfer bypasses
        // Cloudflare/ALB/nginx/FPM entirely — fleet-wide updates hold app
        // connections open 16-65s per device and trip the ALB p99 latency
        // alarm. Agents follow the redirect with a default HttpClient (the
        // bearer header is dropped cross-host; the presigned URL needs none)
        // and verify sha256 locally. 30 min matches the agent's own
        // download timeout.
        try {
            return redirect()->away(
                Storage::disk('s3')->temporaryUrl($s3Key, now()->addMinutes(30))
            );
        } catch (\Throwable $e) {
            logger()->warning('Presigned release URL failed, falling back to streaming', ['error' => $e->getMessage()]);
        }

        // Release zips are ~100MB — stream from S3 instead of buffering the
        // whole object in PHP memory, or a fleet-wide update exhausts FPM.
        return response()->stream(function () use ($s3Key) {
            $stream = Storage::disk('s3')->readStream($s3Key);
            fpassthru($stream);
            if (is_resource($stream)) {
                fclose($stream);
            }
        }, 200, [
            'Content-Type'        => 'application/octet-stream',
            'Content-Length'      => (string) Storage::disk('s3')->size($s3Key),
            'Content-Disposition' => 'attachment; filename="' . basename($s3Key) . '"',
        ]);
    }

    private function encodeS3Key(string $s3Key): string
    {
        return 's3.' . rtrim(strtr(base64_encode($s3Key), '+/', '-_'), '=');
    }

    private function decodeS3Key(string $encodedKey): ?string
    {
        if (! str_starts_with($encodedKey, 's3.')) {
            return null;
        }
        $padded = strtr(substr($encodedKey, 3), '-_', '+/');
        $pad = strlen($padded) % 4;
        if ($pad) $padded .= str_repeat('=', 4 - $pad);
        $decoded = base64_decode($padded, true);
        return $decoded !== false ? $decoded : null;
    }

    /**
     * GET /api/ict-agent/alerts
     *
     * Open alerts for the authenticated device — polled by the tray app to
     * decide what to surface to the user.
     */
    public function alerts(Request $request): JsonResponse
    {
        $device = $request->user();

        $alerts = IctEquipmentAlert::where('device_id', $device->id)
            ->where('status', 'open')
            ->orderBy('created_at', 'desc')
            ->get(['id', 'code', 'issue', 'severity', 'created_at']);

        return response()->json(['alerts' => $alerts]);
    }

    /**
     * POST /api/ict-agent/alerts/{alert}/escalate
     *
     * One-click "file an IT Job Request" from the tray app. Submitted as
     * the equipment's assigned owner so it goes through the normal
     * Division Chief → OCD approval chain like any other request — if no
     * owner is assigned yet, this fails with a clear message rather than
     * fabricating a submitter.
     */
    public function escalate(Request $request, IctEquipmentAlert $alert): JsonResponse
    {
        $device = $request->user();

        if ($alert->device_id !== $device->id) {
            abort(403);
        }

        if ($alert->status !== 'open') {
            return response()->json(['message' => 'This alert is no longer open.'], 422);
        }

        $equipment = ICTEquipment::find($alert->equipment_id);
        $owner = $equipment?->owner_id ? User::find($equipment->owner_id) : null;

        if (! $owner) {
            return response()->json([
                'message' => 'This equipment has no assigned owner yet. Ask MIS to assign one in the ICT Equipments page before filing a ticket.',
            ], 422);
        }

        try {
            $jobRequest = $this->jobRequests->createJobRequest([
                'category'    => 'Hardware',
                'title'       => 'Auto-detected issue: ' . ($equipment->description ?? 'ICT equipment'),
                'description' => $alert->issue . " (auto-detected by Atlas Sentinel on {$device->hostname})",
                'priority'    => $alert->severity === 'critical' ? 'high' : 'normal',
                'ict_equipment_id' => $equipment->id,
            ], $owner);
        } catch (\RuntimeException $e) {
            return response()->json(['message' => $e->getMessage()], 422);
        }

        $alert->update(['status' => 'escalated', 'it_job_request_id' => $jobRequest->id]);

        return response()->json([
            'itjr_no' => $jobRequest->itjr_no,
            'job_request_id' => $jobRequest->id,
        ]);
    }

    /**
     * GET /api/ict-agent/device-summary
     *
     * Everything the tray dashboard shows beyond live local metrics:
     * equipment identity, health score, resolved-alert history, last backup
     * run, recent auto-remediations, and the ITJR category list for the
     * "Report a problem" form. Read-only and scoped to the authenticated
     * device — same isolation as alerts().
     */
    public function deviceSummary(Request $request): JsonResponse
    {
        $device = $request->user();
        $equipment = ICTEquipment::find($device->equipment_id);
        $owner = $equipment?->owner_id ? User::find($equipment->owner_id) : null;

        $alertHistory = IctEquipmentAlert::where('device_id', $device->id)
            ->where('status', '<>', 'open')
            ->orderByDesc('created_at')
            ->limit(10)
            ->get(['issue', 'severity', 'status', 'created_at']);

        $lastBackup = IctBackupRun::where('device_id', $device->id)
            ->orderByDesc('id')
            ->first(['status', 'finished_at', 'files_uploaded', 'bytes_uploaded']);

        $recentRemediations = IctEquipmentRemediationLog::where('device_id', $device->id)
            ->orderByDesc('executed_at')
            ->limit(5)
            ->get(['action', 'target', 'result', 'executed_at']);

        return response()->json([
            'device' => [
                'hostname'         => $device->hostname,
                'agent_version'    => $device->agent_version,
                'last_checkin_at'  => $device->last_checkin_at,
                'health_score'     => $device->health_score,
                'risk_tier'        => $device->risk_tier,
                'network_location' => $device->network_location,
            ],
            'equipment' => $equipment ? [
                'property_no' => $equipment->property_no,
                'description' => $equipment->description,
                'category'    => $equipment->category,
                'owner_name'  => $owner?->name,
            ] : null,
            'alert_history'       => $alertHistory,
            'last_backup'         => $lastBackup,
            'recent_remediations' => $recentRemediations,
            'report_categories'   => ITJobCategory::orderBy('name')->pluck('name'),
            'remote_help_enabled' => $this->remoteHelpService->enabled(),
            'remote_help_download_url' => config('atlas_sentinel.remote_help.anydesk.download_url'),
        ]);
    }

    /**
     * POST /api/ict-agent/report-problem
     *
     * User-initiated "Report a problem" from the tray dashboard. Mirrors
     * escalate(): filed as the equipment's assigned owner so it rides the
     * normal Division Chief → OCD approval chain, and refuses rather than
     * fabricating a submitter when no owner is assigned.
     */
    public function reportProblem(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'category'    => ['required', 'string', 'max:100', Rule::exists(ITJobCategory::class, 'name')],
            'description' => ['required', 'string', 'min:10', 'max:2000'],
        ]);

        $device = $request->user();
        $equipment = ICTEquipment::find($device->equipment_id);
        $owner = $equipment?->owner_id ? User::find($equipment->owner_id) : null;

        if (! $owner) {
            return response()->json([
                'message' => 'This equipment has no assigned owner yet. Ask MIS to assign one in the ICT Equipments page before filing a ticket.',
            ], 422);
        }

        try {
            $jobRequest = $this->jobRequests->createJobRequest([
                'category'    => $validated['category'],
                'title'       => 'User-reported issue: ' . ($equipment->description ?? 'ICT equipment'),
                'description' => $validated['description'] . " (reported via Atlas Sentinel on {$device->hostname})",
                'priority'    => 'normal',
                'ict_equipment_id' => $equipment->id,
            ], $owner);
        } catch (\RuntimeException $e) {
            return response()->json(['message' => $e->getMessage()], 422);
        }

        return response()->json([
            'itjr_no' => $jobRequest->itjr_no,
            'job_request_id' => $jobRequest->id,
        ]);
    }

    /**
     * POST /api/ict-agent/backup/{run}/manifest
     *
     * Batched scan manifest from the agent. Returns which of these files
     * still need uploading (new, or content hash changed since last backup).
     */
    public function backupManifest(Request $request, IctBackupRun $run): JsonResponse
    {
        $this->assertOwnedActiveRun($request, $run);

        $validated = $request->validate([
            // 'present' not 'required': an empty manifest (device with zero
            // documents) is legitimate and still needs to start the run.
            'files'                   => ['present', 'array', 'max:500'],
            'files.*.relative_path'   => ['required', 'string', 'max:2000'],
            'files.*.size_bytes'      => ['required', 'integer', 'min:0'],
            'files.*.sha256'          => ['required', 'string', 'regex:/^[0-9a-fA-F]{64}$/'],
            'files.*.mtime'           => ['nullable', 'string', 'max:40'],
        ]);

        return response()->json([
            'needed' => $this->backupService->recordManifest($run, $validated['files']),
        ]);
    }

    /**
     * POST /api/ict-agent/backup/{run}/upload-session
     *
     * Issues a Google Drive resumable-session URI for one file. The agent
     * PUTs the bytes directly to googleapis.com — they never pass through
     * this server, and Drive credentials never reach the device.
     */
    public function backupUploadSession(Request $request, IctBackupRun $run): JsonResponse
    {
        $this->assertOwnedActiveRun($request, $run);

        $validated = $request->validate([
            'relative_path' => ['required', 'string', 'max:2000'],
            'size_bytes'    => ['required', 'integer', 'min:0', 'max:2147483648'],
            'sha256'        => ['required', 'string', 'regex:/^[0-9a-fA-F]{64}$/'],
            'mime_type'     => ['nullable', 'string', 'max:150'],
        ]);

        $sessionUrl = $this->backupService->createUploadSession($run, [
            'relative_path' => $validated['relative_path'],
            'size_bytes'    => $validated['size_bytes'],
            'mime_type'     => $validated['mime_type'] ?? null,
        ]);

        return response()->json(['session_url' => $sessionUrl]);
    }

    /**
     * POST /api/ict-agent/backup/{run}/file-complete
     *
     * The agent finished one direct-to-Drive upload; record the file's new
     * state so future manifest diffs skip it.
     */
    public function backupFileComplete(Request $request, IctBackupRun $run): JsonResponse
    {
        $this->assertOwnedActiveRun($request, $run);

        $validated = $request->validate([
            'relative_path' => ['required', 'string', 'max:2000'],
            'size_bytes'    => ['required', 'integer', 'min:0'],
            'sha256'        => ['required', 'string', 'regex:/^[0-9a-fA-F]{64}$/'],
            'mtime'         => ['nullable', 'string', 'max:40'],
            'drive_file_id' => ['required', 'string', 'max:200'],
        ]);

        $this->backupService->recordFileUploaded($run, $validated);

        return response()->json(['status' => 'ok']);
    }

    /**
     * POST /api/ict-agent/backup/{run}/complete
     *
     * Final stats for the run — closes it out with whatever outcome the
     * agent reports.
     */
    public function backupComplete(Request $request, IctBackupRun $run): JsonResponse
    {
        $this->assertOwnedActiveRun($request, $run);

        $validated = $request->validate([
            'status'        => ['required', 'string', 'in:completed,completed_with_errors,failed'],
            'files_scanned' => ['nullable', 'integer', 'min:0'],
            'files_skipped' => ['nullable', 'integer', 'min:0'],
            'errors'        => ['nullable', 'array', 'max:100'],
            'errors.*'      => ['nullable', 'string', 'max:1000'],
        ]);

        $this->backupService->completeRun($run, $validated);

        return response()->json(['status' => 'ok']);
    }

    /**
     * Backup runs are device-scoped exactly like alerts: a device token can
     * only ever touch its own runs, and only while the run is still active.
     */
    private function assertOwnedActiveRun(Request $request, IctBackupRun $run): void
    {
        if ($run->device_id !== $request->user()->id) {
            abort(403);
        }

        if (! in_array($run->status, ['dispatched', 'running'], true)) {
            abort(422, 'This backup run is no longer active.');
        }
    }
}
