<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Controllers\ITJobRequestController;
use App\Models\ICTEquipment;
use App\Models\IctEquipmentAlert;
use App\Models\IctEquipmentDevice;
use App\Models\IctEquipmentEnrollmentToken;
use App\Models\IctEquipmentHealthSnapshot;
use App\Models\User;
use App\Services\IctAgentHealthEvaluator;
use App\Services\IctAgentNetworkLocationResolver;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class IctAgentController extends Controller
{
    public function __construct(
        private IctAgentHealthEvaluator $healthEvaluator,
        private ITJobRequestController $jobRequests,
        private IctAgentNetworkLocationResolver $networkLocationResolver,
    ) {
    }

    /**
     * POST /api/ict-agent/enroll
     *
     * Exchanges a one-time enrollment token (generated by MIS in the ICT
     * Equipments page) for a long-lived device token. Matches the reported
     * serial number against an existing ict_equipments row; if none exists,
     * creates a draft row for MIS to complete later instead of blocking
     * enrollment.
     */
    public function enroll(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'enrollment_token' => ['required', 'string'],
            'serial_no'        => ['required', 'string', 'max:255'],
            'hostname'         => ['nullable', 'string', 'max:255'],
            'mac_address'      => ['nullable', 'string', 'max:20'],
            'os_version'       => ['nullable', 'string', 'max:255'],
            'agent_version'    => ['nullable', 'string', 'max:20'],
            'model'            => ['nullable', 'string', 'max:255'],
        ]);

        $enrollmentToken = IctEquipmentEnrollmentToken::where('token', $validated['enrollment_token'])
            ->whereNull('used_at')
            ->where('expires_at', '>', now())
            ->first();

        if (! $enrollmentToken) {
            return response()->json([
                'message' => 'This enrollment token is invalid, expired, or already used.',
            ], 422);
        }

        $equipment = ICTEquipment::where('serial_no', $validated['serial_no'])->first();
        $linked = (bool) $equipment;

        if (! $equipment) {
            $equipment = ICTEquipment::create([
                'category'    => 'Other',
                'serial_no'   => $validated['serial_no'],
                'description' => $validated['model'] ?? ('Auto-detected device — ' . ($validated['hostname'] ?? 'unknown host')),
                'status'      => null,
            ]);
        }

        $device = IctEquipmentDevice::create([
            'equipment_id'     => $equipment->id,
            'hostname'         => $validated['hostname'] ?? null,
            'mac_address'      => $validated['mac_address'] ?? null,
            'os_version'       => $validated['os_version'] ?? null,
            'agent_version'    => $validated['agent_version'] ?? null,
            'last_checkin_at'  => now(),
        ]);

        $deviceToken = $device->createToken('ict-agent', ['ict-agent'])->plainTextToken;

        $enrollmentToken->update(['used_at' => now()]);

        return response()->json([
            'device_token' => $deviceToken,
            'equipment_id' => $equipment->id,
            'linked'       => $linked,
        ], 201);
    }

    /**
     * GET /api/ict-agent/me
     *
     * Sanity-check endpoint for the agent to confirm its device token still
     * resolves correctly and to see which equipment record it's linked to.
     */
    public function me(Request $request): JsonResponse
    {
        $device = $request->user();

        return response()->json([
            'device_id'    => $device->id,
            'equipment_id' => $device->equipment_id,
            'hostname'     => $device->hostname,
            'last_checkin_at' => $device->last_checkin_at,
        ]);
    }

    /**
     * POST /api/ict-agent/checkin
     *
     * Periodic hardware/peripheral snapshot from an enrolled device. Stores
     * the latest snapshot (overwritten each check-in) and runs it through
     * IctAgentHealthEvaluator, which logs routine findings into the
     * equipment's existing PMS history and tracks actionable findings as
     * open alerts.
     */
    public function checkin(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'cpu'           => ['nullable', 'string', 'max:255'],
            'ram_total_mb'  => ['nullable', 'integer'],
            'ram_free_mb'   => ['nullable', 'integer'],
            'disks'         => ['nullable', 'array'],
            'disks.*.drive'    => ['nullable', 'string', 'max:10'],
            'disks.*.total_gb' => ['nullable', 'numeric'],
            'disks.*.free_gb'  => ['nullable', 'numeric'],
            'printers'      => ['nullable', 'array'],
            'printers.*.name'                  => ['nullable', 'string', 'max:255'],
            'printers.*.detected_error_state'  => ['nullable', 'string', 'max:50'],
            'printers.*.pending_jobs'          => ['nullable', 'integer'],
            'pnp_issues'    => ['nullable', 'array'],
            'pnp_issues.*.device_name' => ['nullable', 'string', 'max:255'],
            'pnp_issues.*.error_code'  => ['nullable', 'string', 'max:50'],
            'os_version'    => ['nullable', 'string', 'max:255'],
            'agent_version' => ['nullable', 'string', 'max:20'],
            'wifi_ssid'     => ['nullable', 'string', 'max:255'],
        ]);

        $device = $request->user();

        IctEquipmentHealthSnapshot::updateOrCreate(
            ['device_id' => $device->id],
            ['payload' => $validated, 'recorded_at' => now()]
        );

        $networkLocation = $this->networkLocationResolver->resolve($validated['wifi_ssid'] ?? null, $request->ip());

        $deviceUpdate = [
            'last_checkin_at' => now(),
            'os_version'      => $validated['os_version'] ?? $device->os_version,
            'agent_version'   => $validated['agent_version'] ?? $device->agent_version,
        ];

        if ($networkLocation !== $device->network_location) {
            $deviceUpdate['network_location'] = $networkLocation;
            $deviceUpdate['network_location_changed_at'] = now();
        }

        $device->update($deviceUpdate);

        $this->healthEvaluator->evaluate($device, $validated);

        return response()->json(['status' => 'ok']);
    }

    /**
     * GET /api/ict-agent/alerts
     *
     * Open alerts for the authenticated device — polled by the tray app to
     * decide what to surface to the user.
     */
    public function alerts(Request $request): JsonResponse
    {
        $device = $request->user();

        $alerts = IctEquipmentAlert::where('device_id', $device->id)
            ->where('status', 'open')
            ->orderBy('created_at', 'desc')
            ->get(['id', 'code', 'issue', 'severity', 'created_at']);

        return response()->json(['alerts' => $alerts]);
    }

    /**
     * POST /api/ict-agent/alerts/{alert}/escalate
     *
     * One-click "file an IT Job Request" from the tray app. Submitted as
     * the equipment's assigned owner so it goes through the normal
     * Division Chief → OCD approval chain like any other request — if no
     * owner is assigned yet, this fails with a clear message rather than
     * fabricating a submitter.
     */
    public function escalate(Request $request, IctEquipmentAlert $alert): JsonResponse
    {
        $device = $request->user();

        if ($alert->device_id !== $device->id) {
            abort(403);
        }

        if ($alert->status !== 'open') {
            return response()->json(['message' => 'This alert is no longer open.'], 422);
        }

        $equipment = ICTEquipment::find($alert->equipment_id);
        $owner = $equipment?->owner_id ? User::find($equipment->owner_id) : null;

        if (! $owner) {
            return response()->json([
                'message' => 'This equipment has no assigned owner yet. Ask MIS to assign one in the ICT Equipments page before filing a ticket.',
            ], 422);
        }

        try {
            $jobRequest = $this->jobRequests->createJobRequest([
                'category'    => 'Hardware',
                'title'       => 'Auto-detected issue: ' . ($equipment->description ?? 'ICT equipment'),
                'description' => $alert->issue . " (auto-detected by the ICT Agent on {$device->hostname})",
                'priority'    => $alert->severity === 'critical' ? 'high' : 'normal',
                'ict_equipment_id' => $equipment->id,
            ], $owner);
        } catch (\RuntimeException $e) {
            return response()->json(['message' => $e->getMessage()], 422);
        }

        $alert->update(['status' => 'escalated', 'it_job_request_id' => $jobRequest->id]);

        return response()->json([
            'itjr_no' => $jobRequest->itjr_no,
            'job_request_id' => $jobRequest->id,
        ]);
    }
}
