<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\ICTEquipment;
use App\Models\IctEquipmentDevice;
use App\Models\IctEquipmentEnrollmentToken;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class IctAgentController extends Controller
{
    /**
     * POST /api/ict-agent/enroll
     *
     * Exchanges a one-time enrollment token (generated by MIS in the ICT
     * Equipments page) for a long-lived device token. Matches the reported
     * serial number against an existing ict_equipments row; if none exists,
     * creates a draft row for MIS to complete later instead of blocking
     * enrollment.
     */
    public function enroll(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'enrollment_token' => ['required', 'string'],
            'serial_no'        => ['required', 'string', 'max:255'],
            'hostname'         => ['nullable', 'string', 'max:255'],
            'mac_address'      => ['nullable', 'string', 'max:20'],
            'os_version'       => ['nullable', 'string', 'max:255'],
            'agent_version'    => ['nullable', 'string', 'max:20'],
            'model'            => ['nullable', 'string', 'max:255'],
        ]);

        $enrollmentToken = IctEquipmentEnrollmentToken::where('token', $validated['enrollment_token'])
            ->whereNull('used_at')
            ->where('expires_at', '>', now())
            ->first();

        if (! $enrollmentToken) {
            return response()->json([
                'message' => 'This enrollment token is invalid, expired, or already used.',
            ], 422);
        }

        $equipment = ICTEquipment::where('serial_no', $validated['serial_no'])->first();
        $linked = (bool) $equipment;

        if (! $equipment) {
            $equipment = ICTEquipment::create([
                'category'    => 'Other',
                'serial_no'   => $validated['serial_no'],
                'description' => $validated['model'] ?? ('Auto-detected device — ' . ($validated['hostname'] ?? 'unknown host')),
                'status'      => null,
            ]);
        }

        $device = IctEquipmentDevice::create([
            'equipment_id'     => $equipment->id,
            'hostname'         => $validated['hostname'] ?? null,
            'mac_address'      => $validated['mac_address'] ?? null,
            'os_version'       => $validated['os_version'] ?? null,
            'agent_version'    => $validated['agent_version'] ?? null,
            'last_checkin_at'  => now(),
        ]);

        $deviceToken = $device->createToken('ict-agent', ['ict-agent'])->plainTextToken;

        $enrollmentToken->update(['used_at' => now()]);

        return response()->json([
            'device_token' => $deviceToken,
            'equipment_id' => $equipment->id,
            'linked'       => $linked,
        ], 201);
    }

    /**
     * GET /api/ict-agent/me
     *
     * Sanity-check endpoint for the agent to confirm its device token still
     * resolves correctly and to see which equipment record it's linked to.
     */
    public function me(Request $request): JsonResponse
    {
        $device = $request->user();

        return response()->json([
            'device_id'    => $device->id,
            'equipment_id' => $device->equipment_id,
            'hostname'     => $device->hostname,
            'last_checkin_at' => $device->last_checkin_at,
        ]);
    }
}
