<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\ICTEquipment;
use App\Models\IctEquipmentDevice;
use App\Models\IctEquipmentEnrollmentToken;
use App\Models\IctEquipmentHealthSnapshot;
use App\Services\IctAgentHealthEvaluator;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class IctAgentController extends Controller
{
    public function __construct(private IctAgentHealthEvaluator $healthEvaluator)
    {
    }

    /**
     * POST /api/ict-agent/enroll
     *
     * Exchanges a one-time enrollment token (generated by MIS in the ICT
     * Equipments page) for a long-lived device token. Matches the reported
     * serial number against an existing ict_equipments row; if none exists,
     * creates a draft row for MIS to complete later instead of blocking
     * enrollment.
     */
    public function enroll(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'enrollment_token' => ['required', 'string'],
            'serial_no'        => ['required', 'string', 'max:255'],
            'hostname'         => ['nullable', 'string', 'max:255'],
            'mac_address'      => ['nullable', 'string', 'max:20'],
            'os_version'       => ['nullable', 'string', 'max:255'],
            'agent_version'    => ['nullable', 'string', 'max:20'],
            'model'            => ['nullable', 'string', 'max:255'],
        ]);

        $enrollmentToken = IctEquipmentEnrollmentToken::where('token', $validated['enrollment_token'])
            ->whereNull('used_at')
            ->where('expires_at', '>', now())
            ->first();

        if (! $enrollmentToken) {
            return response()->json([
                'message' => 'This enrollment token is invalid, expired, or already used.',
            ], 422);
        }

        $equipment = ICTEquipment::where('serial_no', $validated['serial_no'])->first();
        $linked = (bool) $equipment;

        if (! $equipment) {
            $equipment = ICTEquipment::create([
                'category'    => 'Other',
                'serial_no'   => $validated['serial_no'],
                'description' => $validated['model'] ?? ('Auto-detected device — ' . ($validated['hostname'] ?? 'unknown host')),
                'status'      => null,
            ]);
        }

        $device = IctEquipmentDevice::create([
            'equipment_id'     => $equipment->id,
            'hostname'         => $validated['hostname'] ?? null,
            'mac_address'      => $validated['mac_address'] ?? null,
            'os_version'       => $validated['os_version'] ?? null,
            'agent_version'    => $validated['agent_version'] ?? null,
            'last_checkin_at'  => now(),
        ]);

        $deviceToken = $device->createToken('ict-agent', ['ict-agent'])->plainTextToken;

        $enrollmentToken->update(['used_at' => now()]);

        return response()->json([
            'device_token' => $deviceToken,
            'equipment_id' => $equipment->id,
            'linked'       => $linked,
        ], 201);
    }

    /**
     * GET /api/ict-agent/me
     *
     * Sanity-check endpoint for the agent to confirm its device token still
     * resolves correctly and to see which equipment record it's linked to.
     */
    public function me(Request $request): JsonResponse
    {
        $device = $request->user();

        return response()->json([
            'device_id'    => $device->id,
            'equipment_id' => $device->equipment_id,
            'hostname'     => $device->hostname,
            'last_checkin_at' => $device->last_checkin_at,
        ]);
    }

    /**
     * POST /api/ict-agent/checkin
     *
     * Periodic hardware/peripheral snapshot from an enrolled device. Stores
     * the latest snapshot (overwritten each check-in) and runs it through
     * IctAgentHealthEvaluator, which logs routine findings into the
     * equipment's existing PMS history and tracks actionable findings as
     * open alerts.
     */
    public function checkin(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'cpu'           => ['nullable', 'string', 'max:255'],
            'ram_total_mb'  => ['nullable', 'integer'],
            'ram_free_mb'   => ['nullable', 'integer'],
            'disks'         => ['nullable', 'array'],
            'disks.*.drive'    => ['nullable', 'string', 'max:10'],
            'disks.*.total_gb' => ['nullable', 'numeric'],
            'disks.*.free_gb'  => ['nullable', 'numeric'],
            'printers'      => ['nullable', 'array'],
            'printers.*.name'                  => ['nullable', 'string', 'max:255'],
            'printers.*.detected_error_state'  => ['nullable', 'string', 'max:50'],
            'printers.*.pending_jobs'          => ['nullable', 'integer'],
            'pnp_issues'    => ['nullable', 'array'],
            'pnp_issues.*.device_name' => ['nullable', 'string', 'max:255'],
            'pnp_issues.*.error_code'  => ['nullable', 'string', 'max:50'],
            'os_version'    => ['nullable', 'string', 'max:255'],
            'agent_version' => ['nullable', 'string', 'max:20'],
        ]);

        $device = $request->user();

        IctEquipmentHealthSnapshot::updateOrCreate(
            ['device_id' => $device->id],
            ['payload' => $validated, 'recorded_at' => now()]
        );

        $device->update([
            'last_checkin_at' => now(),
            'os_version'      => $validated['os_version'] ?? $device->os_version,
            'agent_version'   => $validated['agent_version'] ?? $device->agent_version,
        ]);

        $this->healthEvaluator->evaluate($device, $validated);

        return response()->json(['status' => 'ok']);
    }
}
