<?php

namespace App\Http\Controllers\OPCR;

use App\Http\Controllers\Controller;
use App\Models\AgencyOutcome;
use App\Models\Division;
use App\Models\DostPillar;
use App\Models\OPCR\OpcrPeriod;
use App\Models\PerformanceIndicator;
use Illuminate\Http\Request;
use Inertia\Inertia;

class OpcrPeriodController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();
        $canManage = $user->isSuperAdmin() || $user->hasPermission('opcr.manage');

        $period = OpcrPeriod::current()->first();

        $indicatorsQuery = $period
            ? $period->indicators()->with([
                'subStrategy.strategy.pillar',
                'agencyOutcome',
                'performanceIndicator',
                'divisions',
                'actuals',
            ])->orderBy('id')
            : null;

        if ($indicatorsQuery && ! $canManage) {
            $indicatorsQuery->whereHas('divisions', function ($q) use ($user) {
                $q->where('divisions.id', $user->division_id);
            });
        }

        return Inertia::render('PerformanceManagement/Opcr', [
            'period' => $period,
            'periods' => OpcrPeriod::orderByDesc('fiscal_year')->get(['id', 'fiscal_year', 'period_label', 'is_current']),
            'indicators' => $indicatorsQuery ? $indicatorsQuery->get() : [],
            'pillars' => DostPillar::with('strategies.subStrategies')->get(),
            'agencyOutcomes' => AgencyOutcome::query()->topLevel()->excludingAutoGeneratedMarker()->with('children')->get(),
            'performanceIndicators' => PerformanceIndicator::all(['id', 'description']),
            'divisions' => Division::all(),
            'canManage' => $canManage,
        ]);
    }
}
