<?php

namespace App\Http\Controllers\OPCR;

use App\Http\Controllers\Controller;
use App\Models\AgencyOutcome;
use App\Models\Division;
use App\Models\DostPillar;
use App\Models\OPCR\OpcrIndicator;
use App\Models\OPCR\OpcrPeriod;
use App\Models\PerformanceIndicator;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;

class OpcrPeriodController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();
        $canManage = $user->isSuperAdmin() || $user->hasPermission('opcr.manage');

        $period = OpcrPeriod::current()->first();

        $indicatorsQuery = $period
            ? $period->indicators()->with([
                'subStrategy.strategy.pillar',
                'agencyOutcome',
                'performanceIndicator',
                'divisions',
                'actuals',
            ])->orderBy('id')
            : null;

        if ($indicatorsQuery && ! $canManage) {
            $indicatorsQuery->whereHas('divisions', function ($q) use ($user) {
                $q->where('divisions.id', $user->division_id);
            });
        }

        return Inertia::render('PerformanceManagement/Opcr', [
            'period' => $period,
            'periods' => OpcrPeriod::orderByDesc('fiscal_year')->get(['id', 'fiscal_year', 'period_label', 'is_current']),
            'indicators' => $indicatorsQuery ? $indicatorsQuery->get() : [],
            'pillars' => DostPillar::with('strategies.subStrategies')->get(),
            'agencyOutcomes' => AgencyOutcome::query()->topLevel()->excludingAutoGeneratedMarker()->with('children')->get(),
            'performanceIndicators' => PerformanceIndicator::all(['id', 'description']),
            'divisions' => Division::all(),
            'canManage' => $canManage,
        ]);
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'fiscal_year' => 'required|integer|min:2000|max:2100|unique:opcr_periods,fiscal_year',
            'period_label' => 'required|string|max:255',
        ]);

        OpcrPeriod::create($data);

        return back()->with('success', 'OPCR period created.');
    }

    public function update(Request $request, OpcrPeriod $opcrPeriod)
    {
        $data = $request->validate([
            'fiscal_year' => ['required', 'integer', 'min:2000', 'max:2100', Rule::unique('opcr_periods', 'fiscal_year')->ignore($opcrPeriod->id)],
            'period_label' => 'required|string|max:255',
            'is_current' => 'boolean',
            'campus_director_name' => 'nullable|string|max:255',
            'oic_campus_director_name' => 'nullable|string|max:255',
            'executive_director_name' => 'nullable|string|max:255',
            'commitment_statement' => 'nullable|string',
        ]);

        DB::transaction(function () use ($data, $opcrPeriod) {
            if (! empty($data['is_current'])) {
                OpcrPeriod::where('id', '!=', $opcrPeriod->id)->update(['is_current' => false]);
            }
            $opcrPeriod->update($data);
        });

        return back()->with('success', 'OPCR period updated.');
    }

    public function cloneFrom(Request $request, OpcrPeriod $opcrPeriod)
    {
        $data = $request->validate([
            'source_period_id' => 'required|exists:opcr_periods,id|different:opcr_period',
        ]);

        if ($opcrPeriod->indicators()->exists()) {
            throw ValidationException::withMessages([
                'source_period_id' => 'This period already has indicators. Cloning is only allowed into an empty period.',
            ]);
        }

        $source = OpcrPeriod::findOrFail($data['source_period_id']);

        DB::transaction(function () use ($source, $opcrPeriod) {
            $indicators = $source->indicators()->with('divisions')->get();
            foreach ($indicators as $indicator) {
                $clone = $indicator->replicate([
                    'rating_quality', 'rating_efficiency', 'rating_timeliness', 'rating_average',
                ]);
                $clone->opcr_period_id = $opcrPeriod->id;
                $clone->save();
                $clone->divisions()->sync($indicator->divisions->pluck('id'));
            }
        });

        return back()->with('success', "Cloned from \"{$source->period_label}\".");
    }
}
