<?php

namespace App\Http\Controllers\OPCR;

use App\Http\Controllers\Controller;
use App\Models\AgencyOutcome;
use App\Models\Division;
use App\Models\DostPillar;
use App\Models\IPCRRatingPeriod;
use App\Models\OPCR\OpcrIndicator;
use App\Models\OPCR\OpcrSetting;
use App\Models\PerformanceIndicator;
use App\Services\OPCR\OpcrPdfService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;

class OpcrController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();
        $canManage = $user->isSuperAdmin() || $user->hasPermission('opcr.manage');

        $currentYear = IPCRRatingPeriod::current()->value('year') ?? (int) now()->format('Y');
        $selectedFY = $request->query('fiscal_year', (string) $currentYear);

        $indicatorsQuery = OpcrIndicator::with([
            'subStrategy.strategy.pillar',
            'agencyOutcome',
            'performanceIndicator',
            'divisions',
            'actuals',
        ])
            ->when($selectedFY !== 'all', fn ($q) => $q->forFiscalYear((int) $selectedFY))
            ->orderBy('id');

        if (! $canManage) {
            $indicatorsQuery->whereHas('divisions', function ($q) use ($user) {
                $q->where('divisions.id', $user->division_id);
            });
        }

        return Inertia::render('PerformanceManagement/Opcr', [
            'indicators' => $indicatorsQuery->get(),
            'fiscalYears' => IPCRRatingPeriod::query()->distinct()->orderByDesc('year')->pluck('year'),
            'selectedFiscalYear' => $selectedFY,
            'currentFiscalYear' => $currentYear,
            'settings' => OpcrSetting::current(),
            'pillars' => DostPillar::with('strategies.subStrategies')->get(),
            'agencyOutcomes' => AgencyOutcome::query()->topLevel()->excludingAutoGeneratedMarker()->with('children')->get(),
            'performanceIndicators' => PerformanceIndicator::all(['id', 'description']),
            'divisions' => Division::all(),
            'canManage' => $canManage,
        ]);
    }

    public function updateSettings(Request $request)
    {
        $data = $request->validate([
            'campus_director_name' => 'nullable|string|max:255',
            'oic_campus_director_name' => 'nullable|string|max:255',
            'executive_director_name' => 'nullable|string|max:255',
            'commitment_statement' => 'nullable|string',
        ]);

        OpcrSetting::current()->update($data);

        return back()->with('success', 'Signatories updated.');
    }

    public function clone(Request $request)
    {
        $data = $request->validate([
            'source_fiscal_year' => 'required|integer|min:2000|max:2100|different:target_fiscal_year',
            'target_fiscal_year' => 'required|integer|min:2000|max:2100',
        ]);

        $source = (int) $data['source_fiscal_year'];
        $target = (int) $data['target_fiscal_year'];

        if (OpcrIndicator::forFiscalYear($target)->exists()) {
            throw ValidationException::withMessages([
                'source_fiscal_year' => "FY {$target} already has indicators. Cloning is only allowed into an empty fiscal year.",
            ]);
        }

        DB::transaction(function () use ($source, $target) {
            $indicators = OpcrIndicator::forFiscalYear($source)->with('divisions')->get();
            foreach ($indicators as $indicator) {
                $clone = $indicator->replicate([
                    'rating_quality', 'rating_efficiency', 'rating_timeliness', 'rating_average',
                ]);
                $clone->fiscal_year = $target;
                $clone->save();
                $clone->divisions()->sync($indicator->divisions->pluck('id'));
            }
        });

        return back()->with('success', "Cloned from FY {$source}.");
    }

    public function pdf(int $fiscalYear, OpcrPdfService $service)
    {
        return $service->stream($fiscalYear);
    }
}
