<?php

namespace App\Http\Controllers\OPCR;

use App\Http\Controllers\Controller;
use App\Models\AgencyOutcome;
use App\Models\Division;
use App\Models\IPCRRatingPeriod;
use App\Models\OPCR\OpcrIndicator;
use App\Models\OPCR\OpcrSetting;
use App\Services\OPCR\OpcrPdfService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;

class OpcrController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();
        $canManage = $user->isSuperAdmin() || $user->hasPermission('opcr.manage');

        if (! $request->has('fiscal_year')) {
            return $this->yearIndex($request, $canManage);
        }

        $currentYear = IPCRRatingPeriod::current()->value('year') ?? (int) now()->format('Y');
        $selectedFY = $request->query('fiscal_year');

        $indicatorsQuery = OpcrIndicator::with([
            'agencyOutcome',
            'performanceIndicator.agencyOutcome.dostStrategies.pillar',
            'performanceIndicator.agencyOutcome.dostStrategies.subStrategies',
            'performanceIndicator.agencyOutcome.parent.dostStrategies.pillar',
            'performanceIndicator.agencyOutcome.parent.dostStrategies.subStrategies',
            'divisions',
            'actuals',
        ])
            ->when($selectedFY !== 'all', fn ($q) => $q->forFiscalYear((int) $selectedFY))
            ->orderBy('id');

        if (! $canManage) {
            $indicatorsQuery->whereHas('divisions', function ($q) use ($user) {
                $q->where('divisions.id', $user->division_id);
            });
        }

        return Inertia::render('PerformanceManagement/Opcr', [
            'indicators' => $indicatorsQuery->get(),
            'fiscalYears' => IPCRRatingPeriod::query()->distinct()->orderByDesc('year')->pluck('year'),
            'selectedFiscalYear' => $selectedFY,
            'currentFiscalYear' => $currentYear,
            'settings' => OpcrSetting::current(),
            'agencyOutcomes' => AgencyOutcome::query()->topLevel()->excludingAutoGeneratedMarker()->with('children')->get(),
            'divisions' => Division::all(),
            'canManage' => $canManage,
        ]);
    }

    // Landing page for /opcr with no fiscal_year selected — lists every
    // fiscal year that has OPCR indicators (current year always included,
    // even with none yet) so campus OPCRs read as a browsable archive of
    // yearly documents rather than only reachable via a dropdown default.
    private function yearIndex(Request $request, bool $canManage)
    {
        $currentYear = IPCRRatingPeriod::current()->value('year') ?? (int) now()->format('Y');

        $countsQuery = OpcrIndicator::query();
        if (! $canManage) {
            $countsQuery->whereHas('divisions', fn ($q) => $q->where('divisions.id', $request->user()->division_id));
        }

        $counts = $countsQuery->selectRaw('fiscal_year, count(*) as indicator_count')
            ->groupBy('fiscal_year')
            ->pluck('indicator_count', 'fiscal_year');

        $years = $counts->keys()
            ->push($currentYear)
            ->unique()
            ->sortDesc()
            ->values()
            ->map(fn ($year) => [
                'year' => (int) $year,
                'indicator_count' => (int) ($counts[$year] ?? 0),
                'is_current' => (int) $year === $currentYear,
            ]);

        return Inertia::render('PerformanceManagement/OpcrIndex', [
            'years' => $years,
            'currentFiscalYear' => $currentYear,
            'canManage' => $canManage,
        ]);
    }

    public function updateSettings(Request $request)
    {
        $data = $request->validate([
            'campus_director_name' => 'nullable|string|max:255',
            'executive_director_name' => 'nullable|string|max:255',
            'commitment_statement' => 'nullable|string',
        ]);

        OpcrSetting::current()->update($data);

        return back()->with('success', 'Signatories updated.');
    }

    public function clone(Request $request)
    {
        $data = $request->validate([
            'source_fiscal_year' => 'required|integer|min:2000|max:2100|different:target_fiscal_year',
            'target_fiscal_year' => 'required|integer|min:2000|max:2100',
        ]);

        $source = (int) $data['source_fiscal_year'];
        $target = (int) $data['target_fiscal_year'];

        if (OpcrIndicator::forFiscalYear($target)->exists()) {
            throw ValidationException::withMessages([
                'source_fiscal_year' => "FY {$target} already has indicators. Cloning is only allowed into an empty fiscal year.",
            ]);
        }

        DB::transaction(function () use ($source, $target) {
            $indicators = OpcrIndicator::forFiscalYear($source)->with('divisions')->get();
            foreach ($indicators as $indicator) {
                $clone = $indicator->replicate([
                    'rating_quality', 'rating_efficiency', 'rating_timeliness', 'rating_average',
                    'performance_indicator_id',
                ]);
                $clone->fiscal_year = $target;
                $clone->save();
                $clone->divisions()->sync($indicator->divisions->pluck('id'));
            }
        });

        return back()->with('success', "Cloned from FY {$source}.");
    }

    public function pdf(int $fiscalYear, OpcrPdfService $service)
    {
        return $service->stream($fiscalYear);
    }
}
