<?php

return [

    // ── Maturity level definitions ────────────────────────────────────────────
    'maturity_labels' => [
        1 => ['label' => 'Initial',       'description' => 'Basic CRUD, minimal workflow. No approval chain.'],
        2 => ['label' => 'Managed',       'description' => 'Permissions, validation, basic workflow complete.'],
        3 => ['label' => 'Defined',       'description' => 'Approval chains, audit trail, notifications in place.'],
        4 => ['label' => 'Quantitative',  'description' => 'Reporting, analytics dashboards, KPI tracking.'],
        5 => ['label' => 'Optimizing',    'description' => 'AI/automation, deep cross-module integration.'],
    ],

    // ── Category definitions ─────────────────────────────────────────────────
    'category_labels' => [
        'hr_personnel'       => 'HR & Personnel',
        'academic'           => 'Academic',
        'student_services'   => 'Student Services',
        'finance_admin'      => 'Finance & Administration',
        'compliance_records' => 'Compliance & Records',
        'it_requests'        => 'IT & Requests',
        'communication_data' => 'Communication & Data',
    ],

    // ── External integrations ─────────────────────────────────────────────────
    // 'env_key' is checked for non-empty value to determine if configured.
    'integrations' => [
        's3'           => ['label' => 'AWS S3',           'env_key' => 'AWS_BUCKET',              'description' => 'File storage — PDFs, photos, attachments'],
        'smtp'         => ['label' => 'SMTP / Mail',      'env_key' => 'MAIL_HOST',               'description' => 'Transactional email — payslips, notifications'],
        'pusher'       => ['label' => 'Pusher / Soketi',  'env_key' => 'PUSHER_APP_KEY',          'description' => 'Real-time WebSocket broadcasting'],
        'google_drive' => ['label' => 'Google Drive',     'env_key' => 'GOOGLE_DRIVE_FOLDER_ID',  'description' => 'DB backup destination and DTS file sync'],
        'rekognition'  => ['label' => 'AWS Rekognition',  'env_key' => 'AWS_ACCESS_KEY_ID',       'description' => 'Facial recognition for Online Time Punch'],
        'firebase'     => ['label' => 'Firebase FCM',     'env_key' => 'FIREBASE_CREDENTIALS',    'description' => 'Push notifications for parent mobile app'],
        'sms'          => ['label' => 'SMS Gate',         'env_key' => 'SMS_GATE_URL',            'description' => 'SMS alerts for Student Gate Attendance'],
        'cloudwatch'   => ['label' => 'AWS CloudWatch',   'env_key' => 'AWS_DEFAULT_REGION',      'description' => 'Atlas Sentinel monitoring log sink'],
    ],

    // ── Maturity scoring dimensions ───────────────────────────────────────────
    // Each dimension has: label, color (hex), weight (sum=100), description, criteria[5]
    // Score per dimension = (checked criteria / 5) × 100, weighted average = overall %
    'maturity_dimensions' => [
        'functional' => [
            'label'       => 'Functional',
            'color'       => '#6366f1',
            'weight'      => 20,
            'description' => 'Feature completeness, business rules, workflow coverage',
            'criteria'    => [
                'Core CRUD operations fully implemented',
                'All business rules enforced by the system',
                'Complete workflow coverage (all stages tracked)',
                'Input validation on all user-facing forms',
                'Role-based feature visibility and access control',
            ],
        ],
        'technical' => [
            'label'       => 'Technical',
            'color'       => '#8b5cf6',
            'weight'      => 15,
            'description' => 'Code quality, performance optimization, API standards',
            'criteria'    => [
                'No N+1 queries (all relations eager-loaded)',
                'Database indexes on frequently queried columns',
                'Business logic separated into Service classes',
                'Error handling with user-friendly messages',
                'API endpoints follow consistent conventions',
            ],
        ],
        'security' => [
            'label'       => 'Security',
            'color'       => '#ef4444',
            'weight'      => 20,
            'description' => 'RBAC, audit trail, data protection, OWASP compliance',
            'criteria'    => [
                'Granular RBAC permissions configured and enforced',
                'All mutations logged in audit trail',
                'Input sanitization against XSS and injection',
                'Sensitive data encrypted at rest (S3 + RDS KMS)',
                'Rate limiting applied to sensitive endpoints',
            ],
        ],
        'ai_readiness' => [
            'label'       => 'AI Readiness',
            'color'       => '#06b6d4',
            'weight'      => 10,
            'description' => 'Structured data, analytics, automation readiness',
            'criteria'    => [
                'Structured, queryable and normalized data model',
                'Reporting/analytics endpoints or dashboards available',
                'Data export capability (CSV, Excel, or PDF)',
                'Event-driven or webhook integration support',
                'KPIs defined and measurable from the data',
            ],
        ],
        'data_quality' => [
            'label'       => 'Data Quality',
            'color'       => '#10b981',
            'weight'      => 10,
            'description' => 'Validation, consistency, completeness, master data',
            'criteria'    => [
                'Required field validation at both app and DB layer',
                'Data type constraints and format validation enforced',
                'Referential integrity maintained (foreign keys)',
                'Duplicate detection or prevention in place',
                'Consistent naming and format across records',
            ],
        ],
        'ux' => [
            'label'       => 'User Experience',
            'color'       => '#f59e0b',
            'weight'      => 10,
            'description' => 'Mobile responsiveness, accessibility, UX consistency',
            'criteria'    => [
                'Fully responsive layout (mobile and tablet)',
                'Loading states and skeleton screens implemented',
                'Error messages are clear and actionable',
                'Consistent Tailwind/Atlas design patterns applied',
                'Accessible color contrast and keyboard-friendly',
            ],
        ],
        'governance' => [
            'label'       => 'Governance',
            'color'       => '#64748b',
            'weight'      => 15,
            'description' => 'Ownership, documentation, versioning, change management',
            'criteria'    => [
                'Module owner assigned in Atlas Module Monitor',
                'User-facing documentation or help text available',
                'Change history tracked (audit logs or git history)',
                'KPIs and success metrics defined',
                'Version number maintained in module settings',
            ],
        ],
    ],

    // ── Module registry ───────────────────────────────────────────────────────
    // Fields:
    //   key            – unique slug (kebab-case)
    //   name           – display name
    //   category       – one of category_labels keys
    //   description    – one-line description shown in detail modal
    //   route_name     – named route for "Open Module" link (null = no direct link)
    //   primary_table  – main DB table (null = read-only/computed, shows 'info' status)
    //   activity_col   – column checked for recent activity (default: created_at)
    //   maturity       – 1–5 per maturity_labels above
    //   queue_names    – job queue names tagged to this module (for failed_jobs check)
    //   dependencies   – other module keys this module depends on
    //   integrations   – integration keys from the integrations section above
    //   notes          – optional admin note shown in detail modal
    'modules' => [

        // ── HR & Personnel ────────────────────────────────────────────────────
        [
            'key'           => 'employees',
            'name'          => 'Employee Management',
            'category'      => 'hr_personnel',
            'description'   => 'Core employee directory — personal info, salary grade, office/division assignment, and role management.',
            'route_name'    => 'users.index',
            'primary_table' => 'users',
            'activity_col'  => 'created_at',
            'maturity'      => 4,
            'queue_names'   => [],
            'dependencies'  => [],
            'integrations'  => [],
            'notes'         => '',
        ],
        [
            'key'              => 'leave',
            'name'             => 'Leave Applications',
            'category'         => 'hr_personnel',
            'description'      => 'Employee leave filing via CSC Form 6, 3-stage approval chain (supervisor → division chief → HR), and automatic DTR credit deduction.',
            'route_name'       => 'hr.leave.index',
            'primary_table'    => 'leave_applications',
            'activity_col'     => 'created_at',
            'user_col'         => 'user_id',
            'maturity'         => 4,
            'queue_names'      => [],
            'dependencies'     => ['employees', 'dtr'],
            'integrations'     => [],
            'pending_approvals' => [
                ['table' => 'leave_applications', 'status_col' => 'status', 'pending_values' => ['pending', 'forwarded'], 'label' => 'Pending Leave', 'route_name' => 'hr.leave.index'],
            ],
            'notes'            => '',
        ],
        [
            'key'           => 'dtr',
            'name'          => 'DTR / Attendance',
            'category'      => 'hr_personnel',
            'description'   => 'Daily Time Records synced from biometric logs, with manual correction, travel flagging, and gate-pass deductions.',
            'route_name'    => 'hr.dtr.index',
            'primary_table' => 'dtr_records',
            'activity_col'  => 'created_at',
            'user_col'      => 'user_id',
            'sync_check'    => ['column' => 'source', 'value' => 'biometric', 'label' => 'Biometric', 'max_gap_hours' => 4],
            'maturity'      => 4,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => [],
            'notes'         => '',
        ],
        [
            'key'           => 'wfh',
            'name'          => 'WFH Attendance',
            'category'      => 'hr_personnel',
            'description'   => 'Work-from-home time logging with webcam photo verification (base64 → S3), accomplishment uploads, and supervisor review.',
            'route_name'    => 'hr.wfh.index',
            'primary_table' => 'wfh_attendances',
            'activity_col'  => 'created_at',
            'user_col'      => 'user_id',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => ['s3'],
            'notes'         => '',
        ],
        [
            'key'              => 'gatepass',
            'name'             => 'Gate Pass',
            'category'         => 'hr_personnel',
            'description'      => '3-stage gate pass issuance (Division Chief → HR → OCD), digital PIN signing, and automatic DTR deduction on approval.',
            'route_name'       => 'gatepass.index',
            'primary_table'    => 'gatepass',
            'activity_col'     => 'created_at',
            'maturity'         => 3,
            'queue_names'      => [],
            'dependencies'     => ['employees'],
            'integrations'     => [],
            'pending_approvals' => [
                ['table' => 'gatepass', 'status_col' => 'status', 'pending_values' => ['Pending'], 'label' => 'Pending Gate Passes', 'route_name' => 'gatepass.index'],
            ],
            'notes'            => '',
        ],
        [
            'key'           => 'online_punch',
            'name'          => 'Online Time Punch',
            'category'      => 'hr_personnel',
            'description'   => 'Facial recognition time punching via webcam — self-enroll face, HR approval gate, AWS Rekognition CompareFaces for punch verification.',
            'route_name'    => 'hr.online-punch.index',
            'primary_table' => 'online_time_punches',
            'activity_col'  => 'created_at',
            'user_col'      => 'user_id',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => ['rekognition', 's3'],
            'notes'         => 'AWS Face Liveness blocked by org SCP; uses CompareFaces baseline instead.',
        ],

        // ── Academic ──────────────────────────────────────────────────────────
        [
            'key'           => 'faculty_loading',
            'name'          => 'Faculty Loading',
            'category'      => 'academic',
            'description'   => 'SY-scoped faculty schedule generation with AI-assisted conflict-free assignment, designations, research advisory, and overload computation.',
            'route_name'    => 'faculty-loading.index',
            'primary_table' => 'class_schedules',
            'activity_col'  => 'created_at',
            'user_col'      => 'user_id',
            'maturity'      => 4,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => [],
            'notes'         => '',
        ],
        [
            'key'           => 'class_scheduling',
            'name'          => 'Class Scheduling',
            'category'      => 'academic',
            'description'   => 'Manual and AI-generated class timetables with drag-and-drop calendar, conflict detection, unplaced subject tray, and by-year-level elective overview.',
            'route_name'    => 'faculty-loading.scheduling',
            'primary_table' => 'class_schedules',
            'activity_col'  => 'updated_at',
            'user_col'      => 'user_id',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['faculty_loading', 'sis'],
            'integrations'  => [],
            'notes'         => 'Shares class_schedules table with faculty_loading.',
        ],
        [
            'key'           => 'class_records',
            'name'          => 'Class Records',
            'category'      => 'academic',
            'description'   => 'Teacher grade books — quarterly assessments, CSV roster import, running grade computation, at-risk highlights, A3 PDF export, and school-year locking.',
            'route_name'    => 'class-records.index',
            'primary_table' => 'class_records',
            'activity_col'  => 'created_at',
            'maturity'      => 4,
            'queue_names'   => [],
            'dependencies'  => ['faculty_loading', 'sis'],
            'integrations'  => ['s3'],
            'notes'         => '',
        ],
        [
            'key'           => 'sis',
            'name'          => 'SIS / Enrollment',
            'category'      => 'academic',
            'description'   => 'Student Information System — enrollment, section assignment by grade list, student status tracking, and section roster management.',
            'route_name'    => 'sis.enrollments.index',
            'primary_table' => 'student_enrollments',
            'activity_col'  => 'created_at',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => [],
            'integrations'  => [],
            'notes'         => '',
        ],

        // ── Student Services ──────────────────────────────────────────────────
        [
            'key'           => 'student_portal',
            'name'          => 'Student Portal',
            'category'      => 'student_services',
            'description'   => 'Self-service portal for students — Firebase @crc.pshs.edu.ph auth, PISAY ID one-time link, 10 form sections including profile and RH application.',
            'route_name'    => null,
            'primary_table' => 'student_mobile_links',
            'activity_col'  => 'created_at',
            'maturity'      => 2,
            'queue_names'   => [],
            'dependencies'  => ['sis'],
            'integrations'  => ['firebase'],
            'notes'         => 'Student portal is a separate web route — no single named index route.',
        ],
        [
            'key'           => 'residence_hall',
            'name'          => 'Residence Hall',
            'category'      => 'student_services',
            'description'   => 'Dormer management — room and bed mapping, leave pass filing (staff and student-portal), housekeeping logs, fee tracking, and incident records.',
            'route_name'    => 'residence-hall.index',
            'primary_table' => 'rh_interns',
            'activity_col'  => 'created_at',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['sis'],
            'integrations'  => [],
            'notes'         => 'Code uses "intern"; UI uses "dormer" except on printed form labels.',
        ],
        [
            'key'              => 'discipline',
            'name'             => 'Student Discipline',
            'category'         => 'student_services',
            'description'      => 'SDO anecdotal report workflow with multi-stage approval, PIN digital signing, offense catalog, and confiscated item tracking.',
            'route_name'       => 'discipline.index',
            'primary_table'    => 'discipline_cases',
            'activity_col'     => 'created_at',
            'maturity'         => 3,
            'queue_names'      => [],
            'dependencies'     => ['sis', 'employees'],
            'integrations'     => [],
            'pending_approvals' => [
                ['table' => 'discipline_cases', 'status_col' => 'status', 'pending_values' => ['filed', 'received', 'under_review'], 'label' => 'Active Cases', 'route_name' => 'discipline.index'],
            ],
            'notes'            => '',
        ],
        [
            'key'           => 'student_gate',
            'name'          => 'Student Gate Attendance',
            'category'      => 'student_services',
            'description'   => 'Barcode/PISAY ID gate tap logging with SMS notification via SMS Gate integration and real-time attendance dashboard.',
            'route_name'    => 'student-attendance.index',
            'primary_table' => 'student_attendance_logs',
            'activity_col'  => 'created_at',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['sis'],
            'integrations'  => ['sms'],
            'notes'         => '',
        ],
        [
            'key'           => 'egcu',
            'name'          => 'EGCU Student Records',
            'category'      => 'student_services',
            'description'   => 'Comprehensive cumulative student record system — 20 tables covering academic standing, club memberships, awards, and guidance data.',
            'route_name'    => 'egcu.index',
            'primary_table' => 'egcu_academic_standing',
            'activity_col'  => null,  // table has no timestamp columns; health is row-count based
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['sis'],
            'integrations'  => [],
            'notes'         => 'egcu_academic_standing uses gradelevel column, not levelid.',
        ],

        // ── Finance & Administration ──────────────────────────────────────────
        [
            'key'              => 'payroll',
            'name'             => 'Payroll',
            'category'         => 'finance_admin',
            'description'      => 'Monthly payroll runs with deductions (loans, PhilHealth, GSIS), per-batch payslip PDFs, combined batch report, and email distribution.',
            'route_name'       => 'payroll.index',
            'primary_table'    => 'payroll_runs',
            'activity_col'     => 'created_at',
            'maturity'         => 4,
            'queue_names'      => [],
            'dependencies'     => ['employees', 'dtr', 'leave'],
            'integrations'     => ['smtp'],
            'pending_approvals' => [
                ['table' => 'payroll_runs', 'status_col' => 'status', 'pending_values' => ['draft'], 'label' => 'Draft Payroll Runs', 'route_name' => 'payroll.index'],
            ],
            'notes'            => '',
        ],
        [
            'key'           => 'ppmp',
            'name'          => 'PPMP',
            'category'      => 'finance_admin',
            'description'   => 'Project Procurement Management Plan — unit item requests, division rollup approval, Property Officer review, APP-CSE catalogue, and Budget Officer sign-off.',
            'route_name'    => 'ppmp.index',
            'primary_table' => 'ppmp_items',
            'activity_col'  => 'created_at',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => [],
            'notes'         => '',
        ],
        [
            'key'              => 'procurement',
            'name'             => 'Procurement',
            'category'         => 'finance_admin',
            'description'      => 'Full PR → ORS → DV procurement workflow with 4-role approval stages and per-stage column tracking.',
            'route_name'       => 'procurement.index',
            'primary_table'    => 'procurements',
            'activity_col'     => 'created_at',
            'maturity'         => 3,
            'queue_names'      => [],
            'dependencies'     => ['ppmp', 'employees'],
            'integrations'     => [],
            'pending_approvals' => [
                ['table' => 'procurements', 'pending_null_col' => 'date_approved_budget_officer', 'label' => 'Awaiting Budget Officer', 'route_name' => 'procurement.index'],
            ],
            'notes'            => '',
        ],
        [
            'key'           => 'supply',
            'name'          => 'Supply & Property',
            'category'      => 'finance_admin',
            'description'   => 'Supply ledger (IAR, RIS, Stock Card), property management (ICS, PAR, transfers, RPCI, RPCPPE), disposal, work orders, and CSV import.',
            'route_name'    => 'supply.index',
            'primary_table' => 'supply_items',
            'activity_col'  => 'created_at',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['procurement'],
            'integrations'  => [],
            'notes'         => '',
        ],
        [
            'key'              => 'vehicle_requests',
            'name'             => 'Vehicle Requests',
            'category'         => 'finance_admin',
            'description'      => 'Motor pool vehicle request workflow — Division Chief → FAD → OCD approval, performSign stages, and printable trip ticket with S3 signature image.',
            'route_name'       => 'vehicle-requests.index',
            'primary_table'    => 'vehicle_requests',
            'activity_col'     => 'created_at',
            'maturity'         => 3,
            'queue_names'      => [],
            'dependencies'     => ['employees'],
            'integrations'     => [],
            'pending_approvals' => [
                ['table' => 'vehicle_requests', 'status_col' => 'status', 'pending_values' => ['Pending'], 'label' => 'Pending Vehicle Requests', 'route_name' => 'vehicle-requests.index'],
            ],
            'notes'            => '',
        ],

        // ── Compliance & Records ──────────────────────────────────────────────
        [
            'key'           => 'ipcr',
            'name'          => 'IPCR / PMS',
            'category'      => 'compliance_records',
            'description'   => 'Individual Performance Commitment and Review — rating periods, weight distributions, agency outcomes, and performance indicator tracking for all employee levels.',
            'route_name'    => 'ipcr.index',
            'primary_table' => 'employee_ipcrs',
            'activity_col'  => 'created_at',
            'user_col'      => 'user_id',
            'maturity'      => 4,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => [],
            'notes'         => '',
        ],
        [
            'key'           => 'saln',
            'name'          => 'SALN',
            'category'      => 'compliance_records',
            'description'   => 'Statement of Assets, Liabilities, and Net Worth — filing workflow (draft → submitted → approved → filed) with CSC-compliant form generation.',
            'route_name'    => 'saln.index',
            'primary_table' => 'saln_records',
            'activity_col'  => 'created_at',
            'user_col'      => 'user_id',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => [],
            'notes'         => '',
        ],
        [
            'key'           => 'pds',
            'name'          => 'Personal Data Sheet',
            'category'      => 'compliance_records',
            'description'   => 'CSC Form 212 — digital PDS with Work Experience Sheet (WES) tab, photo and signature embedding, and Excel export with exact cell coordinates.',
            'route_name'    => 'pds.edit',
            'primary_table' => 'users',
            'activity_col'  => 'updated_at',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => [],
            'notes'         => 'Uses users table; activity_col is updated_at to reflect PDS edits.',
        ],
        [
            'key'              => 'document_tracking',
            'name'             => 'Document Tracking',
            'category'         => 'compliance_records',
            'description'      => 'Internal and external document routing with sequential/parallel/manual routing templates, Google Drive attachments, and role-based access control.',
            'route_name'       => 'document-tracking.index',
            'primary_table'    => 'documents',
            'activity_col'     => 'created_at',
            'user_col'         => 'created_by',
            'maturity'         => 3,
            'queue_names'      => [],
            'dependencies'     => ['employees'],
            'integrations'     => ['s3', 'google_drive'],
            'pending_approvals' => [
                ['table' => 'documents', 'status_col' => 'overall_status', 'pending_values' => ['In-Transit'], 'label' => 'In-Transit Documents', 'route_name' => 'document-tracking.index'],
            ],
            'notes'            => '',
        ],
        [
            'key'              => 'issuances',
            'name'             => 'Official Issuances',
            'category'         => 'compliance_records',
            'description'      => 'OCD issuances (SO, TO, MEMO, OO, AO, CIRC, NOTICE) — TYPE-YEAR-MM-NNN numbering, QR scan stamp, Textract full-text search, PIN digital signing, queue-based PDF+email.',
            'route_name'       => 'issuances.index',
            'primary_table'    => 'issuances',
            'activity_col'     => 'created_at',
            'user_col'         => 'created_by',
            'maturity'         => 4,
            'queue_names'      => ['default'],
            'dependencies'     => ['employees'],
            'integrations'     => ['s3'],
            'pending_approvals' => [
                ['table' => 'issuances', 'status_col' => 'status', 'pending_values' => ['draft'], 'label' => 'Draft Issuances', 'route_name' => 'issuances.index'],
            ],
            'notes'            => '',
        ],
        [
            'key'           => 'km',
            'name'          => 'KM / OED Issuances',
            'category'      => 'compliance_records',
            'description'   => 'Knowledge Management portal for OED-level issuances with category management (code PK immutable) and full-text search via Textract pipeline.',
            'route_name'    => 'km.index',
            'primary_table' => 'oed_issuances',
            'activity_col'  => 'created_at',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => ['s3'],
            'notes'         => '',
        ],

        // ── IT & Requests ─────────────────────────────────────────────────────
        [
            'key'           => 'atlas_sentinel',
            'name'          => 'ICT Equipment (Atlas Sentinel)',
            'category'      => 'it_requests',
            'description'   => 'Windows agent-based ICT equipment health monitoring — scored snapshots, diagnostic findings, security evaluation, automated remediations, and fleet health dashboard.',
            'route_name'    => 'atlas-sentinel.health-dashboard',
            'primary_table' => 'ict_equipments',
            'activity_col'  => 'created_at',
            'maturity'      => 4,
            'queue_names'   => [],
            'dependencies'  => [],
            'integrations'  => ['cloudwatch', 's3'],
            'notes'         => 'Agent API at /api/ict-agent/* uses Sanctum device tokens, not user tokens.',
        ],
        [
            'key'           => 'it_job_requests',
            'name'          => 'IT Job Requests',
            'category'      => 'it_requests',
            'description'   => 'IT service desk — 3-day filing rule for event-type requests, load-balanced assignment (Junlou/Michael), and CSM satisfaction follow-up.',
            'route_name'    => 'it-job-requests.index',
            'primary_table' => 'it_job_requests',
            'activity_col'  => 'created_at',
            'user_col'      => 'user_id',
            'maturity'      => 4,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => ['smtp'],
            'notes'         => '',
        ],
        [
            'key'           => 'facility_requests',
            'name'          => 'Facility / Service Requests',
            'category'      => 'it_requests',
            'description'   => 'Campus facility booking and service requests — 3-day advance filing rule, approval workflow, and email notifications.',
            'route_name'    => 'facility-requests.index',
            'primary_table' => 'facility_requests',
            'activity_col'  => 'created_at',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => ['smtp'],
            'notes'         => '',
        ],

        // ── Communication & Data ──────────────────────────────────────────────
        [
            'key'           => 'recruitment',
            'name'          => 'Recruitment',
            'category'      => 'communication_data',
            'description'   => 'End-to-end hiring pipeline — public job portal, application intake, interview scheduling, HRMPSB evaluation, placement, and onboarding task tracking.',
            'route_name'    => 'recruitment.index',
            'primary_table' => 'applications',
            'activity_col'  => 'created_at',
            'maturity'      => 4,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => ['s3', 'smtp'],
            'notes'         => '',
        ],
        [
            'key'           => 'chat',
            'name'          => 'Chat',
            'category'      => 'communication_data',
            'description'   => 'Real-time campus messaging — direct and group channels, base64 file attachments, message status ticks, and mobile-first layout.',
            'route_name'    => 'chat.index',
            'primary_table' => 'messages',
            'activity_col'  => 'created_at',
            'user_col'      => 'sender_id',
            'maturity'      => 3,
            'queue_names'   => [],
            'dependencies'  => ['employees'],
            'integrations'  => ['pusher'],
            'notes'         => '',
        ],
        [
            'key'           => 'gad_dashboard',
            'name'          => 'GAD Data Dashboard',
            'category'      => 'communication_data',
            'description'   => 'Public sex-disaggregated statistics dashboard — 8 data modules, 1-hour cache, no authentication required.',
            'route_name'    => 'gad-data',
            'primary_table' => null,
            'activity_col'  => 'created_at',
            'maturity'      => 2,
            'queue_names'   => [],
            'dependencies'  => ['sis', 'employees'],
            'integrations'  => [],
            'notes'         => 'Read-only computed dashboard; no primary table to track — always shows "info" health status.',
        ],
        [
            'key'           => 'csm_feedback',
            'name'          => 'CSM Feedback',
            'category'      => 'communication_data',
            'description'   => 'Client Satisfaction Measurement — polymorphic feedback responses linked to IT Job Requests and other modules.',
            'route_name'    => null,
            'primary_table' => 'csm_responses',
            'activity_col'  => 'created_at',
            'user_col'      => 'user_id',
            'maturity'      => 2,
            'queue_names'   => [],
            'dependencies'  => ['it_job_requests'],
            'integrations'  => [],
            'notes'         => '',
        ],
        [
            'key'           => 'mobile_api',
            'name'          => 'Mobile API',
            'category'      => 'communication_data',
            'description'   => 'REST API for the parent/student mobile app — email OTP registration, secure link requests, grades and schedule endpoints.',
            'route_name'    => null,
            'primary_table' => 'student_mobile_links',
            'activity_col'  => 'created_at',
            'maturity'      => 2,
            'queue_names'   => [],
            'dependencies'  => ['sis'],
            'integrations'  => ['firebase'],
            'notes'         => 'Shares student_mobile_links with student_portal; API routes under /api/mobile.',
        ],
    ],
];
