<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
* { box-sizing:border-box; margin:0; padding:0; }
body { font-family:Arial, sans-serif; font-size:10pt; color:#1e293b; line-height:1.6; }

/* ── Issuance type header ── */
.issuance-header { text-align:center; margin:16px 0 12px; }
.issuance-type   { font-size:13pt; font-weight:bold; color:#060e50; text-transform:uppercase; letter-spacing:1px; }
.control-no      { font-size:10pt; color:#1447c0; margin-top:2px; }
.subject-line    { font-size:10pt; margin-top:6px; }

/* ── Body ── */
.body-content { margin:14px 0; text-align:justify; }
.body-content p { margin-bottom:8px; }

/* ── Signature block ── */
.sig-block { margin-top:30px; }
.sig-block .signed-by { font-size:8.5pt; color:#64748b; margin-bottom:4px; }
.sig-img   { max-height:50px; max-width:160px; }
.sig-name  { font-weight:bold; font-size:10pt; border-top:1px solid #334155; padding-top:4px; margin-top:4px; display:inline-block; min-width:200px; }
.sig-pos   { font-size:8.5pt; color:#475569; }

/* ── Footer note ── */
.auth-note { margin-top:20px; border-top:1px dashed #e2e8f0; padding-top:8px; font-size:7.5pt; color:#94a3b8; }
</style>
</head>
<body>

{{-- QR code: position:fixed → mPDF stamps it at absolute lower-right on every page --}}
@if($qrB64)
<div style="position:fixed; bottom:9mm; right:9mm; width:22mm; text-align:center; z-index:100;">
  <img src="data:image/svg+xml;base64,{{ $qrB64 }}" style="width:22mm; height:22mm; display:block;" alt="QR" />
  <div style="font-size:5pt; color:#64748b; margin-top:0.8mm; line-height:1.3;">Scan to verify<br>authenticity</div>
</div>
@endif

{{-- Letterhead provided by mPDF header image (report_header.jpeg) --}}

{{-- Issuance type header --}}
<div class="issuance-header">
  <div class="issuance-type">{{ $issuance->type_label }}</div>
  <div class="control-no">No. {{ $issuance->series_no }}, S. {{ $issuance->year }}</div>
</div>

{{-- Body content (editor mode only — scan mode uses stampQrOnScan) --}}
@if($issuance->content)
<div class="body-content">
  {!! $issuance->content !!}
</div>
@endif

{{-- Signature block --}}
<div class="sig-block" style="margin-top:30px;">
  <div class="signed-by">Signed by:</div>
  @if($sigUri)
  <img src="{{ $sigUri }}" class="sig-img" alt="Digital Signature" />
  @else
  <div style="height:50px;"></div>
  @endif
  <div class="sig-name">{{ $ocdUser?->name ?? 'Campus Director' }}</div>
  <div class="sig-pos">{{ $ocdUser?->position ?? 'Campus Director, PSHS-CRC' }}</div>
  @if($sig)
  <div style="font-size:7.5pt; color:#64748b; margin-top:3px;">
    Digitally signed: {{ $sig->signed_at?->format('F d, Y \a\t h:i A') }}
  </div>
  @endif
</div>

{{-- Authentication note --}}
<div class="auth-note">
  This document was generated by CRCMIS. Control No.: <strong>{{ $issuance->control_number }}</strong>
  @if($issuance->content_hash)
  · Hash: {{ substr($issuance->content_hash, 0, 16) }}…
  @endif
  · Verify at: mis.crc.pshs.edu.ph/verify/issuance/{{ $issuance->qr_token }}
</div>

</body>
</html>
