<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
* { box-sizing:border-box; margin:0; padding:0; }
body { font-family:Arial, sans-serif; font-size:10pt; color:#1e293b; line-height:1.6; }

/* ── Letterhead ── */
.letterhead { text-align:center; border-bottom:2px solid #060e50; padding-bottom:10px; margin-bottom:14px; }
.school-name { font-size:11pt; font-weight:bold; color:#060e50; letter-spacing:.5px; }
.campus-name { font-size:9pt; color:#475569; }
.address     { font-size:8pt; color:#64748b; }

/* ── Issuance type header ── */
.issuance-header { text-align:center; margin:16px 0 12px; }
.issuance-type   { font-size:13pt; font-weight:bold; color:#060e50; text-transform:uppercase; letter-spacing:1px; }
.control-no      { font-size:10pt; color:#1447c0; margin-top:2px; }
.subject-line    { font-size:10pt; margin-top:6px; }

/* ── Body ── */
.body-content { margin:14px 0; text-align:justify; }
.body-content p { margin-bottom:8px; }

/* ── Signature block ── */
.sig-block { margin-top:30px; }
.sig-block .signed-by { font-size:8.5pt; color:#64748b; margin-bottom:4px; }
.sig-img   { max-height:50px; max-width:160px; }
.sig-name  { font-weight:bold; font-size:10pt; border-top:1px solid #334155; padding-top:4px; margin-top:4px; display:inline-block; min-width:200px; }
.sig-pos   { font-size:8.5pt; color:#475569; }

/* ── QR block ── */
.qr-block  { position:absolute; bottom:0; right:0; text-align:center; width:100px; }
.qr-label  { font-size:6.5pt; color:#64748b; margin-top:2px; }

/* ── Footer note ── */
.auth-note { margin-top:20px; border-top:1px dashed #e2e8f0; padding-top:8px; font-size:7.5pt; color:#94a3b8; }
</style>
</head>
<body>

{{-- Letterhead --}}
<div class="letterhead">
  <div class="school-name">Philippine Science High School</div>
  <div class="campus-name">Caraga Region Campus</div>
  <div class="address">Ampayon, Butuan City 8600 · portal@crc.pshs.edu.ph</div>
</div>

{{-- Issuance type header --}}
<div class="issuance-header">
  <div class="issuance-type">{{ $issuance->type_label }}</div>
  <div class="control-no">No. {{ $issuance->series_no }}, S. {{ $issuance->year }}</div>
  @if($issuance->attachment_path)
  {{-- Scan mode: just the header info --}}
  <p class="subject-line"><strong>Re:</strong> {{ $issuance->title }}</p>
  @endif
</div>

@if($issuance->content)
{{-- Editor mode: render the body content --}}
<div class="body-content">
  {!! $issuance->content !!}
</div>
@else
{{-- Scan mode note --}}
<p style="color:#64748b; font-size:8.5pt; margin:10px 0;">
  (See attached scanned document: {{ $issuance->attachment_filename }})
</p>
@endif

{{-- Signature block --}}
<div style="position:relative; margin-top:30px;">
  <div class="sig-block">
    <div class="signed-by">Signed by:</div>
    @if($sigUri)
    <img src="{{ $sigUri }}" class="sig-img" alt="Digital Signature" />
    @else
    <div style="height:50px;"></div>
    @endif
    <div class="sig-name">{{ $ocdUser?->name ?? 'Campus Director' }}</div>
    <div class="sig-pos">{{ $ocdUser?->position ?? 'Campus Director, PSHS-CRC' }}</div>
    @if($sig)
    <div style="font-size:7.5pt; color:#64748b; margin-top:3px;">
      Digitally signed: {{ $sig->signed_at?->format('F d, Y \a\t h:i A') }}
    </div>
    @endif
  </div>

  {{-- QR Code --}}
  @if($qrB64)
  <div class="qr-block">
    <img src="data:image/svg+xml;base64,{{ $qrB64 }}" width="85" height="85" alt="QR Code" />
    <div class="qr-label">Scan to verify<br>authenticity</div>
  </div>
  @endif
</div>

{{-- Authentication note --}}
<div class="auth-note">
  This document was generated by CRCMIS. Control No.: <strong>{{ $issuance->control_number }}</strong>
  @if($issuance->content_hash)
  · Hash: {{ substr($issuance->content_hash, 0, 16) }}…
  @endif
  · Verify at: mis.crc.pshs.edu.ph/verify/issuance/{{ $issuance->qr_token }}
</div>

</body>
</html>
