<template>
  <Head title="Health Statistics — Print" />

  <table class="report-page report-page--landscape">
    <thead>
      <tr>
        <td class="report-letterhead">
          <img
            src="/images/report_header_landscape.jpg"
            alt="Philippine Science High School — Caraga Region Campus"
          />
        </td>
      </tr>
    </thead>

    <tfoot>
      <tr>
        <td class="report-page-footer">
          <div class="report-metadata">Generated by Atlas</div>
          <img src="/images/report_footer_landscape.jpg" alt="PSHS-CRC contact information" />
        </td>
      </tr>
    </tfoot>

    <tbody>
      <tr>
        <td class="report-content report-content--landscape">
          <div class="report-title">
            <h1>HEALTH STATISTICS</h1>
            <p>For the period: {{ periodLabel }}</p>
          </div>

          <div class="chart-panel">
            <canvas ref="chartCanvas" id="healthStatsChart"></canvas>
          </div>
        </td>
      </tr>
    </tbody>
  </table>

  <table class="report-page report-page--portrait">
    <thead>
      <tr>
        <td class="report-letterhead">
          <img
            src="/images/report_header.jpeg"
            alt="Philippine Science High School — Caraga Region Campus"
          />
        </td>
      </tr>
    </thead>

    <tfoot>
      <tr>
        <td class="report-page-footer">
          <div class="report-metadata">Generated by Atlas</div>
          <img src="/images/report_footer.jpeg" alt="PSHS-CRC contact information" />
        </td>
      </tr>
    </tfoot>

    <tbody>
      <tr>
        <td class="report-content report-content--portrait">
          <div class="report-title report-title--summary">
            <h2>DISEASE SUMMARY</h2>
            <p>For the period: {{ periodLabel }}</p>
          </div>

          <div v-if="diseaseSummary.length === 0" class="empty-state">
            No disease records for the selected period.
          </div>

          <table v-else class="summary-table">
            <thead>
              <tr>
                <th class="summary-number">No.</th>
                <th class="summary-disease">Disease</th>
                <th>Students<br>Male</th>
                <th>Students<br>Female</th>
                <th>Students<br>Total</th>
                <th>Employees<br>Male</th>
                <th>Employees<br>Female</th>
                <th>Employees<br>Total</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(d, idx) in diseaseSummary" :key="d.name">
                <td>{{ idx + 1 }}</td>
                <td class="summary-disease">{{ d.name }}</td>
                <td>{{ d.students_male || 0 }}</td>
                <td>{{ d.students_female || 0 }}</td>
                <td>{{ d.students_total || 0 }}</td>
                <td>{{ d.employees_male || 0 }}</td>
                <td>{{ d.employees_female || 0 }}</td>
                <td>{{ d.employees_total || 0 }}</td>
                <td>{{ d.total || 0 }}</td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>
</template>

<script>
import { onMounted, ref } from 'vue';
import { Head } from '@inertiajs/vue3';

export default {
  components: { Head },
  props: {
    labels: { type: Array, default: () => [] },
    facultyMale: { type: Array, default: () => [] },
    facultyFemale: { type: Array, default: () => [] },
    staffMale: { type: Array, default: () => [] },
    staffFemale: { type: Array, default: () => [] },
    studentMale: { type: Array, default: () => [] },
    studentFemale: { type: Array, default: () => [] },
    start: { type: [String, null], default: null },
    end: { type: [String, null], default: null },
    diseasesData: { type: Array, default: () => [] },
    diseaseSummary: { type: Array, default: () => [] },
  },
  setup(props) {
    const chartCanvas = ref(null);
    const chartInstance = ref(null);

    const periodLabel = (() => {
      if (props.start && props.end) return `${props.start} — ${props.end}`;
      if (props.start) return `From ${props.start}`;
      if (props.end) return `Up to ${props.end}`;
      return 'All dates';
    })();

    onMounted(async () => {
      // Try to dynamically import Chart.js; if not installed, skip rendering.
      try {
        const Chart = (await import('chart.js/auto')).default;
        const { seriesColor } = await import('@/Utils/chartTheme');

        const ctx = chartCanvas.value.getContext('2d');
        const datasets = [
          { label: 'FACULTY (FEMALE)', data: props.facultyFemale || [] },
          { label: 'FACULTY (MALE)', data: props.facultyMale || [] },
          { label: 'STAFF (FEMALE)', data: props.staffFemale || [] },
          { label: 'STAFF (MALE)', data: props.staffMale || [] },
          { label: 'STUDENT (FEMALE)', data: props.studentFemale || [] },
          { label: 'STUDENT (MALE)', data: props.studentMale || [] },
        ].map((d, i) => ({ ...d, backgroundColor: seriesColor(i) }));

        chartInstance.value = new Chart(ctx, {
          type: 'bar',
          data: {
            labels: props.labels || [],
            datasets: datasets,
          },
          options: {
            scales: {
              x: { stacked: false, ticks: { autoSkip: false } },
              y: { beginAtZero: true },
            },
            plugins: {
              legend: { position: 'bottom' },
              title: { display: false },
            },
          }
        });
        // If the URL contains autoprint=1, trigger print after a short delay
        try {
          const params = new URLSearchParams(window.location.search || window.location.hash.replace(/^#/, ''));
          if (params.get('autoprint') === '1') {
            setTimeout(() => { window.print(); }, 800);
          }
        } catch (err) {
          // ignore
        }
      } catch (e) {
        console.warn('Chart.js not available — falling back to simple layout', e);
      }
    });

    const print = () => { window.print(); };

    return { chartCanvas, chartInstance, periodLabel, print };
  }
}
</script>

<style scoped>
@page health-landscape {
  size: A4 landscape;
  margin: 6mm 0 0;
}

@page health-portrait {
  size: A4 portrait;
  margin: 6mm 0 0;
}

.report-page {
  width: 100%;
  max-width: 1200px;
  margin: 16px auto;
  border-collapse: collapse;
  background: #fff;
}

.report-page--portrait {
  max-width: 794px;
}

.report-letterhead,
.report-page-footer {
  padding: 0;
}

.report-letterhead img,
.report-page-footer img {
  display: block;
  width: 100%;
  height: auto;
}

.report-metadata {
  padding: 4px 12px;
  color: #64748b;
  font-size: 11px;
  text-align: right;
}

.report-content {
  vertical-align: top;
}

.report-content--landscape {
  padding: 8px 40px 16px;
}

.report-content--portrait {
  padding: 8px 34px 16px;
}

.report-title {
  margin-bottom: 12px;
  text-align: center;
}

.report-title h1 {
  margin: 0;
  color: #1e293b;
  font-size: 28px;
  font-weight: 800;
}

.report-title h2 {
  margin: 0;
  color: #1e293b;
  font-size: 20px;
  font-weight: 700;
}

.report-title p {
  margin: 4px 0 0;
  color: #64748b;
  font-size: 14px;
}

.report-title--summary {
  margin-bottom: 10px;
}

.chart-panel {
  padding: 16px;
  border: 1px solid #e2e8f0;
  border-radius: 12px;
}

#healthStatsChart {
  width: 100%;
  height: 420px;
}

.empty-state {
  color: #475569;
  font-size: 13px;
}

.summary-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 12px;
}

.summary-table th,
.summary-table td {
  padding: 6px;
  border: 1px solid #222;
  text-align: center;
}

.summary-table th {
  background: #f1f5f9;
  font-weight: 700;
}

.summary-table .summary-number {
  width: 40px;
}

.summary-table .summary-disease {
  text-align: left;
}

@media print {
  :global(body) {
    margin: 0;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }

  .report-page {
    max-width: none;
    margin: 0;
  }

  .report-page--landscape {
    page: health-landscape;
    height: 203mm;
    break-after: page;
    page-break-after: always;
  }

  .report-page--portrait {
    page: health-portrait;
    min-height: 291mm;
  }

  .report-content--landscape {
    padding: 2mm 15mm 4mm;
  }

  .report-content--portrait {
    padding: 2mm 12mm 4mm;
  }

  .report-metadata {
    padding: 1mm 6mm;
    font-size: 8pt;
  }

  .chart-panel {
    padding: 3mm;
    border-radius: 0;
    box-shadow: none;
  }

  #healthStatsChart {
    height: 105mm !important;
  }

  .summary-table {
    font-size: 8.5pt;
  }

  .summary-table thead {
    display: table-header-group;
  }

  .summary-table tr {
    break-inside: avoid;
    page-break-inside: avoid;
  }
}
</style>
