<template>
  <div class="p-4 bg-white printable-report">
    <div class="report-header-wrap text-center mb-4">
      <img src="/images/report_header.jpeg" alt="Report Header" class="report-header mx-auto" />
      <h1 class="text-3xl font-extrabold mt-2 text-slate-800">HEALTH STATISTICS</h1>
      <div class="text-base text-slate-500 mt-1">For the period: {{ periodLabel }}</div>
    </div>

    <div class="bg-white rounded-xl border border-slate-100 shadow-sm p-4">
      <canvas ref="chartCanvas" id="healthStatsChart" style="width:100%;height:420px"></canvas>
    </div>

    <div class="mt-4 text-sm text-slate-500">Generated by BUGSAYMIS</div>
    <img src="/images/report_footer.jpeg" alt="Report Footer" class="report-footer mt-4" />
  </div>
</template>

<script>
import { onMounted, ref } from 'vue';

export default {
  props: {
    labels: { type: Array, default: () => [] },
    facultyMale: { type: Array, default: () => [] },
    facultyFemale: { type: Array, default: () => [] },
    staffMale: { type: Array, default: () => [] },
    staffFemale: { type: Array, default: () => [] },
    studentMale: { type: Array, default: () => [] },
    studentFemale: { type: Array, default: () => [] },
    start: { type: [String, null], default: null },
    end: { type: [String, null], default: null },
  },
  setup(props) {
    const chartCanvas = ref(null);
    const chartInstance = ref(null);

    const periodLabel = (() => {
      if (props.start && props.end) return `${props.start} — ${props.end}`;
      if (props.start) return `From ${props.start}`;
      if (props.end) return `Up to ${props.end}`;
      return 'All dates';
    })();

    onMounted(async () => {
      // Try to dynamically import Chart.js; if not installed, skip rendering.
      try {
        const Chart = (await import('chart.js/auto')).default;

        const ctx = chartCanvas.value.getContext('2d');
        const datasets = [
          { label: 'FACULTY (FEMALE)', backgroundColor: '#ff6384', data: props.facultyFemale || [] },
          { label: 'FACULTY (MALE)', backgroundColor: '#36a2eb', data: props.facultyMale || [] },
          { label: 'STAFF (FEMALE)', backgroundColor: '#ff9f40', data: props.staffFemale || [] },
          { label: 'STAFF (MALE)', backgroundColor: '#4bc0c0', data: props.staffMale || [] },
          { label: 'STUDENT (FEMALE)', backgroundColor: '#e83e8c', data: props.studentFemale || [] },
          { label: 'STUDENT (MALE)', backgroundColor: '#2b8aef', data: props.studentMale || [] },
        ];

        chartInstance.value = new Chart(ctx, {
          type: 'bar',
          data: {
            labels: props.labels || [],
            datasets: datasets,
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
              x: { stacked: false, ticks: { autoSkip: false }, grid: { display: false } },
              y: { beginAtZero: true, grid: { color: '#e5e7eb' } },
            },
            plugins: {
              legend: { position: 'bottom', labels: { boxWidth: 12, padding: 10 } },
              title: { display: false },
            },
          }
        });
        // If the URL contains autoprint=1, trigger print after a short delay
        try {
          const params = new URLSearchParams(window.location.search || window.location.hash.replace(/^#/, ''));
          if (params.get('autoprint') === '1') {
            setTimeout(() => { window.print(); }, 800);
          }
        } catch (err) {
          // ignore
        }
      } catch (e) {
        console.warn('Chart.js not available — falling back to simple layout', e);
      }
    });

    const print = () => { window.print(); };

    return { chartCanvas, chartInstance, periodLabel, print };
  }
}
</script>

<style scoped>
@page { size: A4 landscape; }
@media print {
  body { -webkit-print-color-adjust: exact; }
  .printable-report { width: 100%; }
}
.printable-report { max-width: 1200px; margin: 0 auto; }
.report-header { width: 100%; max-width: 1200px; height: auto; object-fit: contain; max-height: 110px; }
.report-footer { width: 100%; max-width: 1200px; height: auto; object-fit: contain; display: block; margin: 0 auto; max-height: 80px; }
@media print {
  .report-footer { position: fixed; bottom: 0; left: 0; right: 0; max-height: 60px; }
  .report-header { position: relative; top: 0; max-height: 80px; }
  #healthStatsChart { height: 360px !important; }
}
</style>
