<?php

namespace App\Services\Discipline;

use App\Models\Discipline\DisciplineCase;
use App\Models\DigitalSignature;
use App\Services\DigitalSignatureService;
use Mpdf\Mpdf;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Generates the Anecdotal Report PDF (PSHS-00-F-SDO-01) for a discipline case.
 * Streams freshly-generated bytes — no storage round-trip (mirrors ITJobRequestPdfService).
 */
class DisciplineCasePdfService
{
    public function __construct(
        private StudentResolver $students,
        private DigitalSignatureService $sig,
    ) {}

    public function stream(DisciplineCase $case): StreamedResponse
    {
        $pdfBytes = $this->buildPdfBytes($case);
        $filename = 'AnecdotalReport_' . $case->case_no . '.pdf';

        return new StreamedResponse(function () use ($pdfBytes) {
            echo $pdfBytes;
        }, 200, [
            'Content-Type'        => 'application/pdf',
            'Content-Disposition' => 'inline; filename="' . $filename . '"',
            'Content-Length'      => strlen($pdfBytes),
        ]);
    }

    private function buildPdfBytes(DisciplineCase $case): string
    {
        $prevMemory = ini_get('memory_limit');
        ini_set('memory_limit', '256M');

        $case->loadMissing(['offense', 'filer', 'receiver', 'resolver', 'interventions', 'signatorySnapshots']);

        $student = $this->students->resolve($case->student_id);

        // Signature images — from captured signatory snapshots, gated on the stage
        $receivedSig = $case->received_at
            ? $this->sig->getImageDataUriFromPath(optional($case->signatoryForRole('Received By'))->signature_path)
            : null;
        $resolvedSig = $case->resolved_at
            ? $this->sig->getImageDataUriFromPath(optional($case->signatoryForRole('Resolved By'))->signature_path)
            : null;

        // Digital signature badges + a single verification QR
        $signedBadges = [];
        $documentQr   = null;
        $digitalSigs  = DigitalSignature::where('signable_type', DisciplineCase::class)
            ->where('signable_id', $case->id)
            ->latest('signed_at')
            ->get();

        foreach ($digitalSigs as $ds) {
            $stage = $ds->metadata['stage'] ?? null;
            if ($stage && ! isset($signedBadges[$stage])) {
                $signedBadges[$stage] = $ds->signed_at->format('M d, Y h:i A');
            }
        }
        if ($digitalSigs->isNotEmpty()) {
            $documentQr = base64_encode($this->sig->generateQrSvg($digitalSigs->first()->verification_token, 110));
        }

        $html = view('discipline.anecdotal-report', [
            'case'         => $case,
            'student'      => $student,
            'receivedSig'  => $receivedSig,
            'resolvedSig'  => $resolvedSig,
            'signedBadges' => $signedBadges,
            'documentQr'   => $documentQr,
        ])->render();

        $mpdf = new Mpdf([
            'mode'          => 'utf-8',
            'format'        => 'A4',
            'margin_left'   => 15,
            'margin_right'  => 15,
            'margin_top'    => 15,
            'margin_bottom' => 15,
            'tempDir'       => sys_get_temp_dir(),
        ]);

        $mpdf->SetTitle('Anecdotal Report — ' . $case->case_no);

        // Base64-embedded signature images can exceed pcre.backtrack_limit (1 MB)
        $prevBacktrack = ini_get('pcre.backtrack_limit');
        ini_set('pcre.backtrack_limit', (string) (10 * 1000 * 1000));
        $mpdf->WriteHTML($html);
        ini_set('pcre.backtrack_limit', (string) $prevBacktrack);

        $pdfBytes = $mpdf->Output('', 'S');
        ini_set('memory_limit', $prevMemory);

        return $pdfBytes;
    }
}
