<?php

namespace App\Http\Controllers;

use App\Models\AgencyOutcome;
use App\Models\DostPillar;
use Inertia\Inertia;

class DostStrategicPlanController extends Controller
{
    public function index()
    {
        return Inertia::render('PerformanceManagement/DostStrategicPlan', [
            'pillars' => DostPillar::with(['agencyOutcomes', 'strategies.subStrategies', 'strategies.agencyOutcomes'])
                ->orderBy('name')
                ->get(),
            'agencyOutcomes' => AgencyOutcome::topLevel()
                ->excludingAutoGeneratedMarker()
                ->orderBy('outcome')
                ->get(['id', 'outcome']),
        ]);
    }
}
