<template>
  <Head title="Document Request Processing" /><AdminLayout title="Document Request Processing"><div class="space-y-5">
    <AppPageHeader title="HR Document Request Processing" subtitle="Review, prepare, route, and issue employee certifications." />
    <div class="grid grid-cols-2 gap-3 lg:grid-cols-5"><AppCard v-for="item in cards" :key="item.label"><p class="text-2xl font-bold" :class="item.color">{{ item.value }}</p><p class="text-xs text-slate-500">{{ item.label }}</p></AppCard></div>
    <AppCard><div class="mb-4 flex flex-wrap items-center gap-3"><input v-model="search" placeholder="Search employee, reference, document..." class="w-80 rounded-lg border border-slate-200 px-3 py-2 text-sm"/><select v-model="status" class="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">All statuses</option><option v-for="s in statuses" :key="s" :value="s">{{ label(s) }}</option></select><AppButton v-if="canManageTypes" variant="secondary" class="ml-auto" @click="showTypes=!showTypes"><Cog6ToothIcon class="h-4 w-4"/> Document Catalog</AppButton></div>
      <AppTable :is-empty="filtered.length===0" :skeleton-cols="7"><template #head><tr><th class="px-4 py-3 text-left">Reference</th><th class="px-4 py-3 text-left">Employee</th><th class="px-4 py-3 text-left">Document</th><th class="px-4 py-3 text-left">Processor</th><th class="px-4 py-3 text-left">Due</th><th class="px-4 py-3 text-left">Status</th><th class="px-4 py-3 text-right">Review</th></tr></template><tr v-for="row in filtered" :key="row.id" class="border-t border-slate-100 hover:bg-indigo-50/30"><td class="px-4 py-3 font-mono text-xs">{{ row.reference_no }}</td><td class="px-4 py-3"><p class="text-sm font-medium text-slate-700">{{ row.requester.name }}</p><p class="text-xs text-slate-400">{{ row.requester.position }}</p></td><td class="px-4 py-3 text-sm">{{ row.type.name }}</td><td class="px-4 py-3 text-xs text-slate-500">{{ row.processor?.name ?? 'Unassigned' }}</td><td class="px-4 py-3 text-xs" :class="overdue(row)?'font-semibold text-rose-600':'text-slate-500'">{{ date(row.due_at) }}</td><td class="px-4 py-3"><AppBadge :color="statusColor(row.status)">{{ label(row.status) }}</AppBadge></td><td class="px-4 py-3 text-right"><Link :href="route('hr.document-requests.show',row.id)" class="text-sm font-medium text-indigo-600">Open workspace</Link></td></tr></AppTable>
    </AppCard>
    <AppCard v-if="canManageTypes && showTypes"><div class="mb-4"><h2 class="font-semibold text-slate-800">Document Catalog & Approval Matrix</h2><p class="text-xs text-slate-500">Configure SLA, availability, delivery, and OCD routing.</p></div><div class="grid gap-3 lg:grid-cols-2"><div v-for="type in types" :key="type.id" class="rounded-xl border border-slate-200 p-4"><div class="flex justify-between"><div><p class="font-semibold text-slate-800">{{ type.name }}</p><p class="font-mono text-[10px] text-slate-400">{{ type.code }}</p></div><AppBadge :color="type.is_active?'green':'slate'">{{ type.is_active?'Active':'Inactive' }}</AppBadge></div><p class="my-3 text-xs text-slate-500">{{ type.description }}</p><div class="flex flex-wrap gap-2 text-[11px]"><span class="rounded-full bg-slate-100 px-2 py-1">{{ type.sla_business_days }} business days</span><span class="rounded-full bg-amber-50 px-2 py-1 text-amber-700">{{ type.requires_ocd_approval?'OCD approval':'HR approval' }}</span><span class="rounded-full bg-indigo-50 px-2 py-1 text-indigo-700">Signatory: {{ type.signatory.toUpperCase() }}</span></div><button class="mt-3 text-xs font-medium text-indigo-600" @click="editType(type)">Edit settings</button></div></div></AppCard>
    <AppModal :show="!!editing" title="Document Type Settings" body-class="space-y-4 px-6 py-5" @close="editing=null"><AppInput v-model="typeForm.name" label="Name"/><AppTextarea v-model="typeForm.description" label="Description" :rows="2"/><AppTextarea v-model="typeForm.instructions" label="Employee Instructions" :rows="2"/><AppInput v-model="typeForm.sla_business_days" type="number" label="SLA (Business Days)"/><div class="grid grid-cols-2 gap-3"><label class="text-sm"><input v-model="typeForm.requires_ocd_approval" type="checkbox" class="mr-2">Requires OCD approval</label><label class="text-sm"><input v-model="typeForm.is_active" type="checkbox" class="mr-2">Active</label><label class="text-sm"><input v-model="typeForm.supports_digital" type="checkbox" class="mr-2">Digital delivery</label><label class="text-sm"><input v-model="typeForm.supports_pickup" type="checkbox" class="mr-2">Pickup</label></div><div class="rounded-lg bg-slate-50 p-3 text-sm text-slate-600"><strong>Signatory:</strong> {{ typeForm.requires_ocd_approval ? 'OCD' : 'HR' }} <span class="text-xs text-slate-400">(set automatically by the approval requirement)</span></div><template #footer><AppButton variant="secondary" @click="editing=null">Cancel</AppButton><AppButton :loading="typeForm.processing" @click="saveType">Save Settings</AppButton></template></AppModal>
  </div></AdminLayout>
</template>
<script setup>
import { computed, ref } from 'vue'; import { Head, Link, useForm } from '@inertiajs/vue3'; import { Cog6ToothIcon } from '@heroicons/vue/24/outline'; import AdminLayout from '@/Layouts/AdminLayout.vue'; import AppPageHeader from '@/Components/AppPageHeader.vue'; import AppCard from '@/Components/AppCard.vue'; import AppTable from '@/Components/AppTable.vue'; import AppBadge from '@/Components/AppBadge.vue'; import AppButton from '@/Components/AppButton.vue'; import AppModal from '@/Components/AppModal.vue'; import AppInput from '@/Components/AppInput.vue'; import AppTextarea from '@/Components/AppTextarea.vue';
const props=defineProps({requests:Array,stats:Object,types:Array,canManageTypes:Boolean}); const search=ref(''),status=ref(''),showTypes=ref(false),editing=ref(null); const statuses=[...new Set(props.requests.map(r=>r.status))]; const cards=computed(()=>[{label:'New',value:props.stats.new,color:'text-blue-600'},{label:'Processing',value:props.stats.processing,color:'text-indigo-600'},{label:'Awaiting OCD',value:props.stats.awaiting_ocd,color:'text-amber-600'},{label:'Overdue',value:props.stats.overdue,color:'text-rose-600'},{label:'Issued',value:props.stats.issued,color:'text-emerald-600'}]); const filtered=computed(()=>{const q=search.value.toLowerCase();return props.requests.filter(r=>(!status.value||r.status===status.value)&&`${r.reference_no} ${r.requester.name} ${r.type.name}`.toLowerCase().includes(q))}); const typeForm=useForm({name:'',description:'',instructions:'',requires_ocd_approval:false,signatory:'hr',sla_business_days:3,supports_digital:true,supports_pickup:true,is_active:true}); function editType(t){editing.value=t;Object.keys(typeForm.data()).forEach(k=>typeForm[k]=t[k])} function saveType(){typeForm.signatory=typeForm.requires_ocd_approval?'ocd':'hr';typeForm.put(route('hr.document-request-types.update',editing.value.id),{preserveScroll:true,onSuccess:()=>editing.value=null})} function label(s){return s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())} function date(v){return v?new Date(v).toLocaleDateString('en-PH',{year:'numeric',month:'short',day:'numeric'}):'—'} function overdue(r){return r.due_at&&!['issued','rejected','cancelled'].includes(r.status)&&new Date(r.due_at)<new Date()} function statusColor(s){return ({issued:'green',submitted:'blue',processing:'indigo',pending_ocd_approval:'amber',ready_for_release:'emerald',returned:'orange',ocd_returned:'orange',rejected:'red',cancelled:'slate'})[s]??'slate'}
</script>
