<template>
  <Head :title="documentRequest.reference_no" /><AdminLayout title="Document Request"><div class="space-y-5">
    <div class="flex flex-wrap items-start justify-between gap-3"><div><Link :href="canProcess ? route('hr.document-requests.manage') : route('hr.document-requests.index')" class="text-xs font-medium text-indigo-600">← Back to requests</Link><div class="mt-2 flex items-center gap-3"><h1 class="text-2xl font-bold text-slate-800">{{ documentRequest.reference_no }}</h1><AppBadge :color="statusColor(documentRequest.status)">{{ label(documentRequest.status) }}</AppBadge></div><p class="mt-1 text-sm text-slate-500">{{ documentRequest.type.name }} · Filed {{ dateTime(documentRequest.submitted_at) }}</p></div><div class="flex flex-wrap gap-2"><a v-if="latestIssued" :href="route('hr.document-requests.download',latestIssued.id)" class="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white"><ArrowDownTrayIcon class="h-4 w-4"/> Download Issued Document</a><AppButton v-if="isOwner && ['submitted','returned'].includes(documentRequest.status)" variant="danger" @click="cancelRequest">Cancel Request</AppButton></div></div>
    <div v-if="$page.props.flash?.success" class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ $page.props.flash.success }}</div>

    <div class="grid gap-5 xl:grid-cols-[1fr_360px]">
      <div class="space-y-5">
        <AppCard><h2 class="mb-4 font-semibold text-slate-800">Request Information</h2><div class="grid gap-4 text-sm md:grid-cols-2"><div v-for="field in requestFields" :key="field.label" :class="field.full?'md:col-span-2':''"><p class="text-[11px] font-semibold uppercase tracking-wide text-slate-400">{{ field.label }}</p><p class="mt-1 whitespace-pre-wrap text-slate-700">{{ field.value || '—' }}</p></div></div><div v-if="documentRequest.employee_visible_remarks" class="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><strong>HR Remarks:</strong> {{ documentRequest.employee_visible_remarks }}</div></AppCard>

        <AppCard v-if="documentRequest.attachments.length"><h2 class="mb-3 font-semibold text-slate-800">Supporting Files</h2><div class="divide-y divide-slate-100"><a v-for="file in documentRequest.attachments" :key="file.id" :href="route('hr.document-requests.attachments.download',file.id)" class="flex items-center justify-between py-3 text-sm text-indigo-600"><span class="flex items-center gap-2"><PaperClipIcon class="h-4 w-4"/>{{ file.original_filename }}</span><span class="text-xs text-slate-400">{{ size(file.file_size) }}</span></a></div></AppCard>

        <AppCard v-if="canProcess && ['processing','ocd_returned'].includes(documentRequest.status)"><div class="mb-4 flex items-center justify-between"><div><h2 class="font-semibold text-slate-800">Document Preparation Workspace</h2><p class="text-xs text-slate-500">Review the generated content before routing or issuance.</p></div><AppBadge :color="documentRequest.type.requires_ocd_approval?'amber':'indigo'">{{ documentRequest.type.requires_ocd_approval?'OCD signature required':'HR signature' }}</AppBadge></div>
          <div class="grid gap-3 md:grid-cols-2"><AppInput v-model="draft.document_payload.employee_name" label="Employee Name"/><AppInput v-model="draft.document_payload.position" label="Position"/><AppInput v-model="draft.document_payload.employee_no" label="Employee Number"/><AppInput v-model="draft.document_payload.appointment_status" label="Appointment Status"/></div>
          <template v-if="documentRequest.type.template_key==='service_record'"><div class="mt-5 flex items-center justify-between"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">Service Entries</p><AppButton size="sm" variant="secondary" @click="addRow">Add Entry</AppButton></div><div class="mt-2 overflow-x-auto"><table class="w-full min-w-[850px] text-xs"><thead class="bg-slate-50 text-slate-500"><tr><th v-for="h in ['From','To','Position','Agency','Appointment','Government','']" :key="h" class="px-2 py-2 text-left">{{ h }}</th></tr></thead><tbody><tr v-for="(row,i) in draft.document_payload.service_rows" :key="i" class="border-t border-slate-100"><td><input v-model="row.from" class="cell"></td><td><input v-model="row.to" class="cell"></td><td><input v-model="row.position" class="cell"></td><td><input v-model="row.agency" class="cell"></td><td><input v-model="row.appointment_status" class="cell"></td><td><select v-model="row.government_service" class="cell"><option>Yes</option><option>No</option></select></td><td><button class="text-rose-600" @click="draft.document_payload.service_rows.splice(i,1)">Remove</button></td></tr></tbody></table></div></template>
          <AppTextarea v-else v-model="draft.document_payload.body" class="mt-4" label="Certification Body" :rows="7"/><AppTextarea v-model="draft.document_payload.certification_clause" class="mt-4" label="Closing Certification Clause" :rows="2"/><AppTextarea v-model="draft.internal_notes" class="mt-4" label="Internal HR Notes" :rows="2"/>
          <p v-if="draft.isDirty" class="mt-4 text-right text-xs font-medium text-amber-600">Save the current changes before routing or issuing.</p>
          <div class="mt-3 flex flex-wrap justify-end gap-2"><AppButton variant="secondary" :loading="draft.processing" @click="saveDraft">Save Draft</AppButton><AppButton v-if="documentRequest.type.requires_ocd_approval" :disabled="draft.isDirty" @click="routeToOcd">Route to OCD</AppButton><AppButton v-else-if="canIssue" :disabled="draft.isDirty" @click="issue">Sign & Issue</AppButton></div>
        </AppCard>

        <AppCard v-if="documentRequest.document_payload && (canProcess || ['pending_ocd_approval','ready_for_release'].includes(documentRequest.status))">
          <div class="mb-4 flex items-center justify-between"><div><h2 class="font-semibold text-slate-800">Document Preview</h2><p class="text-xs text-slate-500">Content snapshot used for review and approval.</p></div><AppBadge color="slate">Preview</AppBadge></div>
          <div class="mx-auto max-w-3xl border border-slate-200 bg-white px-8 py-10 shadow-sm md:px-14">
            <p class="text-right text-[10px] text-slate-400">{{ documentRequest.reference_no }}</p>
            <h3 class="my-10 text-center text-lg font-bold uppercase tracking-[0.16em] text-blue-950">{{ documentRequest.type.name }}</h3>
            <template v-if="documentRequest.type.template_key==='service_record'">
              <p class="mb-4 text-sm leading-7 text-slate-700">This is to certify that the following is the service record of <strong>{{ documentRequest.document_payload.employee_name }}</strong> based on the records reviewed by the Human Resource Office:</p>
              <div class="overflow-x-auto"><table class="w-full min-w-[650px] border-collapse text-[10px]"><thead><tr class="bg-slate-100"><th v-for="heading in ['From','To','Designation','Station / Agency','Appointment','Gov’t Service']" :key="heading" class="border border-slate-300 p-2 text-left">{{ heading }}</th></tr></thead><tbody><tr v-for="(row,index) in documentRequest.document_payload.service_rows" :key="index"><td v-for="key in ['from','to','position','agency','appointment_status','government_service']" :key="key" class="border border-slate-300 p-2">{{ row[key] || '—' }}</td></tr></tbody></table></div>
            </template>
            <p v-else class="whitespace-pre-wrap text-justify text-sm leading-8 text-slate-700">{{ documentRequest.document_payload.body }}</p>
            <p class="mt-5 whitespace-pre-wrap text-justify text-sm leading-8 text-slate-700">{{ documentRequest.document_payload.certification_clause }}</p>
            <p class="mt-7 text-xs text-slate-500"><strong>Purpose:</strong> {{ documentRequest.purpose }}</p>
            <div class="mt-12"><div class="h-10"></div><p class="font-semibold text-slate-800">{{ documentRequest.type.requires_ocd_approval ? (documentRequest.ocd_approver?.name || 'OCD AUTHORIZED SIGNATORY') : 'HR AUTHORIZED SIGNATORY' }}</p><p class="text-xs text-slate-500">Digitally signed upon approval and issuance</p></div>
          </div>
        </AppCard>

        <AppCard v-if="canProcess && documentRequest.status==='submitted'"><h2 class="font-semibold text-slate-800">HR Intake Review</h2><p class="mt-1 text-sm text-slate-500">Accept and generate the initial draft, return for more information, or reject with a reason.</p><div class="mt-4 flex flex-wrap gap-2"><AppButton @click="post('start')">Accept & Start Processing</AppButton><AppButton variant="secondary" @click="remarksAction='return'">Return to Employee</AppButton><AppButton variant="danger" @click="remarksAction='reject'">Reject</AppButton></div></AppCard>
        <AppCard v-if="canProcess && documentRequest.status==='ready_for_release'"><h2 class="font-semibold text-emerald-800">Approved and Signed by OCD</h2><p class="mt-1 text-sm text-slate-500">Complete the HR quality check, then issue the canonical document.</p><div class="mt-4"><AppButton v-if="canIssue" @click="issue">Issue Document</AppButton></div></AppCard>
        <AppCard v-if="documentRequest.status==='pending_ocd_approval'"><h2 class="font-semibold text-amber-800">Awaiting OCD Approval</h2><p class="mt-1 text-sm text-slate-500">The prepared document is in the OCD Approval Inbox for PIN-verified approval and signature.</p></AppCard>

        <AppCard v-if="isOwner && documentRequest.status==='returned'"><h2 class="font-semibold text-slate-800">Update and Resubmit</h2><div class="mt-4 space-y-3"><AppTextarea v-model="resubmit.purpose" label="Purpose" :rows="3"/><div class="grid gap-3 md:grid-cols-2"><AppInput v-model="resubmit.addressed_to" label="Addressed To"/><AppInput v-model="resubmit.destination_agency" label="Receiving Agency"/><AppInput v-model="resubmit.needed_at" type="date" label="Date Needed"/><div><label class="text-xs font-semibold uppercase text-slate-500">Delivery</label><select v-model="resubmit.delivery_method" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"><option value="digital">Digital</option><option value="pickup">Pickup</option></select></div></div><AppTextarea v-model="resubmit.special_instructions" label="Special Instructions" :rows="2"/><AppButton :loading="resubmit.processing" @click="resubmitRequest">Resubmit to HR</AppButton></div></AppCard>
      </div>

      <div class="space-y-5"><AppCard><h2 class="mb-4 font-semibold text-slate-800">Progress Timeline</h2><div class="relative space-y-5 before:absolute before:bottom-2 before:left-[7px] before:top-2 before:w-px before:bg-slate-200"><div v-for="event in documentRequest.events" :key="event.id" class="relative pl-7"><span class="absolute left-0 top-1 h-3.5 w-3.5 rounded-full border-2 border-white bg-indigo-500 ring-1 ring-indigo-200"></span><p class="text-sm font-medium text-slate-700">{{ label(event.action) }}</p><p class="text-xs text-slate-500">{{ event.actor?.name ?? 'System' }} · {{ dateTime(event.created_at) }}</p><p v-if="event.remarks" class="mt-1 text-xs leading-5 text-slate-600">{{ event.remarks }}</p></div></div></AppCard><AppCard><h2 class="mb-3 font-semibold text-slate-800">Service Commitment</h2><div class="space-y-3 text-sm"><div class="flex justify-between"><span class="text-slate-500">Target turnaround</span><strong>{{ documentRequest.type.sla_business_days }} business days</strong></div><div class="flex justify-between"><span class="text-slate-500">Due date</span><strong :class="overdue?'text-rose-600':'text-slate-700'">{{ date(documentRequest.due_at) }}</strong></div><div class="flex justify-between"><span class="text-slate-500">OCD approval</span><strong>{{ documentRequest.type.requires_ocd_approval?'Required':'Not required' }}</strong></div></div></AppCard></div>
    </div>
    <AppModal :show="!!remarksAction" :title="remarksAction==='reject'?'Reject Request':'Return to Employee'" body-class="px-6 py-5" @close="remarksAction=null"><AppTextarea v-model="remarks" label="Remarks" :rows="4"/><template #footer><AppButton variant="secondary" @click="remarksAction=null">Cancel</AppButton><AppButton :variant="remarksAction==='reject'?'danger':'primary'" @click="submitRemarks">Confirm</AppButton></template></AppModal>
  </div></AdminLayout>
</template>
<script setup>
import { computed, ref } from 'vue'; import { Head, Link, router, useForm, usePage } from '@inertiajs/vue3'; import Swal from 'sweetalert2'; import { ArrowDownTrayIcon, PaperClipIcon } from '@heroicons/vue/24/outline'; import AdminLayout from '@/Layouts/AdminLayout.vue'; import AppCard from '@/Components/AppCard.vue'; import AppBadge from '@/Components/AppBadge.vue'; import AppButton from '@/Components/AppButton.vue'; import AppModal from '@/Components/AppModal.vue'; import AppInput from '@/Components/AppInput.vue'; import AppTextarea from '@/Components/AppTextarea.vue';
const props=defineProps({documentRequest:Object,canProcess:Boolean,canIssue:Boolean,hasPin:Boolean,signatureUri:String}); const page=usePage(); const latestIssued=computed(()=>props.documentRequest.issued_documents?.[0]??null); const isOwner=computed(()=>props.documentRequest.requester_id===page.props.auth.user.id); const overdue=computed(()=>props.documentRequest.due_at&&!['issued','rejected','cancelled'].includes(props.documentRequest.status)&&new Date(props.documentRequest.due_at)<new Date()); const requestFields=computed(()=>[{label:'Employee',value:props.documentRequest.requester.name},{label:'Position',value:props.documentRequest.requester.position},{label:'Purpose',value:props.documentRequest.purpose,full:true},{label:'Addressed To',value:props.documentRequest.addressed_to},{label:'Receiving Agency',value:props.documentRequest.destination_agency},{label:'Date Needed',value:date(props.documentRequest.needed_at)},{label:'Delivery',value:label(props.documentRequest.delivery_method)},{label:'Copies',value:props.documentRequest.copies},{label:'HR Processor',value:props.documentRequest.processor?.name},{label:'Special Instructions',value:props.documentRequest.special_instructions,full:true}]); const draft=useForm({document_payload:structuredClone(props.documentRequest.document_payload??{employee_name:'',position:'',employee_no:'',appointment_status:'',body:'',service_rows:[],certification_clause:''}),internal_notes:props.documentRequest.internal_notes??''}); const resubmit=useForm({purpose:props.documentRequest.purpose,addressed_to:props.documentRequest.addressed_to??'',destination_agency:props.documentRequest.destination_agency??'',needed_at:props.documentRequest.needed_at??'',delivery_method:props.documentRequest.delivery_method,special_instructions:props.documentRequest.special_instructions??''}); const remarksAction=ref(null),remarks=ref('');
function label(s){return String(s??'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())} function date(v){return v?new Date(v).toLocaleDateString('en-PH',{year:'numeric',month:'long',day:'numeric'}):'—'} function dateTime(v){return v?new Date(v).toLocaleString('en-PH',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—'} function size(v){return v>1048576?`${(v/1048576).toFixed(1)} MB`:`${Math.ceil(v/1024)} KB`} function statusColor(s){return({issued:'green',submitted:'blue',processing:'indigo',pending_ocd_approval:'amber',ready_for_release:'emerald',returned:'orange',ocd_returned:'orange',rejected:'red',cancelled:'slate'})[s]??'slate'} function post(action,data={}){router.post(route(`hr.document-requests.${action}`,props.documentRequest.id),data,{preserveScroll:true})} function saveDraft(){draft.post(route('hr.document-requests.prepare',props.documentRequest.id),{preserveScroll:true})} function addRow(){draft.document_payload.service_rows.push({from:'',to:'',position:'',agency:'',appointment_status:'',government_service:'Yes'})} async function routeToOcd(){const r=await Swal.fire({icon:'question',title:'Route to OCD?',text:'The current frozen draft will be submitted for approval and signature.',showCancelButton:true,confirmButtonText:'Route to OCD'});if(r.isConfirmed)post('route-to-ocd')} async function issue(){let pin=null;if(props.hasPin){const r=await Swal.fire({title:'Sign and issue document',input:'password',inputLabel:'Signing PIN',showCancelButton:true,inputValidator:v=>!v?'PIN is required.':undefined});if(!r.isConfirmed)return;pin=r.value}else{const r=await Swal.fire({icon:'question',title:'Issue this document?',showCancelButton:true});if(!r.isConfirmed)return}post('issue',{pin})} async function cancelRequest(){const r=await Swal.fire({icon:'warning',title:'Cancel this request?',showCancelButton:true,confirmButtonText:'Cancel Request',confirmButtonColor:'#dc2626'});if(r.isConfirmed)post('cancel')} function submitRemarks(){post(remarksAction.value,{remarks:remarks.value});remarksAction.value=null} function resubmitRequest(){resubmit.post(route('hr.document-requests.resubmit',props.documentRequest.id),{preserveScroll:true})}
</script>
<style scoped>.cell{width:100%;min-width:100px;border:1px solid #e2e8f0;border-radius:.375rem;padding:.4rem}</style>
