<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AgencyOutcome extends Model
{
    use HasFactory;

    protected $table = 'agency_org_outcomes';

    protected $fillable = [
        'outcome',
        'sub_outcome',
        'function_type', // ✅ new field
        'fiscal_year',
        'parent_id',
    ];

    /**
     * Model classes whose auto-generated per-assignment WDP identity markers
     * (WorkDistributionPlanClassifier's "<Class>#<id>" / "<Class>#<id>@<tagId>"
     * sub_outcome values) must never be manually selectable — they're private
     * plumbing for one specific teacher's own fallback/materialized row, not
     * reusable framework building blocks. Picking one in a plan/indicator
     * picker silently welds unrelated content onto that teacher's identity.
     */
    public const AUTO_GENERATED_MARKER_SOURCES = [
        \App\Models\FacultyLoading\LoadAssignment::class,
        \App\Models\FacultyLoading\FacultyCommitteeAssignment::class,
    ];

    public function scopeAutoGeneratedMarker($query)
    {
        return $query->where(function ($q) {
            foreach (self::AUTO_GENERATED_MARKER_SOURCES as $class) {
                $q->orWhere('sub_outcome', 'like', addcslashes($class, '\\%_') . '#%');
            }
        });
    }

    // Inverse of scopeAutoGeneratedMarker — kept as its own scope rather than a
    // negation, since SQL's three-valued logic makes `NOT (sub_outcome LIKE ...)`
    // evaluate to NULL (excluded) for rows where sub_outcome IS NULL.
    public function scopeExcludingAutoGeneratedMarker($query)
    {
        return $query->where(function ($q) {
            $q->whereNull('sub_outcome')->orWhere(function ($qq) {
                foreach (self::AUTO_GENERATED_MARKER_SOURCES as $class) {
                    $qq->where('sub_outcome', 'not like', addcslashes($class, '\\%_') . '#%');
                }
            });
        });
    }

    // NULL fiscal_year = applies to all years (legacy rows)
    public function scopeForFiscalYear($query, ?int $year)
    {
        if (! $year) {
            return $query;
        }

        return $query->where(function ($q) use ($year) {
            $q->whereNull('fiscal_year')->orWhere('fiscal_year', $year);
        });
    }

    public function scopeTopLevel($query)
    {
        return $query->whereNull('parent_id');
    }

    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

    public function children()
    {
        return $this->hasMany(self::class, 'parent_id');
    }

    public function performanceIndicators()
    {
        return $this->hasMany(PerformanceIndicator::class, 'agency_outcome_id');
    }

    public function opcrIndicators()
    {
        return $this->hasMany(\App\Models\OPCR\OpcrIndicator::class, 'agency_outcome_id');
    }
}
