<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AgencyOutcome extends Model
{
    use HasFactory;

    protected $table = 'agency_org_outcomes';

    protected $fillable = [
        'outcome',
        'sub_outcome',
        'function_type', // ✅ new field
        'fiscal_year',
        'parent_id',
    ];

    protected $appends = [
        'dost_pillar_names_joined',
        'dost_strategy_names_joined',
        'dost_sub_strategy_descriptions_joined',
    ];

    /**
     * Model classes whose auto-generated per-assignment WDP identity markers
     * (WorkDistributionPlanClassifier's "<Class>#<id>" / "<Class>#<id>@<tagId>"
     * sub_outcome values) must never be manually selectable — they're private
     * plumbing for one specific teacher's own fallback/materialized row, not
     * reusable framework building blocks. Picking one in a plan/indicator
     * picker silently welds unrelated content onto that teacher's identity.
     */
    public const AUTO_GENERATED_MARKER_SOURCES = [
        \App\Models\FacultyLoading\LoadAssignment::class,
        \App\Models\FacultyLoading\FacultyCommitteeAssignment::class,
    ];

    public function scopeAutoGeneratedMarker($query)
    {
        return $query->where(function ($q) {
            foreach (self::AUTO_GENERATED_MARKER_SOURCES as $class) {
                $q->orWhere('sub_outcome', 'like', addcslashes($class, '\\%_') . '#%');
            }
        });
    }

    // Inverse of scopeAutoGeneratedMarker — kept as its own scope rather than a
    // negation, since SQL's three-valued logic makes `NOT (sub_outcome LIKE ...)`
    // evaluate to NULL (excluded) for rows where sub_outcome IS NULL.
    public function scopeExcludingAutoGeneratedMarker($query)
    {
        return $query->where(function ($q) {
            $q->whereNull('sub_outcome')->orWhere(function ($qq) {
                foreach (self::AUTO_GENERATED_MARKER_SOURCES as $class) {
                    $qq->where('sub_outcome', 'not like', addcslashes($class, '\\%_') . '#%');
                }
            });
        });
    }

    // NULL fiscal_year = applies to all years (legacy rows)
    public function scopeForFiscalYear($query, ?int $year)
    {
        if (! $year) {
            return $query;
        }

        return $query->where(function ($q) use ($year) {
            $q->whereNull('fiscal_year')->orWhere('fiscal_year', $year);
        });
    }

    public function scopeTopLevel($query)
    {
        return $query->whereNull('parent_id');
    }

    // True only for the campus-level PSHS Program tags (function_type =
    // "Strategic Functions") — as opposed to the generic Core/Support Function
    // tags used for individual employee IPCR targets, which share this same
    // table. Used to gate OPCR auto-propagation from Performance Indicators.
    public function isStrategicProgram(): bool
    {
        return strtolower(trim((string) $this->function_type)) === 'strategic functions';
    }

    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

    public function children()
    {
        return $this->hasMany(self::class, 'parent_id');
    }

    public function performanceIndicators()
    {
        return $this->hasMany(PerformanceIndicator::class, 'agency_outcome_id');
    }

    public function opcrIndicators()
    {
        return $this->hasMany(\App\Models\OPCR\OpcrIndicator::class, 'agency_outcome_id');
    }

    public function dostPillars()
    {
        return $this->belongsToMany(DostPillar::class, 'dost_pillar_agency_outcomes');
    }

    public function dostStrategies()
    {
        return $this->belongsToMany(DostStrategy::class, 'dost_strategy_agency_outcomes');
    }

    // Pillar/Strategy/Sub-Strategy are tagged many-to-many to a Program (or a
    // specific child under it) in the DOST Strategic Plan module. A child
    // with its own tags uses those (achieving per-indicator specificity);
    // a child with none inherits its parent's, so Programs that were never
    // split into children still display correctly. These are $appends'd
    // (for OPCR's on-screen/print use), so each one guards on
    // relationLoaded() to avoid a lazy-load N+1 anywhere else in the app
    // that serializes an AgencyOutcome without eager-loading
    // dostStrategies.pillar / dostStrategies.subStrategies (and, for the
    // inheritance fallback, parent.dostStrategies.pillar / .subStrategies).
    private function effectiveDostStrategies()
    {
        if (! $this->relationLoaded('dostStrategies')) {
            return null;
        }

        if ($this->dostStrategies->isNotEmpty()) {
            return $this->dostStrategies;
        }

        if ($this->parent_id && $this->relationLoaded('parent') && $this->parent?->relationLoaded('dostStrategies')) {
            return $this->parent->dostStrategies;
        }

        return $this->dostStrategies;
    }

    public function getDostPillarNamesJoinedAttribute(): ?string
    {
        $strategies = $this->effectiveDostStrategies();
        if ($strategies === null) {
            return null;
        }

        $names = $strategies->pluck('pillar.name')->filter()->unique()->values();

        return $names->isEmpty() ? null : $names->implode('; ');
    }

    public function getDostStrategyNamesJoinedAttribute(): ?string
    {
        $strategies = $this->effectiveDostStrategies();
        if ($strategies === null) {
            return null;
        }

        $names = $strategies->pluck('name')->filter()->values();

        return $names->isEmpty() ? null : $names->implode('; ');
    }

    public function getDostSubStrategyDescriptionsJoinedAttribute(): ?string
    {
        $strategies = $this->effectiveDostStrategies();
        if ($strategies === null) {
            return null;
        }

        $descriptions = $strategies->flatMap->subStrategies->pluck('description')->filter()->values();

        return $descriptions->isEmpty() ? null : $descriptions->implode('; ');
    }
}
