<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document Verification — {{ $jobRequest->itjr_no }}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, Helvetica, sans-serif; font-size: 14px; background: #f1f5f9; color: #1e293b; min-height: 100vh; }

    .wrapper { max-width: 640px; margin: 40px auto; padding: 0 16px 60px; }

    .card { background: #fff; border-radius: 12px; border: 1px solid #e2e8f0; padding: 28px 32px; margin-bottom: 16px; }

    .logo { text-align: center; margin-bottom: 20px; }
    .logo .school { font-size: 13px; font-weight: bold; color: #1e293b; line-height: 1.5; }
    .logo .sub    { font-size: 12px; color: #64748b; margin-top: 2px; }

    .doc-title { text-align: center; margin-bottom: 20px; padding-bottom: 16px; border-bottom: 1px solid #e2e8f0; }
    .doc-title h1 { font-size: 16px; font-weight: bold; color: #1e293b; }
    .doc-title .itjr-no { font-size: 22px; font-weight: bold; color: #2563eb; margin-top: 4px; }
    .doc-title .meta    { font-size: 12px; color: #64748b; margin-top: 6px; }

    .section-heading { font-size: 11px; font-weight: bold; color: #64748b; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 12px; }

    .sig-row { display: block; padding: 12px 0; border-bottom: 1px solid #f1f5f9; }
    .sig-row:last-child { border-bottom: none; }

    .sig-stage    { font-size: 10px; font-weight: bold; color: #64748b; text-transform: uppercase; letter-spacing: 0.06em; margin-bottom: 3px; }
    .sig-name     { font-size: 14px; font-weight: bold; color: #1e293b; }
    .sig-position { font-size: 12px; color: #64748b; margin-top: 1px; }
    .sig-date     { font-size: 11px; color: #94a3b8; margin-top: 3px; }

    .badge-valid   { display: inline-block; margin-top: 6px; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: bold; background: #dcfce7; color: #15803d; }
    .badge-invalid { display: inline-block; margin-top: 6px; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: bold; background: #fee2e2; color: #b91c1c; }

    .empty { text-align: center; color: #94a3b8; font-size: 13px; padding: 24px 0; }

    .footer-note { text-align: center; font-size: 11px; color: #94a3b8; margin-top: 20px; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="card">
      <div class="logo">
        <div class="school">PHILIPPINE SCIENCE HIGH SCHOOL SYSTEM</div>
        <div class="school">CARAGA REGION CAMPUS</div>
        <div class="sub">IT Job Request — Digital Signature Verification</div>
      </div>

      <div class="doc-title">
        <h1>IT Job Request Form</h1>
        <div class="itjr-no">{{ $jobRequest->itjr_no }}</div>
        <div class="meta">
          {{ $jobRequest->title ?? $jobRequest->description ?? '—' }}<br>
          Requested by: <strong>{{ $jobRequest->user?->name ?? '—' }}</strong>
        </div>
      </div>

      <div class="section-heading">Digital Signatures</div>

      @if($entries->isEmpty())
        <div class="empty">No digital signatures recorded for this document.</div>
      @else
        @foreach($entries as $entry)
          <div class="sig-row">
            <div class="sig-stage">{{ $entry['stage'] }}</div>
            <div class="sig-name">{{ $entry['signer'] }}</div>
            <div class="sig-position">{{ $entry['position'] }}</div>
            <div class="sig-date">Signed: {{ $entry['signed_at'] }}</div>
            @if($entry['valid'])
              <span class="badge-valid">&#10003; Signature Valid</span>
            @else
              <span class="badge-invalid">&#10007; Signature Invalid</span>
            @endif
          </div>
        @endforeach
      @endif
    </div>

    <div class="footer-note">
      This verification page is generated by the PSHS-CRC Management Information System.<br>
      Tampering with the document will invalidate all digital signatures.
    </div>
  </div>
</body>
</html>
