/**
 * Atlas sidebar navigation data — extracted from AdminLayout.vue (pure data move, no behavior change).
 *
 * Item shape:
 *   { type: 'section', label, roles? }                          — section divider
 *   { label, routeName, href, icon, roles?, permissions? }       — link
 *   { label, icon, roles?, permissions?, children: [...] }       — expandable group
 *
 * Gating: `permissions` (checked via hasPerm()) wins over `roles` when both are present —
 * see the gating logic in AdminLayout.vue.
 */
import {
  HomeIcon,
  UsersIcon,
  DocumentTextIcon,
  ClipboardDocumentListIcon,
  ClipboardDocumentCheckIcon,
  DocumentCheckIcon,
  Cog6ToothIcon,
  ExclamationTriangleIcon,
  UserGroupIcon,
  ChartBarIcon,
  CloudArrowUpIcon,
  ArrowPathIcon,
  ServerStackIcon,
  QueueListIcon,
  ComputerDesktopIcon,
  BookOpenIcon,
  ArchiveBoxIcon,
  WrenchScrewdriverIcon,
  BeakerIcon,
  ShoppingCartIcon,
  CreditCardIcon,
  BanknotesIcon,
  CurrencyDollarIcon,
  HeartIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  HomeModernIcon,
  UserIcon,
  CursorArrowRippleIcon,
  ClockIcon,
  ShieldCheckIcon,
  KeyIcon,
  TableCellsIcon,
  StarIcon,
  TrophyIcon,
  DocumentChartBarIcon,
  AcademicCapIcon,
  CalendarDaysIcon,
  SparklesIcon,
  ScaleIcon,
  CpuChipIcon,
  AdjustmentsHorizontalIcon,
  CheckCircleIcon,
  BuildingLibraryIcon,
  IdentificationIcon,
  UserPlusIcon,
  UserCircleIcon,
  InboxIcon,
  ArrowUpCircleIcon,
  BugAntIcon,
  PuzzlePieceIcon,
  MegaphoneIcon,
  PresentationChartLineIcon,
  FlagIcon,
  ArrowsRightLeftIcon,
} from "@heroicons/vue/24/outline";
import LighthouseIcon from '@/Components/Icons/LighthouseIcon.vue';

export const menuItems = [
  {
    type: "section",
    label: "Administrator",
    roles: ["Administrator"],
  },
  {
    label: "Dashboard",
    routeName: "dashboard",
    href: route("dashboard"),
    icon: HomeIcon,
  },
  {
    label: "SOS Emergency",
    icon: ExclamationTriangleIcon,
    permissions: ["sos.respond", "sos.manage"],
    children: [
      {
        label: "Command Center",
        routeName: "sos.index",
        href: route("sos.index"),
        icon: ExclamationTriangleIcon,
        permissions: ["sos.respond"],
      },
      {
        label: "Settings",
        routeName: "sos.settings.index",
        href: route("sos.settings.index"),
        icon: Cog6ToothIcon,
        permissions: ["sos.manage"],
      },
    ],
  },
  {
    label: "ManCom Deck",
    routeName: "executive.dashboard",
    href: route("executive.dashboard"),
    icon: PresentationChartLineIcon,
    permissions: ["executive.dashboard.view"],
  },
  {
    label: "Approvals",
    routeName: "approvals.inbox",
    href: route("approvals.inbox"),
    icon: InboxIcon,
    roles: ["Administrator", "DivisionChief", "OCD", "GSU Head", "FAD Chief", "HR", "AUH"],
  },
  {
    label: "Data Management",
    icon: UsersIcon,
    roles: ["Administrator"],
    children: [
      {
        label: "All Users",
        routeName: "users.index",
        href: route("users.index"),
        icon: UserGroupIcon,
        permissions: ["users.view"],
      },
      {
        label: "Inactive Users",
        routeName: "users.inactive",
        href: route("users.inactive"),
        icon: UserGroupIcon,
        permissions: ["hr.employees.manage"],
      },
      {
        label: "User Roles",
        routeName: "roles.index",
        href: route("roles.index"),
        icon: CursorArrowRippleIcon,
        permissions: ["roles.assign"],
      },
      {
        label: "Roles & Permissions",
        routeName: "admin.roles",
        href: "/admin/roles",
        icon: ShieldCheckIcon,
        permissions: ["roles.assign"],
      },
      {
        label: "Permissions",
        routeName: "admin.permissions",
        href: "/admin/permissions",
        icon: KeyIcon,
        permissions: ["roles.assign"],
      },
      {
        label: "Assign Roles",
        routeName: "admin.assign-roles",
        href: "/admin/assign-roles",
        icon: UserGroupIcon,
        permissions: ["roles.assign"],
      },
      {
        label: "Division",
        routeName: "roles.divisions",
        href: route("roles.divisions"),
        icon: CursorArrowRippleIcon,
        permissions: ["roles.assign"],
      },
      {
        label: "Office/Unit",
        routeName: "offices.index",
        href: route("offices.index"),
        icon: HomeIcon,
        permissions: ["roles.assign"],
      },
      {
        label: "Org Structure",
        routeName: "hr.org.index",
        href: route("hr.org.index"),
        icon: BuildingLibraryIcon,
        permissions: ["org.view"],
      },
      {
        label: "Buildings",
        routeName: "buildings.index",
        href: route("buildings.index"),
        icon: HomeModernIcon,
        permissions: ["roles.assign"],
      },
      {
        label: "Campus",
        routeName: "campuses.index",
        href: route("campuses.index"),
        icon: HomeIcon,
        permissions: ["roles.assign"],
      },
      {
        label: "Rooms",
        routeName: "rooms.index",
        href: route("rooms.index"),
        icon: HomeIcon,
        permissions: ["roles.assign"],
      },
      {
        label: "Vehicle",
        routeName: "vehicles.index",
        href: route("vehicles.index"),
        icon: ArchiveBoxIcon,
        permissions: ["vehicles.manage"],
      },
      {
        label: "Facility",
        routeName: "facilities.index",
        href: route("facilities.index"),
        icon: ArchiveBoxIcon,
        permissions: ["facilities.manage"],
      },
      
    ],
  },
  {
    label: "MIS",
    icon: ServerStackIcon,
    roles: ["Administrator", "Faculty", "Staff", "DivisionChief", "OCD", "HR", "MIS", "Payroll Officer", "HRMPSB", "Recruitment Officer", "PMT", "Registrar", "Records", "Librarian", "Nurse", "Guidance", "GSU Head", "InformationOfficer", "Dorm Manager", "CID Chief"],
    children: [
      {
        label: "MIS Dashboard",
        routeName: "mis.dashboard",
        href: route("mis.dashboard"),
        icon: ChartBarIcon,
        permissions: ["it.requests.manage"],
      },
      {
        label: "CSM Feedback",
        routeName: "csm.dashboard",
        href: route("csm.dashboard"),
        icon: StarIcon,
        permissions: ["it.requests.manage"],
      },
      {
        label: "Error Reports",
        routeName: "error-reports.index",
        href: route("error-reports.index"),
        icon: BugAntIcon,
        permissions: ["error-reports.manage"],
      },
      {
        label: "My Error Reports",
        routeName: "error-reports.my",
        href: route("error-reports.my"),
        icon: BugAntIcon,
      },
      {
        label: "IT Job Requests",
        routeName: "jobrequests.index",
        href: route("jobrequests.index"),
        icon: ComputerDesktopIcon,
        permissions: ["it.requests.view"],
      },
      {
        label: "Equipment Inventory",
        routeName: "ict-equipments.index",
        href: route("ict-equipments.index"),
        icon: QueueListIcon,
        permissions: ["it.equipment.view"],
      },
      {
        label: "Computer Laboratories",
        routeName: "computer-labs.index",
        href: route("computer-labs.index"),
        icon: ComputerDesktopIcon,
        permissions: ["it.equipment.view", "computer_labs.book", "computer_labs.manage"],
      },
      {
        label: "Sentinel",
        routeName: "atlas-sentinel.health-dashboard",
        href: route("atlas-sentinel.health-dashboard"),
        icon: ChartBarIcon,
        permissions: ["it.equipment.view"],
      },
      {
        label: "Remote Help",
        routeName: "atlas-sentinel.remote-help.index",
        href: route("atlas-sentinel.remote-help.index"),
        icon: CursorArrowRippleIcon,
        permissions: ["atlas.sentinel.remote-help.manage"],
      },
      {
        label: "Device Backups",
        routeName: "atlas-sentinel.backups.index",
        href: route("atlas-sentinel.backups.index"),
        icon: CloudArrowUpIcon,
        permissions: ["it.equipment.view"],
      },
      {
        label: "Module Monitor",
        routeName: "atlas.modules.index",
        href: route("atlas.modules.index"),
        icon: CpuChipIcon,
        permissions: ["atlas.modules.view"],
      },
      {
        label: "WatchTower",
        routeName: "atlas.watchtower.index",
        href: route("atlas.watchtower.index"),
        icon: LighthouseIcon,
        permissions: ["atlas.watchtower.view"],
      },
      {
        label: "Workspace Sync",
        routeName: "atlas.workspace-sync.index",
        href: route("atlas.workspace-sync.index"),
        icon: ArrowPathIcon,
        permissions: ["atlas.workspace-sync.view"],
      },
      {
        label: "PMS",
        routeName: "ict-pms.index",
        href: route("ict-pms.index"),
        icon: ClockIcon,
        permissions: ["it.equipment.view"],
      },

    ],
  },
  {
    label: "Administration",
    icon: DocumentTextIcon,
    // No group-level permission gate: Announcements is open to every
    // authenticated user; the other children gate themselves.
    children: [
      {
        label: "Issuances",
        routeName: "issuances.index",
        href: route("issuances.index"),
        icon: DocumentTextIcon,
        permissions: ["issuances.manage"],
      },
      {
        label: "OED Issuances",
        routeName: "km.index",
        href: route("km.index"),
        icon: BookOpenIcon,
        permissions: ["km.view"],
      },
      {
        label: "Announcements",
        routeName: "announcements.index",
        href: route("announcements.index"),
        icon: MegaphoneIcon,
      },
      {
        label: "Certificate of Appearance",
        routeName: "coa.index",
        href: route("coa.index"),
        icon: IdentificationIcon,
        permissions: ["coa.manage"],
      },
    ],
  },
  {
    type: "section",
    label: "Finance & Administration",
    roles: ["Administrator", "Faculty", "Staff", "Student", "Parent"],
  },
  
  
    {
      label: "Human Resource",
      icon: UserGroupIcon,
      roles: ["Administrator", "HR", "Faculty", "Staff", "DivisionChief", "OCD"],
      children: [
      {
        label: "HR Dashboard",
        routeName: "hr.dashboard",
        href: route("hr.dashboard"),
        icon: ChartBarIcon,
        permissions: ["hr.dashboard.view"],
      },
      {
        label: "My PDS",
        routeName: "pds.my",
        href: route("pds.my"),
        icon: ClipboardDocumentListIcon,
        permissions: ["hr.pds.view"],
      },
      {
        label: "PDS Records",
        routeName: "pds.index",
        href: route("pds.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["pds.view_all"],
      },
      {
        label: "Employees",
        routeName: "hr.employees.index",
        href: route('hr.employees.index'),
        icon: UserIcon,
        permissions: ["hr.employees.manage"],
      },
      {
        label: "201 Files",
        routeName: "hr.twoohone.index",
        href: route('hr.twoohone.index'),
        icon: ArchiveBoxIcon,
        permissions: ["hr.employee.view"],
      },
      {
        label: "Service Records",
        routeName: "hr.service-records.index",
        href: route('hr.service-records.index'),
        icon: IdentificationIcon,
        permissions: ["hr.service-records.view"],
      },
      {
        label: "My Service Record",
        routeName: "hr.service-records.my",
        href: route('hr.service-records.my'),
        icon: DocumentCheckIcon,
        permissions: ["hr.service-records.view-own"],
      },
      {
        label: "My Document Requests",
        routeName: "hr.document-requests.index",
        href: route('hr.document-requests.index'),
        icon: DocumentTextIcon,
        permissions: ["hr.document-requests.file"],
      },
      {
        label: "Document Request Processing",
        routeName: "hr.document-requests.manage",
        href: route('hr.document-requests.manage'),
        icon: QueueListIcon,
        permissions: ["hr.document-requests.process"],
      },
      {
        label: "Work Schedules",
        routeName: "hr.schedules.index",
        href: route("hr.schedules.index"),
        icon: ClockIcon,
        permissions: ["hr.schedule.manage"],
      },
      {
        label: "My Work Schedule",
        routeName: "hr.schedules.my",
        href: route("hr.schedules.my"),
        icon: ClockIcon,
      },
      
      {
        label: "Gate Pass",
        routeName: "gatepass.index",
        href: route('gatepass.index'),
        icon: ClipboardDocumentListIcon,
        permissions: ["hr.gatepass.view"],
      },
      {
        label: "Leave Applications",
        routeName: "hr.leave.index",
        href: route('hr.leave.index'),
        icon: ClipboardDocumentListIcon,
        permissions: ["hr.leave.file", "hr.leave.view"],
      },
      {
        label: "Substitutions",
        routeName: "hr.substitutions.index",
        href: route('hr.substitutions.index'),
        icon: ArrowsRightLeftIcon,
        permissions: ["hr.leave.file", "hr.leave.view"],
      },
      {
        label: "My Leave Credits",
        routeName: "hr.leave-credits.my",
        href: route('hr.leave-credits.my'),
        icon: CreditCardIcon,
        permissions: ["hr.leave.file", "hr.leave.credits.view"],
      },
      {
        label: "Leave Credit Ledger",
        routeName: "hr.reports.leave-credits.ledger",
        href: route('hr.reports.leave-credits.ledger'),
        icon: DocumentChartBarIcon,
        permissions: ["hr.leave.approve"],
      },
      {
        label: "Monthly Accrual Report",
        routeName: "hr.reports.leave-credits.accrual",
        href: route('hr.reports.leave-credits.accrual'),
        icon: DocumentChartBarIcon,
        permissions: ["hr.leave.approve"],
      },
      {
        label: "Leave Utilization Report",
        routeName: "hr.reports.leave-credits.utilization",
        href: route('hr.reports.leave-credits.utilization'),
        icon: ChartBarIcon,
        permissions: ["hr.leave.approve"],
      },
      {
        label: "Initialize Leave Credits",
        routeName: "hr.leave-credits.initialize",
        href: route('hr.leave-credits.initialize'),
        icon: ClipboardDocumentListIcon,
        permissions: ["hr.leave.approve"],
      },
      {
        label: "Adjust Leave Credits",
        routeName: "hr.leave-credits.adjust",
        href: route('hr.leave-credits.adjust'),
        icon: AdjustmentsHorizontalIcon,
        permissions: ["hr.leave.approve"],
      },
      {
        label: "Service Credit Approval",
        routeName: "hr.leave-credits.service-credits",
        href: route('hr.leave-credits.service-credits'),
        icon: CheckCircleIcon,
        permissions: ["hr.leave.approve"],
      },
      {
        label: "My DTR",
        routeName: "hr.my-dtr.index",
        href: route('hr.my-dtr.index'),
        icon: ClockIcon,
        permissions: ["dtr.view_own"],
      },
      {
        label: "DTR Records",
        routeName: "hr.dtr.index",
        href: route('hr.dtr.index'),
        icon: TableCellsIcon,
        permissions: ["hr.dtr.view"],
      },
      {
        label: "Holidays",
        routeName: "hr.holidays.index",
        href: route('hr.holidays.index'),
        icon: StarIcon,
        permissions: ["hr.employees.manage"],
      },
      {
        label: "Biometric Logs",
        routeName: "hr.biometric.index",
        href: route('hr.biometric.index'),
        icon: ClockIcon,
        permissions: ["hr.biometric.manage"],
      },
      {
        label: "Work From Home",
        routeName: "hr.wfh.index",
        href: route('hr.wfh.index'),
        icon: HomeModernIcon,
        permissions: ["wfh.view"],
      },
      {
        label: "WFH Monitoring",
        routeName: "hr.wfh.monitor.page",
        href: route('hr.wfh.monitor.page'),
        icon: ChartBarIcon,
        permissions: ["wfh.monitor"],
      },
      {
        label: "Online Time Punches",
        routeName: "hr.online-punch.index",
        href: route('hr.online-punch.index'),
        icon: IdentificationIcon,
        permissions: ["hr.online-punch.record"],
      },
      {
        label: "Online Punch Monitoring",
        routeName: "hr.online-punch.monitor.page",
        href: route('hr.online-punch.monitor.page'),
        icon: ChartBarIcon,
        permissions: ["hr.online-punch.monitor"],
      },
      {
        label: "Face Enrollment",
        routeName: "hr.face-enrollment.self",
        href: route('hr.face-enrollment.self'),
        icon: UserIcon,
        permissions: ["hr.face-enrollment.self"],
      },
      {
        label: "Face Enrollment Review",
        routeName: "hr.face-enrollment.index",
        href: route('hr.face-enrollment.index'),
        icon: ShieldCheckIcon,
        permissions: ["hr.face-enrollment.manage"],
      },
    ],
  },

  {
    label: "SALN",
    icon: DocumentChartBarIcon,
    roles: [],
    permissions: ["saln.create", "saln.view_all", "saln.review"],
    children: [
      {
        label: "My SALN",
        routeName: "saln.index",
        href: route("saln.index"),
        icon: DocumentTextIcon,
        roles: [],
        permissions: ["saln.create"],
      },
      {
        label: "For Review",
        routeName: "saln.review.index",
        href: route("saln.review.index"),
        icon: ClipboardDocumentListIcon,
        roles: [],
        permissions: ["saln.review"],
      },
      {
        label: "All SALN Records",
        routeName: "saln.hr.index",
        href: route("saln.hr.index"),
        icon: TableCellsIcon,
        roles: [],
        permissions: ["saln.view_all"],
      },
      {
        label: "Annual Report",
        routeName: "saln.hr.reports.annual",
        href: route("saln.hr.reports.annual"),
        icon: ChartBarIcon,
        roles: [],
        permissions: ["saln.view_all"],
      },
    ],
  },

  {
    label: "Payroll",
    icon: BanknotesIcon,
    roles: ["Administrator", "HR", "Payroll Officer", "Faculty", "Staff", "DivisionChief"],
    children: [
      {
        label: "Payroll Runs",
        routeName: "payroll.index",
        href: route('payroll.index'),
        icon: CurrencyDollarIcon,
        permissions: ["payroll.view"],
      },
      {
        label: "Allowance Types",
        routeName: "payroll.allowances.index",
        href: route('payroll.allowances.index'),
        icon: CurrencyDollarIcon,
        permissions: ["payroll.manage"],
      },
      {
        label: "Payroll Upload",
        routeName: "payroll.cashier.index",
        href: route('payroll.cashier.index'),
        icon: DocumentChartBarIcon,
        permissions: ["payroll.upload", "payroll.view_all"],
      },
      {
        label: "My Payslips",
        routeName: "payroll.my-payslips.index",
        href: route('payroll.my-payslips.index'),
        icon: DocumentTextIcon,
      },
    ],
  },

  {
    label: "Performance Mngmt",
    icon: UserGroupIcon,
    roles: ["Administrator", "Faculty", "Staff", "HR", "DivisionChief", "OCD", "PMT", "PMRater"],
    children: [
      {
        label: "DOST Strategic Plan",
        routeName: "dost-strategic-plan.index",
        href: route("dost-strategic-plan.index"),
        icon: FlagIcon,
        permissions: ["ipcr.view"],
      },
      {
        label: "Agency Org Outcome",
        routeName: "outcome.index",
        href: route("outcome.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["ipcr.view"],
      },
      {
        label: "Performance Indicators",
        routeName: "performanceindicator.index",
        href: route("performanceindicator.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["ipcr.view"],
      },
      {
        label: "Work Distribution Plan",
        routeName: "workdistribution.index",
        href: route("workdistribution.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["ipcr.view"],
      },
      {
        label: "IPCR",
        routeName: "employee-ipcr.index",
        href: route("employee-ipcr.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["ipcr.view"],
      },
      {
        label: "Committees",
        routeName: "pm-committees.index",
        href: route("pm-committees.index"),
        icon: UserGroupIcon,
        permissions: ["accomplishments.view"],
      },
      {
        label: "Special Assignments",
        routeName: "pm-special-assignments.index",
        href: route("pm-special-assignments.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["accomplishments.view"],
      },
      {
        label: "My Accomplishments",
        routeName: "my-accomplishments.index",
        href: route("my-accomplishments.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["accomplishments.view"],
      },
      {
        label: "My Unit",
        routeName: "my-unit-ipcr.index",
        href: route("my-unit-ipcr.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["ipcr.view"],
      },
      {
        label: "My Division",
        routeName: "division-chief-ipcr.index",
        href: route("division-chief-ipcr.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["ipcr.approve"],
      },
      {
        label: "HR IPCR Review",
        routeName: "hr-ipcr.index",
        href: route("hr-ipcr.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["ipcr.monitor"],
      },
      {
        label: "PMT Review",
        routeName: "pmt-ipcr.index",
        href: route("pmt-ipcr.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["ipcr.approve"],
      },
      {
        label: "Rating Periods",
        routeName: "ipcr-rating-periods.index",
        href: route("ipcr-rating-periods.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["ipcr.admin"],
      },
      {
        label: "IPCR Monitoring (All Stages)",
        routeName: "admin-ipcr.index",
        href: route("admin-ipcr.index"),
        icon: ClipboardDocumentListIcon,
        roles: ["Administrator"],
      },
    ],
  },
  {
    label: "Recruitment",
    icon: UserGroupIcon,
    roles: ["Administrator", "HR", "OCD"],
    permissions: ["recruitment.view"],
    children: [
      {
        label: "Job Items",
        routeName: "recruitment.job-items.index",
        href: route("recruitment.job-items.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["recruitment.manage"],
      },
      {
        label: "Applicant Pool",
        routeName: "recruitment.applicants.index",
        href: route("recruitment.applicants.index"),
        icon: UsersIcon,
        permissions: ["recruitment.manage"],
      },
      {
        label: "Applications",
        routeName: "recruitment.applications.index",
        href: route("recruitment.applications.index"),
        icon: QueueListIcon,
        permissions: ["recruitment.evaluate"],
      },
      {
        label: "Placements & Onboarding",
        routeName: "recruitment.placements.index",
        href: route("recruitment.placements.index"),
        icon: HomeModernIcon,
        permissions: ["recruitment.onboarding"],
      },
      {
        label: "Type Configuration",
        routeName: "recruitment.types.index",
        href: route("recruitment.types.index"),
        icon: ShieldCheckIcon,
        permissions: ["recruitment.manage"],
      },
      {
        label: "HRMPSB Members",
        routeName: "recruitment.hrmpsb.index",
        href: route("recruitment.hrmpsb.index"),
        icon: UsersIcon,
        permissions: ["recruitment.manage"],
      },
      {
        label: "Reports",
        routeName: "recruitment.reports.index",
        href: route("recruitment.reports.index"),
        icon: ChartBarIcon,
        permissions: ["recruitment.view"],
      },
      {
        label: "Salary Grade Table",
        routeName: "salary-grades.index",
        href: route("salary-grades.index"),
        icon: TableCellsIcon,
        permissions: ["recruitment.view"],
      },
    ],
  },
  {
    label: "Learning & Devt", 
    icon: BookOpenIcon,
    roles: ["Administrator", "HR"],
    permissions: ["lnd.view"],
    children: [
      {
        label: "Learning Programs",
        routeName: "lnd.programs.index",
        href: route("lnd.programs.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["lnd.view"],
      },
      {
        label: "Training Sessions",
        routeName: "lnd.sessions.index",
        href: route("lnd.sessions.index"),
        icon: QueueListIcon,
        permissions: ["lnd.view"],
      },
      {
        label: "Training Needs (TNA)",
        routeName: "lnd.tna.index",
        href: route("lnd.tna.index"),
        icon: ChartBarIcon,
        permissions: ["lnd.view"],
      },
      {
        label: "IDP",
        routeName: "lnd.idp.index",
        href: route("lnd.idp.index"),
        icon: DocumentTextIcon,
        permissions: ["lnd.view"],
      },
      {
        label: "My Trainings",
        routeName: "lnd.my-trainings",
        href: route("lnd.my-trainings"),
        icon: UserIcon,
        permissions: ["lnd.view"],
      },
      {
        label: "My IDP",
        routeName: "lnd.my-idp",
        href: route("lnd.my-idp"),
        icon: ClockIcon,
        permissions: ["lnd.view"],
      },
    ],
  },
  {
    label: "Rewards & Recog",
    icon: StarIcon,
    permissions: ["rewards.view"],
    children: [
      {
        label: "Dashboard",
        routeName: "rewards.dashboard",
        href: route("rewards.dashboard"),
        icon: ChartBarIcon,
        permissions: ["rewards.view"],
      },
      {
        label: "Nominations",
        routeName: "rewards.nominations.index",
        href: route("rewards.nominations.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["rewards.view"],
      },
      {
        label: "Evaluation Panel",
        routeName: "rewards.evaluations.panel",
        href: route("rewards.evaluations.panel"),
        icon: QueueListIcon,
        permissions: ["rewards.evaluate"],
      },
      {
        label: "Approvals",
        routeName: "rewards.approvals.index",
        href: route("rewards.approvals.index"),
        icon: DocumentTextIcon,
        permissions: ["rewards.approve"],
      },
      {
        label: "Award Types",
        routeName: "rewards.types.index",
        href: route("rewards.types.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["rewards.manage"],
      },
      {
        label: "My Recognitions",
        routeName: "rewards.my-recognitions",
        href: route("rewards.my-recognitions"),
        icon: UserIcon,
        permissions: ["rewards.view"],
      },
      {
        label: "Reports",
        routeName: "rewards.reports",
        href: route("rewards.reports"),
        icon: ChartBarIcon,
        permissions: ["rewards.view"],
      },
    ],
  },
  
  {
    label: "Records Management",
    icon: ArchiveBoxIcon,
    roles: ["Administrator", "Records", "Faculty", "Staff", "GSU Head", "DivisionChief", "OCD"],
    children: [
      {
        label: "Issuances",
        routeName: "issuances.index",
        href: route("issuances.index"),
        icon: DocumentTextIcon,
        permissions: ["issuances.view"],
      },
      {
        label: "Document Tracking",
        routeName: "document-tracking.index",
        href: route("document-tracking.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["documents.view"],
      },
      {
        label: "Messengerial",
        routeName: "messengerial.index",
        href: route("messengerial.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["messengerial.view"],
      },
    ],
  },
  {
    label: "Travel",
    icon: CalendarDaysIcon,
    roles: ["Administrator", "Faculty", "Staff", "DivisionChief", "OCD", "FAD Chief", "Budget Officer", "Bookkeeper", "Accountant", "Cashier"],
    children: [
      {
        label: "Dashboard",
        routeName: "travel.dashboard",
        href: route("travel.dashboard"),
        icon: ChartBarIcon,
        permissions: ["travel.view"],
      },
      {
        label: "Travel Requests",
        routeName: "travel.index",
        href: route("travel.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["travel.view"],
      },
    ],
  },
  {
    label: "General Services",
    icon: WrenchScrewdriverIcon,
    roles: ["Administrator", "Faculty", "Staff", "GSU Head", "DivisionChief", "OCD", "FAD Chief"],
    children: [
      {
        label: "Dashboard",
        routeName: "general-services.dashboard",
        href: route("general-services.dashboard"),
        icon: ChartBarIcon,
        roles: ["Administrator", "GSU Head", "DivisionChief", "OCD", "FAD Chief"],
      },
      {
        label: "Vehicle Request",
        routeName: "vehicle-requests.index",
        href: route("vehicle-requests.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["vehicles.view"],
      },
      {
        label: "Facility Request",
        routeName: "facility-requests.index",
        href: route("facility-requests.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["facilities.view"],
      },
      {
        label: "Request for Services",
        routeName: "service-requests.index",
        href: route('service-requests.index'),
        icon: ClipboardDocumentListIcon,
        permissions: ["facilities.view"],
      },
      {
        label: "Work Request",
        routeName: "work-requests.index",
        href: route('work-requests.index'),
        icon: ClipboardDocumentListIcon,
        permissions: ["facilities.view"],
      },
      // No roles/permissions — every authenticated employee can report and
      // browse the found-items board; GSU actions are gated in-page.
      {
        label: "Lost & Found",
        routeName: "lost-found.index",
        href: route("lost-found.index"),
        icon: ArchiveBoxIcon,
      },
    ],
  },
  {
    label: "Procurement",
    icon: ShoppingCartIcon,
    roles: ["Administrator", "Faculty", "Staff", "GSU Head", "DivisionChief", "OCD", "Budget Officer", "Bookkeeper", "Accountant", "Procurement Officer", "FAD Chief"],
    children: [
      {
        label: "PPMP",
        routeName: "ppmp.index",
        href: "/ppmp",
        icon: DocumentTextIcon,
        permissions: ["ppmp.create", "ppmp.view_all"],
      },
      {
        label: "PPMP Dashboard",
        routeName: "ppmp.dashboard",
        href: "/ppmp/dashboard",
        icon: DocumentTextIcon,
        permissions: ["ppmp.view_all"],
      },
      {
        label: "PS-DBM Catalogue",
        routeName: "ppmp.catalogue.index",
        href: "/ppmp/catalogue",
        icon: DocumentTextIcon,
        permissions: ["ppmp.consolidate"],
      },
      {
        label: "Annual Procurement Plan",
        routeName: "ppmp.app.index",
        href: "/ppmp/app",
        icon: DocumentTextIcon,
        permissions: ["ppmp.consolidate"],
      },
      {
        label: "Purchase Requests",
        routeName: "procurements.index",
        href: route("procurements.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["procurement.pr.view", "procurement.pr.create", "procurement.view"],
      },
      {
        label: "RFQ",
        routeName: "rfq.index",
        href: route("rfq.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["procurement.rfq.view", "procurement.rfq.create", "procurement.rfq.evaluate", "procurement.rfq.award"],
      },
      {
        label: "Purchase Orders",
        routeName: "po.index",
        href: route("po.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["procurement.po.view", "procurement.po.create", "procurement.po.review", "procurement.po.sign"],
      },
      {
        label: "ORS",
        routeName: "ors.index",
        href: route("ors.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["procurement.ors.view", "procurement.ors.create"],
      },
      {
        label: "Disbursement Vouchers",
        routeName: "dv.index",
        href: route("dv.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["procurement.dv.view", "procurement.dv.create"],
      },
    ],
  },
  {
    label: "Supply & Property",
    icon: ArchiveBoxIcon,
    permissions: ["supply.view", "supply.receive", "supply.issue", "supply.manage", "property.view", "property.manage", "property.transfer", "property.reports", "property.dispose", "work-orders.view", "work-orders.manage"],
    children: [
      {
        label: "Item Catalog",
        routeName: "supply.items.index",
        href: route("supply.items.index"),
        icon: ArchiveBoxIcon,
        permissions: ["supply.view", "supply.manage"],
      },
      {
        label: "IAR",
        routeName: "supply.iar.index",
        href: route("supply.iar.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["supply.receive", "supply.manage"],
      },
      {
        label: "RIS",
        routeName: "supply.ris.index",
        href: route("supply.ris.index"),
        icon: QueueListIcon,
        permissions: ["supply.view", "supply.issue", "supply.manage"],
      },
      {
        label: "Stock Card",
        routeName: "supply.stock-card.index",
        href: route("supply.stock-card.index"),
        icon: ArchiveBoxIcon,
        permissions: ["supply.view", "supply.manage"],
      },
      {
        label: "Property Items",
        routeName: "property.items.index",
        href: route("property.items.index"),
        icon: ArchiveBoxIcon,
        permissions: ["property.view", "property.manage"],
      },
      {
        label: "ICS",
        routeName: "property.ics.index",
        href: route("property.ics.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["property.view", "property.manage"],
      },
      {
        label: "PAR",
        routeName: "property.par.index",
        href: route("property.par.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["property.view", "property.manage"],
      },
      {
        label: "Transfers",
        routeName: "property.transfers.index",
        href: route("property.transfers.index"),
        icon: QueueListIcon,
        permissions: ["property.view", "property.transfer", "property.manage"],
      },
      {
        label: "Reports",
        routeName: "property.reports.index",
        href: route("property.reports.index"),
        icon: TableCellsIcon,
        permissions: ["property.reports"],
      },
      {
        label: "Work Orders",
        routeName: "property.work-orders.index",
        href: route("property.work-orders.index"),
        icon: WrenchScrewdriverIcon,
        permissions: ["work-orders.view", "work-orders.manage"],
      },
      {
        label: "Disposal",
        routeName: "property.disposal.index",
        href: route("property.disposal.index"),
        icon: ArchiveBoxIcon,
        permissions: ["property.dispose"],
      },
    ],
  },
  {
    label: "Activity Management",
    icon: CalendarDaysIcon,
    roles: ["Administrator", "Faculty", "Staff", "Student", "HR", "DivisionChief", "OCD"],
    children: [
      {
        label: "Activities",
        routeName: "ams.activities.index",
        href: route("ams.activities.index"),
        icon: ClipboardDocumentListIcon,
        roles: [],
        permissions: ["activities.manage", "activities.view_all"],
      },
      {
        label: "My Activities",
        routeName: "ams.my-activities.index",
        href: route("ams.my-activities.index"),
        icon: UserCircleIcon,
      },
      {
        label: "Monitor",
        routeName: "ams.monitor.index",
        href: route("ams.monitor.index"),
        icon: ChartBarIcon,
        permissions: ["activities.monitor", "activities.evaluation_committee"],
      },
    ],
  },
  // {
  //   label: "Supply & Property",
  //   icon: ShoppingCartIcon,
  //   roles: ["Administrator", "Faculty", "Staff", "Student", "Parent"],
  //   children: [
  //     {
  //       label: "PDS",
  //       routeName: null,
  //       href: "#",
  //       icon: ClipboardDocumentListIcon,
  //       roles: ["Administrator", "Faculty", "Staff", "Student", "Parent"],
  //     },
  //   ],
  // },
  // {
  //   label: "Accounting",
  //   icon: CreditCardIcon,
  //   roles: ["Administrator", "Faculty", "Staff", "Student", "Parent"],
  //   children: [
  //     {
  //       label: "PDS",
  //       routeName: null,
  //       href: "#",
  //       icon: ClipboardDocumentListIcon,
  //       roles: ["Administrator", "Faculty", "Staff", "Student", "Parent"],
  //     },
  //   ],
  // },
  // {
  //   label: "Budget",
  //   icon: BanknotesIcon,
  //   roles: ["Administrator", "Faculty", "Staff", "Student", "Parent"],
  //   children: [
  //     {
  //       label: "PDS",
  //       routeName: null,
  //       href: "#",
  //       icon: ClipboardDocumentListIcon,
  //       roles: ["Administrator", "Faculty", "Staff", "Student", "Parent"],
  //     },
  //   ],
  // },
  // {
  //   label: "Cashier",
  //   icon: CurrencyDollarIcon,
  //   roles: ["Administrator", "Faculty", "Staff", "Student", "Parent"],
  //   children: [
  //     {
  //       label: "PDS",
  //       routeName: null,
  //       href: "#",
  //       icon: ClipboardDocumentListIcon,
  //       roles: ["Administrator", "Faculty", "Staff", "Student", "Parent"],
  //     },
  //   ],
  // },
  {
    type: "section",
    label: "Curriculum & Instruction",
    roles: ["Administrator", "Faculty", "Staff", "DivisionChief", "OCD"],
  },

  {
    label: "CID Dashboard",
    routeName: "cid.dashboard.index",
    href: route("cid.dashboard.index"),
    icon: ChartBarIcon,
    permissions: ["cid.dashboard"],
  },

  {
    label: "Competitions & Winnings",
    routeName: "cid.competitions.index",
    href: route("cid.competitions.index"),
    icon: TrophyIcon,
    permissions: ["cid.competitions.view", "cid.competitions.manage"],
  },

  {
    label: "Alternative Learning Program",
    routeName: "alp.index",
    href: route("alp.index"),
    icon: SparklesIcon,
    permissions: ["alp.view", "alp.manage", "alp.advise", "alp.coordinate", "alp.registrar-certify", "alp.approve", "alp.reports", "alp.audit"],
  },

  {
    label: "Science Laboratory",
    icon: BeakerIcon,
    permissions: ["lab.view", "lab.request", "lab.manage"],
    children: [
      {
        label: "Lab Dashboard",
        routeName: "science-lab.dashboard",
        href: route("science-lab.dashboard"),
        icon: ChartBarIcon,
        permissions: ["lab.view", "lab.request", "lab.manage"],
      },
      {
        label: "Request & Reservation",
        routeName: "science-lab.requests.index",
        href: route("science-lab.requests.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["lab.request", "lab.manage"],
      },
      {
        label: "Laboratories",
        routeName: "science-lab.laboratories.index",
        href: route("science-lab.laboratories.index"),
        icon: BuildingLibraryIcon,
        permissions: ["lab.manage"],
      },
      {
        label: "Equipment Registry",
        routeName: "science-lab.equipment.index",
        href: route("science-lab.equipment.index"),
        icon: WrenchScrewdriverIcon,
        permissions: ["lab.manage"],
      },
      {
        label: "Inventory",
        routeName: "science-lab.inventory.index",
        href: route("science-lab.inventory.index"),
        icon: ArchiveBoxIcon,
        permissions: ["lab.manage"],
      },
      {
        label: "Maintenance",
        routeName: "science-lab.maintenance.index",
        href: route("science-lab.maintenance.index"),
        icon: WrenchScrewdriverIcon,
        permissions: ["lab.manage"],
      },
      {
        label: "Calibration",
        routeName: "science-lab.calibration.index",
        href: route("science-lab.calibration.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["lab.manage"],
      },
      {
        label: "Safety",
        routeName: "science-lab.safety.index",
        href: route("science-lab.safety.index"),
        icon: ShieldCheckIcon,
        permissions: ["lab.manage"],
      },
      {
        label: "Waste Management",
        routeName: "science-lab.waste.index",
        href: route("science-lab.waste.index"),
        icon: ArchiveBoxIcon,
        permissions: ["lab.manage"],
      },
    ],
  },

  {
    label: "Class Records",
    icon: TableCellsIcon,
    roles: ["Administrator", "Faculty", "CID Chief", "OCD"],
    orRoles: ["AUH"],
    children: [
      {
        label: "My Class Records",
        routeName: "class-records.page.index",
        href: route("class-records.page.index"),
        icon: ClipboardDocumentListIcon,
        roles: ["Administrator", "Faculty", "CID Chief", "OCD"],
      },
      {
        label: "Weekly Assessment Tracker",
        routeName: "class-records.wat.index",
        href: route("class-records.wat.index"),
        icon: CalendarDaysIcon,
        roles: ["Administrator", "Faculty", "CID Chief", "OCD"],
      },
      {
        // Personal, cross-section view of a faculty member's own plotted
        // load — distinct from the section-scoped tracker above, which is
        // used by coordinators/reviewers for one section at a time.
        label: "My WAT Tracker",
        routeName: "class-records.wat.my-tracker",
        href: route("class-records.wat.my-tracker"),
        icon: CalendarDaysIcon,
        roles: ["Administrator", "Faculty"],
      },
      {
        // Read-only monitoring for CID Chief (campus-wide) and Academic Unit
        // Heads (own unit, scoped server-side via Office.unit_head) — never
        // grants write access, the page itself enforces that.
        label: "Class Record Monitoring",
        routeName: "class-records.monitor.index",
        href: route("class-records.monitor.index"),
        icon: DocumentChartBarIcon,
        roles: ["Administrator", "CID Chief"],
        orRoles: ["AUH"],
      },
    ],
  },

  {
    label: "Learn",
    routeName: "learn.index",
    href: route("learn.index"),
    icon: AcademicCapIcon,
    roles: ["Administrator", "Faculty", "CID Chief"],
    orRoles: ["AUH"],
  },

  {
    label: "Homeroom Attendance",
    icon: UserGroupIcon,
    roles: ["Administrator", "Faculty", "CID Chief", "Registrar"],
    children: [
      {
        label: "Daily Attendance",
        routeName: "homeroom-attendance.index",
        href: route("homeroom-attendance.index"),
        icon: ClipboardDocumentListIcon,
        roles: [],
        permissions: ["homeroom-attendance.log"],
      },
      {
        label: "Activity Attendance",
        routeName: "homeroom-attendance.activities.index",
        href: route("homeroom-attendance.activities.index"),
        icon: CalendarDaysIcon,
        roles: [],
        permissions: ["homeroom-attendance.log"],
      },
      {
        label: "Flag Ceremony / Retreat",
        routeName: "homeroom-attendance.flag.index",
        href: route("homeroom-attendance.flag.index"),
        icon: FlagIcon,
        roles: [],
        permissions: ["homeroom-attendance.log"],
      },
      {
        label: "Record on Attendance & Punctuality",
        routeName: "homeroom-attendance.monthly-report.show",
        href: route("homeroom-attendance.monthly-report.show"),
        icon: ClipboardDocumentCheckIcon,
        roles: [],
        permissions: ["homeroom-attendance.log"],
      },
      {
        label: "Coordinator Review",
        routeName: "homeroom-attendance.coordinator.index",
        href: route("homeroom-attendance.coordinator.index"),
        icon: ClipboardDocumentCheckIcon,
        roles: [],
        permissions: ["homeroom-attendance.coordinator-review"],
      },
      {
        label: "Class Admission Slips",
        routeName: "homeroom-attendance.admission-slips.index",
        href: route("homeroom-attendance.admission-slips.index"),
        icon: DocumentCheckIcon,
        roles: [],
        permissions: ["homeroom-attendance.admission-slip.issue"],
      },
      {
        label: "Settings",
        routeName: "homeroom-attendance.settings.edit",
        href: route("homeroom-attendance.settings.edit"),
        icon: Cog6ToothIcon,
        roles: [],
        permissions: ["homeroom-attendance.settings.manage"],
      },
      {
        label: "Academic Calendar",
        routeName: "academic-calendar.index",
        href: route("academic-calendar.index"),
        icon: CalendarDaysIcon,
        roles: [],
        permissions: ["academic-calendar.manage"],
      },
    ],
  },

  {
    label: "Quiz",
    icon: PuzzlePieceIcon,
    roles: ["Administrator", "Faculty", "Staff", "MIS", "HR"],
    children: [
      {
        label: "Quizzes",
        routeName: "quiz.index",
        href: route("quiz.index"),
        icon: PuzzlePieceIcon,
        roles: [],
        permissions: ["quiz.manage", "quiz.view_all"],
      },
    ],
  },

  {
    label: "Teacher Attendance",
    icon: ClockIcon,
    roles: ["Administrator", "CID Chief", "AUH"],
    children: [
      {
        label: "Attendance Monitor",
        routeName: "teacher-attendance.index",
        href: route("teacher-attendance.index"),
        icon: ClipboardDocumentListIcon,
        roles: ["Administrator", "CID Chief", "AUH"],
      },
    ],
  },

  {
    label: "Faculty Loading",
    icon: AcademicCapIcon,
    roles: ["Administrator", "Faculty", "CID Chief", "OCD"],
    permissions: [
      "faculty_loading.view_own", "faculty_loading.view",
      "faculty_loading.manage", "faculty_loading.school_year",
      "faculty_loading.approve", "faculty_loading.reports",
      "faculty_loading.setup", "faculty_loading.vacancies",
      "faculty_loading.training", "faculty_loading.research_advisories",
    ],
    orRoles: ["ScheduleAdvisory"],
    children: [
      // ── Setup ───────────────────────────────────────────────────────────────
      {
        label: "School Years",
        routeName: "faculty-loading.school-years.index",
        href: route("faculty-loading.school-years.index"),
        icon: ClockIcon,
        roles: [],
        permissions: ["faculty_loading.school_year"],
      },
      {
        label: "Academic Units",
        routeName: "faculty-loading.academic-units.index",
        href: route("faculty-loading.academic-units.index"),
        icon: BuildingLibraryIcon,
        roles: [],
        permissions: ["faculty_loading.setup"],
      },
      {
        label: "Designations",
        routeName: "faculty-loading.designations.index",
        href: route("faculty-loading.designations.index"),
        icon: IdentificationIcon,
        roles: [],
        permissions: ["faculty_loading.setup"],
      },
      {
        label: "Subjects",
        routeName: "faculty-loading.subjects.index",
        href: route("faculty-loading.subjects.index"),
        icon: BookOpenIcon,
        roles: [],
        permissions: ["faculty_loading.subjects.view", "faculty_loading.subjects.manage"],
      },
      {
        label: "Classrooms",
        routeName: "faculty-loading.classrooms.index",
        href: route("faculty-loading.classrooms.index"),
        icon: TableCellsIcon,
        roles: [],
        permissions: ["faculty_loading.classrooms"],
      },
      // ── Faculty & Sections ──────────────────────────────────────────────────
      {
        label: "Supervisory",
        routeName: "faculty-loading.supervisory.index",
        href: route("faculty-loading.supervisory.index"),
        icon: ShieldCheckIcon,
        roles: [],
        permissions: ["faculty_loading.manage"],
      },
      {
        label: "Sections",
        routeName: "faculty-loading.sections.index",
        href: route("faculty-loading.sections.index"),
        icon: TableCellsIcon,
        roles: [],
        permissions: ["faculty_loading.manage"],
      },
      // ── Load Management ─────────────────────────────────────────────────────
      {
        label: "Load Assignments",
        routeName: "faculty-loading.assignments.index",
        href: route("faculty-loading.assignments.index"),
        icon: ClipboardDocumentListIcon,
        roles: [],
        permissions: ["faculty_loading.manage"],
      },
      {
        label: "Research Advisories",
        routeName: "faculty-loading.research-advisories.index",
        href: route("faculty-loading.research-advisories.index"),
        icon: BookOpenIcon,
        roles: [],
        permissions: ["faculty_loading.manage", "faculty_loading.research_advisories"],
      },
      {
        label: "Committee Assignments",
        routeName: "faculty-loading.committee-assignments.index",
        href: route("faculty-loading.committee-assignments.index"),
        icon: QueueListIcon,
        roles: [],
        permissions: ["faculty_loading.manage"],
      },
      {
        label: "Schedules",
        routeName: "faculty-loading.schedules.index",
        href: route("faculty-loading.schedules.index"),
        icon: CalendarDaysIcon,
        roles: [],
        permissions: ["faculty_loading.manage"],
        // Academic Unit Heads reach the calendar too — the controller scopes
        // them to their own unit's faculty (capability level "unit").
        orRoles: ["AUH", "ScheduleAdvisory"],
      },
      // Personal calendar for everyone — faculty AND managers see their own
      // schedule here; CID-plotted classes are read-only on this page.
      {
        label: "My Faculty Schedule",
        routeName: "faculty-loading.my-schedule",
        href: route("faculty-loading.my-schedule"),
        icon: CalendarDaysIcon,
        pinToTop: true,
        roles: [],
        permissions: ["faculty_loading.view_own", "faculty_loading.manage"],
      },
      {
        label: "Faculty List",
        routeName: "faculty-loading.faculty-list",
        href: route("faculty-loading.faculty-list"),
        icon: UsersIcon,
        roles: [],
        permissions: ["faculty_loading.manage"],
      },
      // ── AI Tools ────────────────────────────────────────────────────────────
      {
        label: "AI Dashboard",
        routeName: "faculty-loading.ai-dashboard",
        href: route("faculty-loading.ai-dashboard"),
        icon: CpuChipIcon,
        roles: [],
        permissions: ["faculty_loading.manage"],
      },
      {
        label: "Schedule Analytics",
        routeName: "faculty-loading.schedule-analytics.index",
        href: route("faculty-loading.schedule-analytics.index"),
        icon: PresentationChartLineIcon,
        roles: [],
        permissions: ["faculty_loading.manage", "faculty_loading.approve"],
      },
      {
        label: "Bell Schedule",
        routeName: "faculty-loading.bell-schedule.index",
        href: route("faculty-loading.bell-schedule.index"),
        icon: ClockIcon,
        // Administrator + CID Chief only (controller re-checks the role).
        roles: ["Administrator", "CID Chief"],
        permissions: [],
      },
      {
        label: "AI Schedule Generator",
        routeName: "faculty-loading.auto-schedule.index",
        href: route("faculty-loading.auto-schedule.index"),
        icon: SparklesIcon,
        roles: [],
        permissions: ["faculty_loading.manage"],
      },
      {
        label: "Load Balancing",
        routeName: "faculty-loading.load-balance.index",
        href: route("faculty-loading.load-balance.index"),
        icon: ScaleIcon,
        roles: [],
        permissions: ["faculty_loading.manage"],
      },
      // ── Overview & Records ──────────────────────────────────────────────────
      {
        label: "Faculty Loads",
        routeName: "faculty-loading.index",
        href: route("faculty-loading.index"),
        icon: UserGroupIcon,
        roles: [],
        permissions: ["faculty_loading.view"],
      },
      {
        label: "Faculty Vacancies",
        routeName: "faculty-loading.vacancies.index",
        href: route("faculty-loading.vacancies.index"),
        icon: UserPlusIcon,
        roles: [],
        permissions: ["faculty_loading.vacancies"],
      },
      {
        label: "Training Records",
        routeName: "faculty-loading.training-records.index",
        href: route("faculty-loading.training-records.index"),
        icon: AcademicCapIcon,
        roles: [],
        permissions: ["faculty_loading.training"],
      },
      // ── Finance & Reports ───────────────────────────────────────────────────
      {
        label: "Overload Pay",
        routeName: "faculty-loading.overload-computations.index",
        href: route("faculty-loading.overload-computations.index"),
        icon: BanknotesIcon,
        roles: [],
        permissions: ["faculty_loading.approve"],
      },
      {
        label: "Salary Schedules",
        routeName: "faculty-loading.salary-schedules.index",
        href: route("faculty-loading.salary-schedules.index"),
        icon: CurrencyDollarIcon,
        roles: [],
        permissions: ["faculty_loading.approve"],
      },
      {
        label: "Reports",
        routeName: "faculty-loading.reports.loads",
        href: route("faculty-loading.reports.loads"),
        icon: ChartBarIcon,
        roles: [],
        permissions: ["faculty_loading.reports"],
      },
      // ── Personal ────────────────────────────────────────────────────────────
      {
        label: "My Load Assignments",
        routeName: "faculty-loading.my-load",
        href: route("faculty-loading.my-load"),
        icon: DocumentTextIcon,
        pinToTop: true,
        roles: [],
        permissions: ["faculty_loading.view_own"],
      },
    ],
  },

  

  {
    type: "section",
    label: "Student Services",
    roles: ["Administrator", "Faculty", "Staff", "Student", "Parent"],
  },
  {
    label: "Registrar",
    icon: DocumentTextIcon,
    routeName: "registrar.enrollment.index",
    href: route("registrar.enrollment.index"),
    permissions: [
      "students.enrollment.view",
      "homeroom-attendance.admission-slip.issue",
    ],
    children: [
      {
        label: "Class Admission Slips",
        routeName: "homeroom-attendance.admission-slips.index",
        href: route("homeroom-attendance.admission-slips.index"),
        icon: DocumentCheckIcon,
        permissions: ["homeroom-attendance.admission-slip.issue"],
      },
      {
        label: "Students",
        routeName: "students.index",
        href: route("students.index"),
        icon: UserGroupIcon,
        roles: ["Administrator", "Registrar"],
      },
      {
        label: "Enrollment",
        routeName: "registrar.enrollment.index",
        href: route("registrar.enrollment.index"),
        icon: AcademicCapIcon,
        permissions: ["students.enrollment.view"],
      },
      {
        label: "Enrollment Periods",
        routeName: "registrar.enrollment-periods.index",
        href: route("registrar.enrollment-periods.index"),
        icon: CalendarDaysIcon,
        permissions: ["students.enrollment.manage"],
      },
      {
        label: "Enrollment Applications",
        routeName: "registrar.enrollment-applications.index",
        href: route("registrar.enrollment-applications.index"),
        icon: TableCellsIcon,
        permissions: ["students.enrollment.manage"],
      },
      {
        label: "Academic Policies",
        routeName: "registrar.academic-policies.index",
        href: route("registrar.academic-policies.index"),
        icon: ScaleIcon,
        permissions: ["students.policies.manage"],
      },
      {
        label: "Transcripts",
        routeName: "registrar.transcript.index",
        href: route("registrar.transcript.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["students.transcript.view"],
      },
      {
        label: "Promotion",
        routeName: "registrar.promotion.index",
        href: route("registrar.promotion.index"),
        icon: ArrowUpCircleIcon,
        permissions: ["students.promotion.process"],
      },
      {
        label: "Analytics",
        routeName: "registrar.analytics.index",
        href: route("registrar.analytics.index"),
        icon: ChartBarIcon,
        permissions: ["students.analytics.view"],
      },
    ],
  },
  {
    label: "Gate Attendance",
    icon: QueueListIcon,
    roles: ["Administrator"],
    permissions: ["students.attendance.view"],
    children: [
      {
        label: "Kiosk",
        routeName: "student-attendance.kiosk",
        href: route("student-attendance.kiosk"),
        icon: ComputerDesktopIcon,
        permissions: ["students.attendance.scan"],
      },
      {
        label: "Kiosk Devices",
        routeName: "student-attendance.devices.index",
        href: route("student-attendance.devices.index"),
        icon: ShieldCheckIcon,
        roles: ["Administrator"],
      },
      {
        label: "Attendance Logs",
        routeName: "student-attendance.logs.index",
        href: route("student-attendance.logs.index"),
        icon: ClipboardDocumentListIcon,
        permissions: ["students.attendance.view"],
      },
      {
        label: "Parent Contacts",
        routeName: "student-attendance.parents.index",
        href: route("student-attendance.parents.index"),
        icon: UserGroupIcon,
        permissions: ["students.attendance.view"],
      },
    ],
  },
  {
    label: "Student Clearance",
    icon: ClipboardDocumentListIcon,
    roles: ["Administrator", "Faculty", "Staff", "Registrar", "CID Chief", "Nurse", "Guidance", "Librarian"],
    permissions: [
      "students.clearance.view",
      "students.clearance.manage",
      "students.clearance.sign",
      "students.clearance.subject-sign",
      "students.clearance.adviser-review",
      "students.clearance.registrar",
      "students.clearance.report",
      "students.clearance.admin",
      "class-records.view",
    ],
    children: [
      {
        label: "Dashboard",
        routeName: "student-clearance.index",
        href: route("student-clearance.index"),
        icon: ChartBarIcon,
        permissions: ["students.clearance.view", "students.clearance.manage", "students.clearance.registrar"],
      },
      {
        label: "Signatory Queue",
        routeName: "student-clearance.queue",
        href: route("student-clearance.queue"),
        icon: ClipboardDocumentListIcon,
        permissions: [
          "students.clearance.sign",
          "students.clearance.subject-sign",
          "students.clearance.manage",
          "students.clearance.registrar",
          "class-records.view",
        ],
      },
    ],
  },
      {
        label: "Health Services",
        icon: HeartIcon,
        roles: ["Administrator", "Faculty", "Staff", "Student", "Parent", "Clinic","Nurse"],
        children: [
          {
            label: "Consultations",
            routeName: "consultations.index",
            href: route("consultations.index"),
            icon: ChatBubbleLeftRightIcon,
            permissions: ["health.view"],
          },
          {
            label: "Consultation Logs",
            routeName: "consultations.log.print",
            href: route("consultations.log.print"),
            icon: DocumentTextIcon,
            target: '_blank',
            permissions: ["health.view"],
          },
          {
            label: "Statistics Report",
            routeName: 'health.statistics.report',
            href: "#",
            icon: ChartBarIcon,
            permissions: ["health.view"],
          },
          {
            label: "Doctor's Schedule",
            routeName: "physician-schedule.index",
            href: route("physician-schedule.index"),
            icon: ClockIcon,
            permissions: ["health.manage"],
          },
          {
            label: "Student Medical Records",
            routeName: "students.health.index",
            href: route('students.health.index'),
            icon: UserIcon,
            permissions: ["students.health.view"],
          },
        ],
      },
  {
    label: "Guidance Services",
    icon: ChatBubbleLeftRightIcon,
    permissions: ["guidance.view", "guidance.refer", "guidance.manage", "guidance.cumulative.view", "guidance.cumulative.manage"],
    children: [
      {
        label: "Dashboard",
        routeName: "guidance.dashboard",
        href: "/guidance/dashboard",
        icon: ChartBarIcon,
        permissions: ["guidance.view"],
      },
      {
        label: "Consultations",
        routeName: "guidance.consultations.index",
        href: route('guidance.consultations.index'),
        icon: ClipboardDocumentListIcon,
        permissions: ["guidance.view"],
      },
      {
        label: "Refer to Guidance",
        routeName: "guidance.refer",
        href: "/guidance/refer",
        icon: ClipboardDocumentListIcon,
        permissions: ["guidance.refer"],
      },
      {
        label: "Session Reports",
        routeName: "guidance.session-reports.index",
        href: "/guidance/session-reports",
        icon: DocumentTextIcon,
        permissions: ["guidance.manage"],
      },
      {
        label: "Transaction Reports",
        routeName: "guidance.reports",
        href: "/guidance/reports",
        icon: DocumentChartBarIcon,
        permissions: ["guidance.view"],
      },
      {
        label: "Cumulative Records",
        routeName: "guidance.cumulative.index",
        href: route('guidance.cumulative.index'),
        icon: UserIcon,
        permissions: ["guidance.cumulative.view"],
      },
    ],
  },
  {
    label: "Student Discipline",
    icon: ShieldCheckIcon,
    permissions: ["discipline.file", "discipline.view", "discipline.manage"],
    children: [
      {
        label: "File a Report",
        routeName: "discipline.cases.create",
        href: "/discipline/cases/create",
        icon: ClipboardDocumentListIcon,
        permissions: ["discipline.file"],
      },
      {
        label: "Cases",
        routeName: "discipline.cases.index",
        href: "/discipline/cases",
        icon: DocumentTextIcon,
        permissions: ["discipline.view", "discipline.manage"],
      },
      {
        label: "Offense Catalog",
        routeName: "discipline.offenses.index",
        href: "/discipline/offenses",
        icon: BookOpenIcon,
        permissions: ["discipline.manage"],
      },
      {
        label: "Confiscated Items",
        routeName: "discipline.confiscated.index",
        href: "/discipline/confiscated",
        icon: ArchiveBoxIcon,
        permissions: ["discipline.manage"],
      },
    ],
  },
  {
    label: "Residence Hall",
    icon: HomeModernIcon,
    permissions: [
      "rh.dashboard.view", "rh.applications.view", "rh.applications.evaluate",
      "rh.applications.approve", "rh.interns.view", "rh.interns.manage",
      "rh.rooms.manage", "rh.leave-passes.view", "rh.leave-passes.approve",
      "rh.leave-passes.guard", "rh.housekeeping.manage", "rh.incidents.manage",
      "rh.fees.manage",
    ],
    children: [
      {
        label: "Dashboard",
        routeName: "rh.dashboard",
        href: "/rh/dashboard",
        icon: HomeModernIcon,
        permissions: ["rh.dashboard.view"],
      },
      {
        label: "Applications",
        routeName: "rh.applications.index",
        href: "/rh/applications",
        icon: DocumentTextIcon,
        permissions: ["rh.applications.view", "rh.applications.evaluate", "rh.applications.approve"],
      },
      {
        label: "Dormers",
        routeName: "rh.interns.index",
        href: "/rh/interns",
        icon: UserGroupIcon,
        permissions: ["rh.interns.view", "rh.interns.manage"],
      },
      {
        label: "Leave Passes",
        routeName: "rh.leave-passes.index",
        href: "/rh/leave-passes",
        icon: ClockIcon,
        permissions: ["rh.leave-passes.view", "rh.leave-passes.approve", "rh.leave-passes.guard"],
      },
      {
        label: "Housekeeping",
        routeName: "rh.housekeeping.index",
        href: "/rh/housekeeping",
        icon: ClipboardDocumentListIcon,
        permissions: ["rh.housekeeping.manage"],
      },
      {
        label: "Incidents",
        routeName: "rh.incidents.index",
        href: "/rh/incidents",
        icon: HeartIcon,
        permissions: ["rh.incidents.manage"],
      },
      {
        label: "Fee Ledger",
        routeName: "rh.fees.index",
        href: "/rh/fees",
        icon: BanknotesIcon,
        permissions: ["rh.fees.manage"],
      },
      {
        label: "Rooms",
        routeName: "rh.rooms.index",
        href: "/rh/rooms",
        icon: HomeModernIcon,
        permissions: ["rh.rooms.manage"],
      },
    ],
  },
  {
    label: "Library Services",
    icon: BookOpenIcon,
    roles: ["Administrator", "Librarian"],
    children: [
      {
        label: "Library Attendance",
        routeName: "library.attendance.index",
        href: route('library.attendance.index'),
        icon: ClipboardDocumentListIcon,
        permissions: ["library.manage"],
      },
      {
        label: "Collections",
        routeName: "library.collections.index",
        href: route('library.collections.index'),
        icon: ArchiveBoxIcon,
        permissions: ["library.manage"],
      },
      {
        label: "Collection Categories",
        routeName: "library.collection-categories.index",
        href: route('library.collection-categories.index'),
        icon: BookOpenIcon,
        permissions: ["library.manage"],
      },
      {
        label: "Borrowing",
        routeName: "library.borrowings.index",
        href: route('library.borrowings.index'),
        icon: BookOpenIcon,
        permissions: ["library.view"],
      },
      {
        label: "Statistics Report",
        routeName: "library.statistics.report",
        href: '#',
        icon: ChartBarIcon,
        permissions: ["library.manage"],
      },
    ],
  },
  // {
  //   label: "Residence Hall",
  //   icon: HomeModernIcon,
  //   roles: ["Administrator", "Faculty", "Staff", "Student", "Parent"],
  //   children: [
  //     {
  //       label: "PDS",
  //       routeName: null,
  //       href: "#",
  //       icon: ClipboardDocumentListIcon,
  //       roles: ["Administrator", "Faculty", "Staff", "Student", "Parent"],
  //     },
  //   ],
  // },
  {
    type: "section",
    label: "Reports",
    roles: ["Administrator", "Faculty", "Staff"],
  },
  {
    label: "Reports",
    icon: DocumentTextIcon,
    roles: ["Administrator", "Faculty", "Staff"],
    children: [
      {
        label: "Monthly Reports",
        routeName: "reports.index",
        href: route("reports.index"),
        icon: ChartBarIcon,
        permissions: ["reports.view"],
      },
      {
        label: "Audit Logs",
        routeName: "reports.audit_logs",
        href: route("reports.audit_logs"),
        icon: DocumentTextIcon,
        permissions: ["roles.assign"],
      },
    ],
  },
  {
    label: "Chat",
    routeName: "chat.index",
    href: "/chat",
    icon: ChatBubbleOvalLeftEllipsisIcon,
    roles: [],
    permissions: ["chat.access"],
  },
];
